// Code generated by ego generate from memory.ego. DO NOT EDIT.

package messenger

import (
	"context"
	"slices"
	"sync"
	"time"
)

// Browser is a transport whose messages can be listed and removed, as the
// failure transport's are by messenger:failed:show and remove.
//
//line memory.ego:12
type Browser interface {
	Transport
	// List returns the messages, available or not, oldest first.
	List(ctx context.Context) ([]Message, error)
	// Remove removes the message with the ID, if it is there.
	Remove(ctx context.Context, id string) error
}

// MemoryTransport keeps messages in memory: for tests, and for work that
// may be lost when the process stops. Its zero value is ready.
type MemoryTransport struct {
	// Now is the clock; nil means time.Now.
	Now func() time.Time

	mu       sync.Mutex
	messages []*kept
	leases   int
}

// kept is a message in memory, with its lease.
type kept struct {
	msg   Message
	until time.Time // the end of its lease
	lease int       // which lease holds it
}

func (t *MemoryTransport) now() time.Time {
	v := t.Now
	if v == nil {
		v = time.Now
	}
	return (v)()
}

//line memory.ego:42
func (t *MemoryTransport) Send(ctx context.Context, m Message) error {
	t.mu.Lock()
	defer t.mu.Unlock()
	t.messages = append(t.messages, &kept{msg: m})
	return nil
}

func (t *MemoryTransport) Receive(ctx context.Context, ttl time.Duration) (Lease, bool, error) {
	t.mu.Lock()
	defer t.mu.Unlock()
	now := t.now()
	var next *kept
	for _, k := range t.messages {
		if !k.msg.AvailableAt.After(now) && !k.until.After(now) && (next == nil || k.msg.AvailableAt.Before(next.msg.AvailableAt)) {
			next = k
		}
	}
	if next == nil {
		return nil, false, nil
	}
	t.leases++
	next.until, next.lease = now.Add(ttl), t.leases
	return &memoryLease{t: t, k: next, id: t.leases}, true, nil
}

func (t *MemoryTransport) List(ctx context.Context) ([]Message, error) {
	t.mu.Lock()
	defer t.mu.Unlock()
	out := make([]Message, len(t.messages))
	for i, k := range t.messages {
		out[i] = k.msg
	}
	slices.SortStableFunc(out, func(a, b Message) int { return a.AvailableAt.Compare(b.AvailableAt) })
	return out, nil
}

func (t *MemoryTransport) Remove(ctx context.Context, id string) error {
	t.mu.Lock()
	defer t.mu.Unlock()
	t.messages = slices.DeleteFunc(t.messages, func(k *kept) bool { return k.msg.ID == id })
	return nil
}

// memoryLease is a lease of a message in memory.
type memoryLease struct {
	t  *MemoryTransport
	k  *kept
	id int
}

func (l *memoryLease) Message() Message { return l.k.msg }

// held reports whether the lease still holds its message; t.mu is held.
func (l *memoryLease) held() bool {
	return l.k.lease == l.id && l.k.until.After(l.t.now()) && slices.Contains(l.t.messages, l.k)
}

func (l *memoryLease) Extend(ctx context.Context, ttl time.Duration) (bool, error) {
	l.t.mu.Lock()
	defer l.t.mu.Unlock()
	if !l.held() {
		return false, nil
	}
	l.k.until = l.t.now().Add(ttl)
	return true, nil
}

func (l *memoryLease) Ack(ctx context.Context) error {
	l.t.mu.Lock()
	defer l.t.mu.Unlock()
	if l.k.lease == l.id {
		l.t.messages = slices.DeleteFunc(l.t.messages, func(k *kept) bool { return k == l.k })
	}
	return nil
}

func (l *memoryLease) Retry(ctx context.Context, m Message) error {
	l.t.mu.Lock()
	defer l.t.mu.Unlock()
	if l.k.lease == l.id {
		l.k.msg, l.k.until = m, time.Time{}
	}
	return nil
}
