// Code generated by ego generate from annotations.ego. DO NOT EDIT.

package main

import (
	"fmt"
	"go/ast"
	"go/token"
	"go/types"
	"sort"
	"strconv"
	"strings"

	"golang.org/x/tools/go/packages"
	"golang.org/x/tools/go/types/typeutil"
)

// annotations returns the body of the autoOpenAPI provider: the doc
// comments of the app's endpoints, the errors each one can fail with, and
// the doc comments of the types they take and return.
//
// An endpoint is a function or method passed to httpkernel.Endpoint in one
// of the module's packages. The errors it can fail with are the error cases
// it builds, in its body and in the functions it calls, through the
// module's packages and goncini's: an error case is a struct type that the
// kernel answers for, as a case of an error set that a mapper maps
// (httpkernel.Map), or a ProblemError.
//
//line annotations.ego:25
func (a *app) annotations() string {
	x := a.newCrawler()
	var ops, docs []string
	types_ := map[*types.TypeName]bool{}
	for _, fn := range x.endpoints() {
		decl := x.decls[fn]
		var cases []string
		for _, c := range x.cases(fn) {
			cases = append(cases, a.typeString(c)+"{}")
		}
		summary, desc := opDoc(fn.Name(), decl.fd.Doc.Text())
		fields := []string{}
		if summary != "" {
			fields = append(fields, "Summary: "+strconv.Quote(summary))
		}
		if desc != "" {
			fields = append(fields, "Description: "+strconv.Quote(desc))
		}
		if len(cases) > 0 {
			fields = append(fields, "Errors: []error{"+strings.Join(cases, ", ")+"}")
		}
		if len(fields) > 0 {
			ops = append(ops, fmt.Sprintf("\t\t\t%q: {%s},\n", runtimeName(fn), strings.Join(fields, ", ")))
		}
		sig := fn.Type().(*types.Signature)
		if sig.Params().Len() == 2 && sig.Results().Len() == 2 {
			x.collectTypes(sig.Params().At(1).Type(), types_)
			x.collectTypes(sig.Results().At(0).Type(), types_)
		}
	}
	var names []*types.TypeName
	for tn := range types_ {
		names = append(names, tn)
	}
	sort.Slice(names, func(i, j int) bool {
		return names[i].Pkg().Path()+"."+names[i].Name() < names[j].Pkg().Path()+"."+names[j].Name()
	})
	for _, tn := range names {
		if d := x.typeDoc(tn); d != "" {
			docs = append(docs, fmt.Sprintf("\t\t\treflect.TypeFor[%s](): %s,\n", a.typeString(tn.Type()), d))
		}
	}
	sort.Strings(ops)
	var b strings.Builder
	b.WriteString(a.typeString(a.lookup("openapi.Annotations")) + "{\n")
	if len(ops) > 0 {
		b.WriteString("\t\tOperations: map[string]" + a.typeString(a.lookup("openapi.OperationDoc")) + "{\n" + strings.Join(ops, "") + "\t\t},\n")
	}
	if len(docs) > 0 {
		a.imports["reflect"] = "reflect"
		b.WriteString("\t\tTypes: map[reflect.Type]" + a.typeString(a.lookup("openapi.TypeDoc")) + "{\n" + strings.Join(docs, "") + "\t\t},\n")
	}
	b.WriteString("\t}")
	return b.String()
}

// crawler finds the endpoints of a module, and what their code builds.
type crawler struct {
	a       *app
	decls   map[*types.Func]decl       // the functions of the module's and goncini's packages
	specs   map[*types.TypeName]tspec  // the types of the module's packages
	sets    []*types.Interface         // the error sets that mappers map
	problem *types.Interface           // httpkernel.ProblemError
	module  map[*packages.Package]bool // the module's packages
}

// decl is a function's declaration, in its package.
type decl struct {
	fd  *ast.FuncDecl
	pkg *packages.Package
}

// tspec is a type's declaration, with its doc comment.
type tspec struct {
	ts  *ast.TypeSpec
	doc string
	pkg *packages.Package
}

func (a *app) newCrawler() *crawler {
	x := &crawler{a: a, decls: map[*types.Func]decl{}, specs: map[*types.TypeName]tspec{}, module: map[*packages.Package]bool{}}
	for _, p := range a.all {
		x.module[p] = true
	}
	if pe := a.lookup("httpkernel.ProblemError"); pe != nil {
		x.problem = pe.Underlying().(*types.Interface)
	}
	packages.Visit(a.all, nil, func(p *packages.Package) {
		if !x.module[p] && p.PkgPath != gonciniPath && !strings.HasPrefix(p.PkgPath, gonciniPath+"/") {
			return
		}
		for _, f := range p.Syntax {
			for _, d := range f.Decls {
				switch d := d.(type) {
				case *ast.FuncDecl:
					if fn, ok := p.TypesInfo.Defs[d.Name].(*types.Func); ok && d.Body != nil {
						x.decls[fn] = decl{d, p}
					}
				case *ast.GenDecl:
					gd := d
					if gd.Tok != token.TYPE || !x.module[p] {
						continue
					}
					for _, s := range gd.Specs {
						ts := s.(*ast.TypeSpec)
						text := ts.Doc.Text()
						if text == "" && len(gd.Specs) == 1 {
							text = gd.Doc.Text()
						}
						if tn, ok := p.TypesInfo.Defs[ts.Name].(*types.TypeName); ok {
							x.specs[tn] = tspec{ts, text, p}
						}
					}
				}
			}
		}
		for id, inst := range p.TypesInfo.Instances {
			if x.isFunc(p, id, "httpkernel", "Map") && inst.TypeArgs.Len() == 1 {
				if set, ok := inst.TypeArgs.At(0).Underlying().(*types.Interface); ok {
					x.sets = append(x.sets, set)
				}
			}
		}
	})
	return x
}

// isFunc reports whether id, in p, names goncini's function pkg.name.
func (x *crawler) isFunc(p *packages.Package, id *ast.Ident, pkg, name string) bool {
	obj := p.TypesInfo.Uses[id]
	return obj != nil && obj.Name() == name && obj.Pkg() != nil && obj.Pkg().Path() == gonciniPath+"/"+pkg
}

// endpoints returns the functions and methods that the module's packages
// pass to httpkernel.Endpoint, sorted by their names.
func (x *crawler) endpoints() []*types.Func {
	seen := map[*types.Func]bool{}
	var fns []*types.Func
	for _, p := range x.a.all {
		for _, f := range p.Syntax {
			ast.Inspect(f, func(n ast.Node) bool {
				call, ok := n.(*ast.CallExpr)
				if !ok || len(call.Args) != 1 || !x.isFunc(p, calleeIdent(call.Fun), "httpkernel", "Endpoint") {
					return true
				}
				var fn *types.Func
				switch arg := call.Args[0].(type) {
				case *ast.SelectorExpr:
					if s := p.TypesInfo.Selections[arg]; s != nil {
						fn, _ = s.Obj().(*types.Func)
					} else {
						fn, _ = p.TypesInfo.Uses[arg.Sel].(*types.Func)
					}
				case *ast.Ident:
					fn, _ = p.TypesInfo.Uses[arg].(*types.Func)
				}
				if fn != nil && !seen[fn] && x.decls[fn].fd != nil {
					seen[fn] = true
					fns = append(fns, fn)
				}
				return true
			})
		}
	}
	sort.Slice(fns, func(i, j int) bool { return runtimeName(fns[i]) < runtimeName(fns[j]) })
	return fns
}

// calleeIdent is the name of a called function, through its type
// arguments: Endpoint in httpkernel.Endpoint[In, Out](h).
func calleeIdent(fun ast.Expr) *ast.Ident {
	switch ix := fun.(type) {
	case *ast.IndexExpr:
		return ident(ix.X)
	case *ast.IndexListExpr:
		return ident(ix.X)
	}
	return ident(fun)
}

// runtimeName is the name of fn that the runtime gives it, which
// httpkernel.Description.Func is: example.com/api/articles.(*Articles).Show.
func runtimeName(fn *types.Func) string {
	sig := fn.Type().(*types.Signature)
	if sig.Recv() == nil {
		return fn.Pkg().Path() + "." + fn.Name()
	}
	recv := sig.Recv().Type()
	ptr, isPtr := recv.(*types.Pointer)
	if isPtr {
		recv = ptr.Elem()
	}
	named := recv.(*types.Named)
	name := named.Obj().Name()
	if named.TypeParams().Len() > 0 || named.TypeArgs().Len() > 0 {
		name += "[...]" // as the runtime writes a generic type's methods
	}
	if isPtr {
		return fn.Pkg().Path() + ".(*" + name + ")." + fn.Name()
	}
	return fn.Pkg().Path() + "." + name + "." + fn.Name()
}

// cases returns the error cases that fn builds, or the functions it calls
// do, sorted by their packages and names.
func (x *crawler) cases(fn *types.Func) []*types.Named {
	found := map[*types.Named]bool{}
	x.crawl(fn.Origin(), found, map[*types.Func]bool{})
	var out []*types.Named
	for n := range found {
		out = append(out, n)
	}
	sort.Slice(out, func(i, j int) bool {
		return out[i].Obj().Pkg().Path()+"."+out[i].Obj().Name() < out[j].Obj().Pkg().Path()+"."+out[j].Obj().Name()
	})
	return out
}

// crawl adds the error cases that fn's body builds, and the functions it
// calls statically, to found.
func (x *crawler) crawl(fn *types.Func, found map[*types.Named]bool, seen map[*types.Func]bool) {
	d, ok := x.decls[fn]
	if !ok || seen[fn] {
		return
	}
	seen[fn] = true
	info := d.pkg.TypesInfo
	ast.Inspect(d.fd.Body, func(n ast.Node) bool {
		switch n := n.(type) {
		case *ast.CompositeLit:
			if named, ok := types.Unalias(info.TypeOf(n)).(*types.Named); ok && x.isCase(named) {
				found[named] = true
			}
		case *ast.CallExpr:
			if callee := typeutil.StaticCallee(info, n); callee != nil {
				x.crawl(callee.Origin(), found, seen)
			}
		}
		return true
	})
}

// isCase reports whether t is an error case that the kernel answers for:
// an exported struct type that a mapper's error set has, or a
// ProblemError.
func (x *crawler) isCase(t *types.Named) bool {
	if _, ok := t.Underlying().(*types.Struct); !ok || !t.Obj().Exported() || t.TypeArgs().Len() > 0 {
		return false
	}
	if t.Obj().Pkg().Path() == gonciniPath+"/httpkernel" && t.Obj().Name() == "Problem" {
		return false // its status is a value
	}
	for _, set := range x.sets {
		if types.Implements(t, set) {
			return true
		}
	}
	return x.problem != nil && types.Implements(t, x.problem)
}

// collectTypes adds the named types of the module that t holds, through
// pointers, slices, maps, struct fields and type arguments.
func (x *crawler) collectTypes(t types.Type, found map[*types.TypeName]bool) {
	switch t := types.Unalias(t).(type) {
	case *types.Pointer:
		x.collectTypes(t.Elem(), found)
	case *types.Slice:
		x.collectTypes(t.Elem(), found)
	case *types.Array:
		x.collectTypes(t.Elem(), found)
	case *types.Map:
		x.collectTypes(t.Elem(), found)
	case *types.Struct:
		for i := range t.NumFields() {
			x.collectTypes(t.Field(i).Type(), found)
		}
	case *types.Named:
		for i := range t.TypeArgs().Len() {
			x.collectTypes(t.TypeArgs().At(i), found)
		}
		tn := t.Obj()
		if found[tn] {
			return
		}
		if _, ok := x.specs[tn]; ok && tn.Exported() && t.TypeArgs().Len() == 0 {
			found[tn] = true
			x.collectTypes(t.Underlying(), found)
		}
	}
}

// typeDoc returns the openapi.TypeDoc literal of tn, "" if it has no doc
// comments.
func (x *crawler) typeDoc(tn *types.TypeName) string {
	s := x.specs[tn]
	var fields []string
	if st, ok := s.ts.Type.(*ast.StructType); ok {
		fields = fieldDocs(st, "")
	}
	desc := strings.TrimSpace(s.doc)
	if desc == "" && len(fields) == 0 {
		return ""
	}
	var parts []string
	if desc != "" {
		parts = append(parts, "Description: "+strconv.Quote(desc))
	}
	if len(fields) > 0 {
		parts = append(parts, "Fields: map[string]string{"+strings.Join(fields, ", ")+"}")
	}
	return "{" + strings.Join(parts, ", ") + "}"
}

// fieldDocs returns the doc comments of a struct's fields, as map entries
// by their paths: through anonymous structs, the names of their fields
// after prefix.
func fieldDocs(st *ast.StructType, prefix string) []string {
	var out []string
	for _, f := range st.Fields.List {
		text := strings.TrimSpace(f.Doc.Text())
		if text == "" {
			text = strings.TrimSpace(f.Comment.Text())
		}
		for _, name := range f.Names {
			if !name.IsExported() {
				continue
			}
			if text != "" {
				out = append(out, fmt.Sprintf("%q: %q", (prefix+name.Name), text))
			}
			if inner, ok := f.Type.(*ast.StructType); ok {
				out = append(out, fieldDocs(inner, prefix+name.Name+".")...)
			}
		}
	}
	return out
}

// opDoc splits an endpoint's doc comment into a summary, its first
// sentence, and a description, the rest. A comment that starts with the
// method's name, as Go's do, has it dropped from the summary: "Show
// returns the article." is "Returns the article."
func opDoc(name, text string) (summary, description string) {
	text = strings.TrimSpace(text)
	end := len(text)
	if i := strings.Index(text, "\n\n"); i >= 0 {
		end = i
	}
	for _, sep := range []string{". ", ".\n"} {
		if i := strings.Index(text[:end], sep); i >= 0 && i+1 < end {
			end = i + 1
		}
	}
	summary = strings.Join(strings.Fields(text[:end]), " ")
	description = strings.TrimSpace(text[end:])
	if rest, ok := strings.CutPrefix(summary, name+" "); ok && rest != "" {
		summary = exported(rest)
	}
	return summary, description
}

// exported returns s with its first letter upper case.
func exported(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
