// Code generated by ego generate from webtest.ego. DO NOT EDIT.

// Package webtest tests goncini apps: Boot builds an app as Main does, in
// the test environment; a Client sends it requests in process and checks
// the responses; Run runs its commands; and Isolate runs a test in a
// database transaction that is rolled back.
//
//	func TestShow(t *testing.T) {
//		a := webtest.Boot(t, config.Load, app.Build)
//		webtest.Run(t, a, "db:migrate")
//		c := webtest.NewClient(t, a.Kernel)
//		c.Post("/articles", `{"title":"Hello","body":"…"}`).Status(201)
//		var art articles.Article
//		c.Get("/articles/hello").Status(200).JSON(&art)
//		c.Get("/articles/nope").Problem(404)
//	}
//
// Everything works inside a testing/synctest bubble, so that tests of
// timeouts and schedules run on a fake clock.
package webtest

import (
	"bytes"
	"context"
	"strings"
	"testing"

	"github.com/goncini/goncini"
	"github.com/goncini/goncini/console"
	"github.com/goncini/goncini/db"

	"github.com/effect-go/effect-go/scope"
)

// Boot builds an app for a test, as goncini.Main does in the test
// environment: with the .env files of goncini.ProjectDir for test, the
// config that load makes for it, and build, usually the app's injector.
// The app's scope closes, and its resources are released, when the test
// ends.
//
// build can be an injector of the test's own that returns more than the
// app, such as a struct with the app and its database, for Isolate.
//
//line webtest.ego:39
func Boot[C, A any](t testing.TB, load func(*goncini.Env) C, build func(context.Context, *scope.Scope, C) (A, error)) A {
	t.Helper()
	var app A
	_, cfg, err := goncini.Load(goncini.ProjectDir(), "test", load)
	if err != nil {
		t.Fatal(err)
		return app
	}
	built := make(chan A, 1)
	stop := make(chan struct{})
	done := make(chan error, 1)
	go func() {
		_, err := scope.Run(context.Background(), func(s *scope.Scope) (struct{}, error) {
			app, err := build(s.Context(), s, cfg)
			if err != nil {
				return struct{}{}, err
			}
//line webtest.ego:53
			built <- app
			<-stop
			return struct{}{}, nil
		})
		done <- err
	}()
	select {
	case app = <-built:
		t.Cleanup(func() {
			close(stop)
			if err := <-done; err != nil {
				t.Errorf("closing the app: %v", err)
			}
		})
	case err := <-done:
		t.Fatalf("building the app: %v", err)
	}
	return app
}

// Run runs one of app's own commands with args, such as db:migrate to
// create a test database's tables, and returns its output. The test fails
// if the command does.
//
//	webtest.Run(t, app, "db:migrate")
func Run(t testing.TB, app *goncini.App, args ...string) string {
	t.Helper()
	var out bytes.Buffer
	if err := console.Run(t.Context(), &out, app.Commands, "", args); err != nil {
		t.Fatalf("%s: %v", strings.Join(args, " "), err)
	}
	return out.String()
}

// Isolate begins a transaction of the database that iso stands for, such
// as a db.SQL, and returns a context in which the database is queried in
// it; the transaction is rolled back when the test ends, so that the test
// leaves the database as it found it. The app's own transactions join it,
// so their commits don't end it.
//
// A client with that context sends requests that query in the
// transaction:
//
//	ctx := webtest.Isolate(t, a.SQL)
//	c := webtest.NewClient(t, a.App.Kernel).WithContext(ctx)
//
// A transaction is one connection: requests in it must not run in
// parallel, and the app must query through the adapter's Conn, not the
// pool.
func Isolate(t testing.TB, iso db.Isolator) context.Context {
	t.Helper()
	// Not t.Context(), which ends before the cleanups run: database/sql
	// rolls back a transaction whose context ends.
	ctx, rollback, err := iso.Isolate(context.WithoutCancel(t.Context()))
	if err != nil {
		t.Fatalf("isolating the test: %v", err)
	}
	t.Cleanup(func() {
		if err := rollback(); err != nil {
			t.Errorf("rolling back the test's transaction: %v", err)
		}
	})
	return ctx
}
