// Code generated by ego generate from main.ego. DO NOT EDIT.

package goncini

import (
	"bytes"
	"context"
	"encoding/json/jsontext"
	"encoding/json/v2"
	"flag"
	"fmt"
	"io"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/goncini/goncini/console"
	"github.com/goncini/goncini/httpkernel"
	"github.com/goncini/goncini/routing"

	"github.com/effect-go/effect-go/scope"
)

// Main runs an app from its command line, as its main function does:
//
//	func main() { goncini.Main(config.Load, app.Build) }
//
// It loads the environment named by APP_ENV from the process and the .env
// files of ProjectDir, then the config with load, and fails with every
// missing secret at once. It then builds the app with build, in a scope
// that SIGINT and SIGTERM cancel, and runs the command that the arguments
// name, as Run does.
//
// A mistake in the command line, such as an unknown command, is printed and
// exits with status 2. Anything else that fails is logged, and exits with
// status 1.
//
//line main.ego:35
func Main[C any](load func(*Env) C, build func(context.Context, *scope.Scope, C) (*App, error)) {
	env, cfg, err := Load(ProjectDir(), "", load)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	var usage error
	scope.Main(func(s *scope.Scope) error {
		app, err2 := build(s.Context(), s, cfg)
		if err2 != nil {
			return err2
		}
		slog.SetDefault(app.Logger)
		err := Run(s.Context(), os.Stdout, env, cfg, app, os.Args[1:])
		if console.IsUsage(err) {
			usage = err
			return nil
		}
		return err
	})
//line main.ego:52
	if usage != nil {
		fmt.Fprintln(os.Stderr, usage)
		os.Exit(2)
	}
}

// Load returns the environment named name, loaded from dir as LoadEnv does,
// and the config that load makes for it. It fails with the reasons of
// Env.Err: an unknown environment and every missing secret.
func Load[C any](dir, name string, load func(*Env) C) (*Env, C, error) {
	var cfg C
	env, err := LoadEnv(dir, name)
	if err != nil {
		return nil, *new(C), err
	}
//line main.ego:64
	cfg = load(env)
	if err := env.Err(); err != nil {
		return nil, *new(C), err
	}
//line main.ego:66
	return env, cfg, nil
}

// ProjectDir returns the directory of the app's .env files: the nearest one
// that holds a go.mod file, from the working directory up, which is the
// app's own when it runs through go run or go test; or else the working
// directory, as for a deployed binary.
func ProjectDir() string {
	wd, err := os.Getwd()
	if err != nil {
		wd = "."
	}
//line main.ego:75
	for dir := wd; ; dir = filepath.Dir(dir) {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		if filepath.Dir(dir) == dir {
			return wd
		}
	}
}

// Run runs the command of app that args[0] names, with the rest of args,
// writing its output to out: serve when args is empty. Besides the app's
// own commands, there are:
//   - serve, which runs the app's checks, then serves it over HTTP until
//     ctx is done, and shuts down gracefully; -addr overrides the address
//     of the config, for a developer whose port is taken;
//   - debug:router, which lists the routes;
//   - debug:config, which prints cfg as JSON, with the values of env's
//     secrets masked, and without its zero values, which are defaults;
//   - list and help, which describe the commands.
func Run[C any](ctx context.Context, out io.Writer, env *Env, cfg C, app *App, args []string) error {
	commands := []console.Command{
		serveCommand{app.Server, app.Checks},
		console.New("debug:router", "Lists the routes", func(ctx context.Context, out io.Writer, args []string) error {
			return routing.WriteTable(out, app.Router.List())
		}),
		console.New("debug:config", "Prints the config, with secrets masked", func(ctx context.Context, out io.Writer, args []string) error { return writeConfig(out, env, cfg) }),
	}
	return console.Run(ctx, out, append(commands, app.Commands...), "serve", args)
}

// serveCommand serves the app until ctx is done, once its checks pass.
type serveCommand struct {
	server *httpkernel.Server
	checks []Check
}

func (serveCommand) Name() string    { return "serve" }
func (serveCommand) Summary() string { return "Serves the app over HTTP" }

func (c serveCommand) Flags(fs *flag.FlagSet) {
	fs.StringVar(&c.server.Addr, "addr", c.server.Addr, "the TCP address to listen on, instead of the config's")
}

func (c serveCommand) Run(ctx context.Context, out io.Writer, args []string) error {
	if len(args) > 0 {
		return console.Usage{Command: "serve", Reason: fmt.Sprintf("unexpected argument %q", args[0])}
	}
	for _, check := range c.checks {
		if err := check(ctx); err != nil {
			return fmt.Errorf("goncini: the app isn't ready to serve: %w", err)
		}
	}
	return c.server.ListenAndServe(ctx)
}

// writeConfig writes cfg as indented JSON, without its zero values, which
// are defaults, and with the values of env's secrets masked in its strings.
func writeConfig(out io.Writer, env *Env, cfg any) error {
	durations := json.MarshalToFunc(func(enc *jsontext.Encoder, d time.Duration) error { return enc.WriteToken(jsontext.String(d.String())) })
	b, err := json.Marshal(cfg, json.OmitZeroStructFields(true), json.WithMarshalers(durations))
	if err != nil {
		return err
	}
//line main.ego:134
	dec := jsontext.NewDecoder(bytes.NewReader(b))
	enc := jsontext.NewEncoder(out, jsontext.WithIndent("  "))
	for {
		tok, err := dec.ReadToken()
		if err == io.EOF {
			return nil
		}
		if err != nil {
			return err
		}
//line main.ego:142
		if tok.Kind() == '"' {
			s := tok.String()
			for _, secret := range env.read {
				s = strings.ReplaceAll(s, secret, "******")
			}
			tok = jsontext.String(s)
		}
		if err := enc.WriteToken(tok); err != nil {
			return err
		}
	}
}
