// Code generated by ego generate from migrations.ego. DO NOT EDIT.

// Package migrations holds the database's migrations, for goose: run them
// with db:migrate.
package migrations

import "embed"

// FS is the migrations, embedded in the binary.
//
//go:embed *.sql
//line migrations.ego:10
var FS embed.FS
