// Code generated by goncini generate. DO NOT EDIT.

package app

import (
	"database/sql"

	"github.com/effect-go/effect-go/layer"
	"github.com/goncini/goncini"
	"github.com/goncini/goncini/console"
	"github.com/goncini/goncini/db"
	"github.com/goncini/goncini/examples/realworld/articles"
	"github.com/goncini/goncini/examples/realworld/conduit"
	"github.com/goncini/goncini/examples/realworld/config"
	"github.com/goncini/goncini/examples/realworld/users"
	"github.com/goncini/goncini/httpkernel"
	"github.com/goncini/goncini/security"
)

// Autoconfigured hands goncini the app's services of each kind it uses,
// found by their types, and each part of goncini its config section.
var Autoconfigured = layer.Set(autoProblems, autoCommands, autoChecks, autoServices, autoConfigHTTP, autoConfigLog, autoConfigDB, autoConfigSecurity)

// autoProblems are the error mappers that the app's packages declare.
func autoProblems() []httpkernel.ErrorMapper {
	return []httpkernel.ErrorMapper{articles.Problems, conduit.AuthProblems, users.Problems}
}

// autoCommands are the services that are console commands, and the commands of the migrator.
func autoCommands(m db.Migrator) []console.Command {
	return db.Commands(m)
}

// autoChecks ping the services that can be pinged, such as the database, before serving.
func autoChecks(p1 *sql.DB) []goncini.Check {
	return []goncini.Check{p1.PingContext}
}

// autoServices describes the app's services, for debug:container.
func autoServices() []goncini.Service {
	return []goncini.Service{
		{Type: "goncini.HTTP", Provider: "autoConfigHTTP", Needs: []string{"config.Config"}},
		{Type: "db.Config", Provider: "autoConfigDB", Needs: []string{"config.Config"}},
		{Type: "*sql.DB", Provider: "db.Open", Needs: []string{"db.Config"}},
		{Type: "*db.SQL", Provider: "db.NewSQL", Needs: []string{"*sql.DB"}},
		{Type: "*users.Store", Provider: "users.NewStore", Needs: []string{"*db.SQL"}},
		{Type: "security.Hasher", Provider: "hasher", Needs: []string{}},
		{Type: "security.Config", Provider: "autoConfigSecurity", Needs: []string{"config.Config"}},
		{Type: "*security.Tokens", Provider: "security.NewTokens", Needs: []string{"security.Config"}},
		{Type: "*users.Users", Provider: "users.NewUsers", Needs: []string{"*users.Store", "security.Hasher", "*security.Tokens"}},
		{Type: "func() time.Time", Provider: "clock", Needs: []string{}},
		{Type: "*articles.Store", Provider: "articles.NewStore", Needs: []string{"*db.SQL", "func() time.Time"}},
		{Type: "*articles.Articles", Provider: "articles.NewArticles", Needs: []string{"*articles.Store"}},
		{Type: "[]routing.Routes", Provider: "routes", Needs: []string{"*users.Users", "*articles.Articles"}},
		{Type: "*routing.Router", Provider: "goncini.NewRouter", Needs: []string{"[]routing.Routes"}},
		{Type: "*security.Firewall[*users.User]", Provider: "firewall", Needs: []string{"security.Config", "*security.Tokens", "*users.Store"}},
		{Type: "[]httpkernel.Middleware", Provider: "middleware", Needs: []string{"*security.Firewall[*users.User]"}},
		{Type: "[]httpkernel.ErrorMapper", Provider: "autoProblems", Needs: []string{}},
		{Type: "httpkernel.Renderer", Provider: "conduit.NewRenderer", Needs: []string{}},
		{Type: "httpkernel.Validator", Provider: "conduit.NewValidator", Needs: []string{}},
		{Type: "goncini.Log", Provider: "autoConfigLog", Needs: []string{"config.Config"}},
		{Type: "*slog.Logger", Provider: "goncini.NewLogger", Needs: []string{"goncini.Log"}},
		{Type: "*httpkernel.Kernel", Provider: "goncini.NewKernel", Needs: []string{"goncini.HTTP", "*routing.Router", "[]httpkernel.Middleware", "[]httpkernel.ErrorMapper", "httpkernel.Renderer", "httpkernel.Validator", "*slog.Logger"}},
		{Type: "*httpkernel.Server", Provider: "goncini.NewServer", Needs: []string{"goncini.HTTP", "*httpkernel.Kernel", "*slog.Logger"}},
		{Type: "db.Migrator", Provider: "migrator", Needs: []string{"*sql.DB"}},
		{Type: "[]console.Command", Provider: "autoCommands", Needs: []string{"db.Migrator"}},
		{Type: "[]goncini.Check", Provider: "autoChecks", Needs: []string{"*sql.DB"}},
		{Type: "[]goncini.Service", Provider: "autoServices", Needs: []string{}},
		{Type: "*goncini.App", Provider: "goncini.NewApp", Needs: []string{"*httpkernel.Kernel", "*httpkernel.Server", "*routing.Router", "[]console.Command", "[]goncini.Check", "[]goncini.Service", "*slog.Logger"}},
	}
}

// autoConfigHTTP is the HTTP section of the config.
func autoConfigHTTP(c config.Config) goncini.HTTP { return c.HTTP }

// autoConfigLog is the Log section of the config.
func autoConfigLog(c config.Config) goncini.Log { return c.Log }

// autoConfigDB is the DB section of the config.
func autoConfigDB(c config.Config) db.Config { return c.DB }

// autoConfigSecurity is the Security section of the config.
func autoConfigSecurity(c config.Config) security.Config { return c.Security }
