// Code generated by goncini generate. DO NOT EDIT.

package app

import (
	"database/sql"
	"reflect"

	"github.com/effect-go/effect-go/layer"
	"github.com/goncini/goncini"
	"github.com/goncini/goncini/console"
	"github.com/goncini/goncini/db"
	"github.com/goncini/goncini/examples/realworld/articles"
	"github.com/goncini/goncini/examples/realworld/conduit"
	"github.com/goncini/goncini/examples/realworld/config"
	"github.com/goncini/goncini/examples/realworld/users"
	"github.com/goncini/goncini/httpkernel"
	"github.com/goncini/goncini/openapi"
	"github.com/goncini/goncini/security"
)

// Autoconfigured hands goncini the app's services of each kind it uses,
// found by their types, and each part of goncini its config section.
var Autoconfigured = layer.Set(autoProblems, autoCommands, autoChecks, autoServices, autoOpenAPI, autoConfigHTTP, autoConfigLog, autoConfigDB, autoConfigSecurity, autoConfigOpenAPI)

// autoProblems are the error mappers that the app's packages declare.
func autoProblems() []httpkernel.ErrorMapper {
	return []httpkernel.ErrorMapper{articles.Problems, conduit.AuthProblems, users.Problems}
}

// autoCommands are the services that are console commands, and the commands of the migrator.
func autoCommands(m db.Migrator) []console.Command {
	return db.Commands(m)
}

// autoChecks ping the services that can be pinged, such as the database, before serving.
func autoChecks(p1 *sql.DB) []goncini.Check {
	return []goncini.Check{p1.PingContext}
}

// autoServices describes the app's services, for debug:container.
func autoServices() []goncini.Service {
	return []goncini.Service{
		{Type: "goncini.HTTP", Provider: "autoConfigHTTP", Needs: []string{"config.Config"}},
		{Type: "db.Config", Provider: "autoConfigDB", Needs: []string{"config.Config"}},
		{Type: "*sql.DB", Provider: "db.Open", Needs: []string{"db.Config"}},
		{Type: "*db.SQL", Provider: "db.NewSQL", Needs: []string{"*sql.DB"}},
		{Type: "*users.Store", Provider: "users.NewStore", Needs: []string{"*db.SQL"}},
		{Type: "security.Hasher", Provider: "hasher", Needs: []string{}},
		{Type: "security.Config", Provider: "autoConfigSecurity", Needs: []string{"config.Config"}},
		{Type: "*security.Tokens", Provider: "security.NewTokens", Needs: []string{"security.Config"}},
		{Type: "func() time.Time", Provider: "clock", Needs: []string{}},
		{Type: "*ratelimit.Limiter", Provider: "logins", Needs: []string{"func() time.Time"}},
		{Type: "*users.Users", Provider: "users.NewUsers", Needs: []string{"*users.Store", "security.Hasher", "*security.Tokens", "*ratelimit.Limiter"}},
		{Type: "*articles.Store", Provider: "articles.NewStore", Needs: []string{"*db.SQL", "func() time.Time"}},
		{Type: "*articles.Articles", Provider: "articles.NewArticles", Needs: []string{"*articles.Store"}},
		{Type: "[]routing.Routes", Provider: "routes", Needs: []string{"*users.Users", "*articles.Articles"}},
		{Type: "*routing.Router", Provider: "goncini.NewRouter", Needs: []string{"[]routing.Routes"}},
		{Type: "*security.Firewall[*users.User]", Provider: "firewall", Needs: []string{"security.Config", "*security.Tokens", "*users.Store"}},
		{Type: "[]httpkernel.Middleware", Provider: "middleware", Needs: []string{"*security.Firewall[*users.User]"}},
		{Type: "[]httpkernel.ErrorMapper", Provider: "autoProblems", Needs: []string{}},
		{Type: "httpkernel.Renderer", Provider: "conduit.NewRenderer", Needs: []string{}},
		{Type: "httpkernel.Validator", Provider: "conduit.NewValidator", Needs: []string{}},
		{Type: "goncini.Log", Provider: "autoConfigLog", Needs: []string{"config.Config"}},
		{Type: "slog.Handler", Provider: "goncini.NewLogHandler", Needs: []string{"goncini.Log"}},
		{Type: "*slog.Logger", Provider: "goncini.NewLogger", Needs: []string{"slog.Handler"}},
		{Type: "*httpkernel.Kernel", Provider: "goncini.NewKernel", Needs: []string{"goncini.HTTP", "*routing.Router", "[]httpkernel.Middleware", "[]httpkernel.ErrorMapper", "httpkernel.Renderer", "httpkernel.Validator", "*slog.Logger"}},
		{Type: "*httpkernel.Server", Provider: "goncini.NewServer", Needs: []string{"goncini.HTTP", "*httpkernel.Kernel", "*slog.Logger"}},
		{Type: "db.Migrator", Provider: "migrator", Needs: []string{"*sql.DB"}},
		{Type: "[]console.Command", Provider: "autoCommands", Needs: []string{"db.Migrator"}},
		{Type: "[]goncini.Check", Provider: "autoChecks", Needs: []string{"*sql.DB"}},
		{Type: "[]goncini.Service", Provider: "autoServices", Needs: []string{}},
		{Type: "openapi.Config", Provider: "autoConfigOpenAPI", Needs: []string{"config.Config"}},
		{Type: "openapi.Annotations", Provider: "autoOpenAPI", Needs: []string{}},
		{Type: "*openapi.Document", Provider: "goncini.NewOpenAPI", Needs: []string{"openapi.Config", "*routing.Router", "*httpkernel.Kernel", "openapi.Annotations"}},
		{Type: "*goncini.App", Provider: "goncini.NewApp", Needs: []string{"*httpkernel.Kernel", "*httpkernel.Server", "*routing.Router", "[]console.Command", "[]goncini.Check", "[]goncini.Service", "*slog.Logger", "*openapi.Document"}},
	}
}

// autoOpenAPI is what the app's code says of its API: the doc comments of its
// endpoints and types, and the errors each endpoint can fail with.
func autoOpenAPI() openapi.Annotations {
	return openapi.Annotations{
		Operations: map[string]openapi.OperationDoc{
			"github.com/goncini/goncini/examples/realworld/articles.(*Articles).AddComment":    {Summary: "Comments on an article.", Errors: []error{articles.NoArticle{}, articles.Unavailable{}}},
			"github.com/goncini/goncini/examples/realworld/articles.(*Articles).Comments":      {Summary: "Returns the comments of an article, oldest first.", Errors: []error{articles.NoArticle{}, articles.Unavailable{}}},
			"github.com/goncini/goncini/examples/realworld/articles.(*Articles).Create":        {Summary: "Publishes an article, with a slug made of its title.", Errors: []error{articles.NoArticle{}, articles.Unavailable{}}},
			"github.com/goncini/goncini/examples/realworld/articles.(*Articles).Delete":        {Summary: "Deletes an article that the authenticated user wrote.", Errors: []error{articles.NoArticle{}, articles.NotAuthor{}, articles.Unavailable{}}},
			"github.com/goncini/goncini/examples/realworld/articles.(*Articles).DeleteComment": {Summary: "Deletes a comment that the authenticated user wrote.", Errors: []error{articles.NoArticle{}, articles.NoComment{}, articles.NotCommentAuthor{}, articles.Unavailable{}}},
			"github.com/goncini/goncini/examples/realworld/articles.(*Articles).Favorite":      {Summary: "Adds an article to the authenticated user's favorites.", Errors: []error{articles.NoArticle{}, articles.Unavailable{}}},
			"github.com/goncini/goncini/examples/realworld/articles.(*Articles).Feed":          {Summary: "Returns the articles of the authors that the authenticated user follows, newest first, without their bodies.", Errors: []error{articles.Unavailable{}}},
			"github.com/goncini/goncini/examples/realworld/articles.(*Articles).List":          {Summary: "Returns the articles that the filters select, newest first, without their bodies.", Errors: []error{articles.Unavailable{}}},
			"github.com/goncini/goncini/examples/realworld/articles.(*Articles).Show":          {Summary: "Returns an article.", Errors: []error{articles.NoArticle{}, articles.Unavailable{}}},
			"github.com/goncini/goncini/examples/realworld/articles.(*Articles).Tags":          {Summary: "Returns every tag that an article has.", Errors: []error{articles.Unavailable{}}},
			"github.com/goncini/goncini/examples/realworld/articles.(*Articles).Unfavorite":    {Summary: "Removes an article from the authenticated user's favorites.", Errors: []error{articles.NoArticle{}, articles.Unavailable{}}},
			"github.com/goncini/goncini/examples/realworld/articles.(*Articles).Update":        {Summary: "Changes the values that the body has of an article that the authenticated user wrote.", Description: "Its slug stays the same.", Errors: []error{articles.NoArticle{}, articles.NotAuthor{}, articles.Unavailable{}}},
			"github.com/goncini/goncini/examples/realworld/users.(*Users).Current":             {Summary: "Returns the authenticated user, with a new token.", Errors: []error{users.Unavailable{}, security.Unauthenticated{}}},
			"github.com/goncini/goncini/examples/realworld/users.(*Users).Follow":              {Summary: "Makes the authenticated user follow another.", Errors: []error{users.NoProfile{}, users.Unavailable{}}},
			"github.com/goncini/goncini/examples/realworld/users.(*Users).Login":               {Summary: "Returns the user with an email and a password, with a new token.", Description: "Each email has a few attempts a minute from each address, which a\nsuccessful one gives back.", Errors: []error{users.BadCredentials{}, users.TooManyLogins{}, users.Unavailable{}}},
			"github.com/goncini/goncini/examples/realworld/users.(*Users).Profile":             {Summary: "Returns a user's profile.", Errors: []error{users.NoProfile{}, users.Unavailable{}}},
			"github.com/goncini/goncini/examples/realworld/users.(*Users).Register":            {Summary: "Registers a user, and returns them with a token.", Errors: []error{users.Taken{}, users.Unavailable{}}},
			"github.com/goncini/goncini/examples/realworld/users.(*Users).Unfollow":            {Summary: "Makes the authenticated user stop following another.", Errors: []error{users.NoProfile{}, users.Unavailable{}}},
			"github.com/goncini/goncini/examples/realworld/users.(*Users).Update":              {Summary: "Changes the authenticated user's values that the body has.", Errors: []error{users.Taken{}, users.Unavailable{}, security.Unauthenticated{}}},
		},
		Types: map[reflect.Type]openapi.TypeDoc{
			reflect.TypeFor[articles.Article]():      {Description: "Article is an article, as a viewer sees it."},
			reflect.TypeFor[articles.ArticleBody]():  {Description: "ArticleBody is an article, as the API sends it."},
			reflect.TypeFor[articles.ArticlesBody](): {Description: "ArticlesBody is a page of articles, with how many there are in all."},
			reflect.TypeFor[articles.Comment]():      {Description: "Comment is a comment on an article, as a viewer sees it."},
			reflect.TypeFor[articles.CommentBody]():  {Description: "CommentBody is a comment, as the API sends it."},
			reflect.TypeFor[articles.CommentsBody](): {Description: "CommentsBody is the comments of an article."},
			reflect.TypeFor[articles.ListInput]():    {Fields: map[string]string{"Tag": "only the articles with this tag", "Author": "only the articles of this author, a username", "Favorited": "only the favorites of this user, a username"}},
			reflect.TypeFor[articles.Page]():         {Description: "Page is where a page of articles starts, and its size.", Fields: map[string]string{"Limit": "how many articles, at most", "Offset": "how many articles to skip"}},
			reflect.TypeFor[articles.Summary]():      {Description: "Summary is an article without its body, as lists show it."},
			reflect.TypeFor[articles.TagsBody]():     {Description: "TagsBody is every tag."},
			reflect.TypeFor[users.Profile]():         {Description: "Profile is a user as others see them."},
			reflect.TypeFor[users.ProfileBody]():     {Description: "ProfileBody is a profile, as the API sends it."},
			reflect.TypeFor[users.UserBody]():        {Description: "UserBody is the user that a user sees, with a token."},
		},
	}
}

// autoConfigHTTP is the HTTP section of the config.
func autoConfigHTTP(c config.Config) goncini.HTTP { return c.HTTP }

// autoConfigLog is the Log section of the config.
func autoConfigLog(c config.Config) goncini.Log { return c.Log }

// autoConfigDB is the DB section of the config.
func autoConfigDB(c config.Config) db.Config { return c.DB }

// autoConfigSecurity is the Security section of the config.
func autoConfigSecurity(c config.Config) security.Config { return c.Security }

// autoConfigOpenAPI is the OpenAPI section of the config.
func autoConfigOpenAPI(c config.Config) openapi.Config { return c.OpenAPI }
