// Code generated by ego generate. DO NOT EDIT.

//go:build !egolayers

package app

import (
	"context"
	"fmt"

	"github.com/effect-go/effect-go/scope"
	"github.com/goncini/goncini"
	"github.com/goncini/goncini/db"
	"github.com/goncini/goncini/examples/realworld/articles"
	"github.com/goncini/goncini/examples/realworld/conduit"
	"github.com/goncini/goncini/examples/realworld/config"
	"github.com/goncini/goncini/examples/realworld/moderation"
	"github.com/goncini/goncini/examples/realworld/users"
	"github.com/goncini/goncini/security"
)

// Build builds the API for cfg. RealWorld has an error format and
// validation messages of its own.
func Build(ctx context.Context, s *scope.Scope, cfg config.Config) (*goncini.App, error) {
	http := autoConfigHTTP(cfg)
	config2 := autoConfigSecurity(cfg)
	tokens, err := security.NewTokens(config2)
	if err != nil {
		return nil, fmt.Errorf("security.NewTokens: %w", err)
	}
	config3 := autoConfigDB(cfg)
	db2, cleanup, err := db.Open(config3)
	if err != nil {
		return nil, fmt.Errorf("db.Open: %w", err)
	}
	s.Defer(func(context.Context) error { return cleanup() })
	sql2 := db.NewSQL(db2)
	store := users.NewStore(sql2)
	firewall2 := firewall(config2, tokens, store)
	config4 := autoConfigModeration(cfg)
	firewall3, err := moderation.NewFirewall(config4)
	if err != nil {
		return nil, fmt.Errorf("moderation.NewFirewall: %w", err)
	}
	hasher2 := hasher()
	v := clock()
	limiter := logins(v)
	users2, err := users.NewUsers(store, hasher2, tokens, limiter)
	if err != nil {
		return nil, fmt.Errorf("users.NewUsers: %w", err)
	}
	store2 := articles.NewStore(sql2, v)
	authorship := articles.NewAuthorship()
	v2 := autoVoters(authorship)
	access := security.NewAccess(config2, v2)
	articles2 := articles.NewArticles(store2, access)
	moderation2 := moderation.NewModeration(articles2, access)
	v3 := routes(firewall2, firewall3, users2, articles2, moderation2)
	router := goncini.NewRouter(v3)
	v4 := goncini.NewMiddleware()
	v5 := autoProblems()
	renderer := conduit.NewRenderer()
	validator := conduit.NewValidator()
	log := autoConfigLog(cfg)
	handler := goncini.NewLogHandler(log)
	logger := goncini.NewLogger(handler)
	kernel, err := goncini.NewKernel(http, router, v4, v5, renderer, validator, logger)
	if err != nil {
		return nil, fmt.Errorf("NewKernel: %w", err)
	}
	server := goncini.NewServer(http, kernel, logger)
	migrator2, err := migrator(db2)
	if err != nil {
		return nil, fmt.Errorf("migrator: %w", err)
	}
	v6 := autoCommands(migrator2)
	v7 := autoChecks(db2)
	v8 := autoServices()
	config5 := autoConfigOpenAPI(cfg)
	annotations := autoOpenAPI()
	document, err := goncini.NewOpenAPI(config5, router, kernel, annotations)
	if err != nil {
		return nil, fmt.Errorf("NewOpenAPI: %w", err)
	}
	app := goncini.NewApp(kernel, server, router, v6, v7, v8, logger, document)
	return app, nil
}
