// Code generated by ego generate. DO NOT EDIT.

//go:build !egolayers

package app

import (
	"context"
	"fmt"

	"github.com/effect-go/effect-go/scope"
	"github.com/goncini/goncini"
	"github.com/goncini/goncini/cache"
	"github.com/goncini/goncini/db"
	"github.com/goncini/goncini/examples/realworld/articles"
	"github.com/goncini/goncini/examples/realworld/conduit"
	"github.com/goncini/goncini/examples/realworld/config"
	"github.com/goncini/goncini/examples/realworld/moderation"
	"github.com/goncini/goncini/examples/realworld/notifications"
	"github.com/goncini/goncini/examples/realworld/users"
	"github.com/goncini/goncini/lock"
	"github.com/goncini/goncini/mailer"
	"github.com/goncini/goncini/messenger"
	"github.com/goncini/goncini/scheduler"
	"github.com/goncini/goncini/security"
)

// Build builds the API for cfg. RealWorld has an error format and
// validation messages of its own.
func Build(ctx context.Context, s *scope.Scope, cfg config.Config) (*goncini.App, error) {
	http := autoConfigHTTP(cfg)
	config2 := autoConfigSecurity(cfg)
	tokens, err := security.NewTokens(config2)
	if err != nil {
		return nil, fmt.Errorf("security.NewTokens: %w", err)
	}
	config3 := autoConfigDB(cfg)
	db2, cleanup, err := db.Open(config3)
	if err != nil {
		return nil, fmt.Errorf("db.Open: %w", err)
	}
	s.Defer(func(context.Context) error { return cleanup() })
	sql2 := db.NewSQL(db2)
	store := users.NewStore(sql2)
	firewall2 := firewall(config2, tokens, store)
	config4 := autoConfigModeration(cfg)
	firewall3, err := moderation.NewFirewall(config4)
	if err != nil {
		return nil, fmt.Errorf("moderation.NewFirewall: %w", err)
	}
	hasher2 := hasher()
	v := clock()
	limiter := logins(v)
	config5 := autoDefaultCacheConfig()
	memoryStore := cache.NewMemoryStore()
	cache2 := cache.New(config5, memoryStore)
	invalidator := articles.NewInvalidator(cache2)
	config6 := autoConfigMessenger(cfg)
	transports, err := messenger.NewSQLTransports(db2, config6)
	if err != nil {
		return nil, fmt.Errorf("NewSQLTransports: %w", err)
	}
	config7 := autoConfigMailer(cfg)
	log := autoConfigLog(cfg)
	handler := goncini.NewLogHandler(log)
	logger := goncini.NewLogger(handler)
	transport, err := mailer.NewTransport(config7, logger)
	if err != nil {
		return nil, fmt.Errorf("NewTransport: %w", err)
	}
	handler2 := mailer.NewHandler(config7, transport)
	notifications2 := notifications.NewNotifications(sql2, v)
	v2 := autoHandlers(handler2, notifications2)
	bus := messenger.NewBus(config6, transports, v2, logger)
	subscriber := notifications.NewSubscriber(bus)
	v3 := autoSubscribers(invalidator, subscriber)
	dispatcher := goncini.NewDispatcher(v3)
	mailer2 := mailer.NewAsync(config7, bus)
	users2, err := users.NewUsers(store, hasher2, tokens, limiter, dispatcher, mailer2)
	if err != nil {
		return nil, fmt.Errorf("users.NewUsers: %w", err)
	}
	store2 := articles.NewStore(sql2, v)
	authorship := articles.NewAuthorship()
	v4 := autoVoters(authorship)
	access := security.NewAccess(config2, v4)
	articles2 := articles.NewArticles(store2, access, dispatcher, cache2)
	moderation2 := moderation.NewModeration(articles2, access)
	v5 := routes(firewall2, firewall3, users2, articles2, notifications2, moderation2)
	router := goncini.NewRouter(v5)
	v6 := goncini.NewMiddleware()
	v7 := autoProblems()
	renderer := conduit.NewRenderer()
	validator := conduit.NewValidator()
	kernel, err := goncini.NewKernel(http, router, v6, v7, renderer, validator, dispatcher, logger)
	if err != nil {
		return nil, fmt.Errorf("NewKernel: %w", err)
	}
	server := goncini.NewServer(http, kernel, logger)
	migrator2, err := migrator(db2)
	if err != nil {
		return nil, fmt.Errorf("migrator: %w", err)
	}
	config8 := autoDefaultSchedulerConfig()
	sqlStore, err := lock.NewSQLStore(db2)
	if err != nil {
		return nil, fmt.Errorf("NewSQLStore: %w", err)
	}
	v8 := autoTasks(notifications2)
	scheduler2 := scheduler.New(config8, sqlStore, v8, logger)
	v9 := autoCommands(migrator2, bus, scheduler2)
	v10 := autoChecks(db2)
	v11 := autoServices()
	config9 := autoConfigOpenAPI(cfg)
	annotations := autoOpenAPI()
	document, err := goncini.NewOpenAPI(config9, router, kernel, annotations)
	if err != nil {
		return nil, fmt.Errorf("NewOpenAPI: %w", err)
	}
	v12 := autoBackground(bus, scheduler2)
	app := goncini.NewApp(kernel, server, router, v9, v10, v11, logger, document, dispatcher, v12)
	return app, nil
}

// BuildTest builds the API for a test, with its database, which a test
// reaches into to change what the API doesn't see.
func BuildTest(ctx context.Context, s *scope.Scope, cfg config.Config) (*Test, error) {
	http := autoConfigHTTP(cfg)
	config2 := autoConfigSecurity(cfg)
	tokens, err := security.NewTokens(config2)
	if err != nil {
		return nil, fmt.Errorf("security.NewTokens: %w", err)
	}
	config3 := autoConfigDB(cfg)
	db2, cleanup, err := db.Open(config3)
	if err != nil {
		return nil, fmt.Errorf("db.Open: %w", err)
	}
	s.Defer(func(context.Context) error { return cleanup() })
	sql2 := db.NewSQL(db2)
	store := users.NewStore(sql2)
	firewall2 := firewall(config2, tokens, store)
	config4 := autoConfigModeration(cfg)
	firewall3, err := moderation.NewFirewall(config4)
	if err != nil {
		return nil, fmt.Errorf("moderation.NewFirewall: %w", err)
	}
	hasher2 := hasher()
	v := clock()
	limiter := logins(v)
	config5 := autoDefaultCacheConfig()
	memoryStore := cache.NewMemoryStore()
	cache2 := cache.New(config5, memoryStore)
	invalidator := articles.NewInvalidator(cache2)
	config6 := autoConfigMessenger(cfg)
	transports, err := messenger.NewSQLTransports(db2, config6)
	if err != nil {
		return nil, fmt.Errorf("NewSQLTransports: %w", err)
	}
	config7 := autoConfigMailer(cfg)
	log := autoConfigLog(cfg)
	handler := goncini.NewLogHandler(log)
	logger := goncini.NewLogger(handler)
	transport, err := mailer.NewTransport(config7, logger)
	if err != nil {
		return nil, fmt.Errorf("NewTransport: %w", err)
	}
	handler2 := mailer.NewHandler(config7, transport)
	notifications2 := notifications.NewNotifications(sql2, v)
	v2 := autoHandlers(handler2, notifications2)
	bus := messenger.NewBus(config6, transports, v2, logger)
	subscriber := notifications.NewSubscriber(bus)
	v3 := autoSubscribers(invalidator, subscriber)
	dispatcher := goncini.NewDispatcher(v3)
	mailer2 := mailer.NewAsync(config7, bus)
	users2, err := users.NewUsers(store, hasher2, tokens, limiter, dispatcher, mailer2)
	if err != nil {
		return nil, fmt.Errorf("users.NewUsers: %w", err)
	}
	store2 := articles.NewStore(sql2, v)
	authorship := articles.NewAuthorship()
	v4 := autoVoters(authorship)
	access := security.NewAccess(config2, v4)
	articles2 := articles.NewArticles(store2, access, dispatcher, cache2)
	moderation2 := moderation.NewModeration(articles2, access)
	v5 := routes(firewall2, firewall3, users2, articles2, notifications2, moderation2)
	router := goncini.NewRouter(v5)
	v6 := goncini.NewMiddleware()
	v7 := autoProblems()
	renderer := conduit.NewRenderer()
	validator := conduit.NewValidator()
	kernel, err := goncini.NewKernel(http, router, v6, v7, renderer, validator, dispatcher, logger)
	if err != nil {
		return nil, fmt.Errorf("NewKernel: %w", err)
	}
	server := goncini.NewServer(http, kernel, logger)
	migrator2, err := migrator(db2)
	if err != nil {
		return nil, fmt.Errorf("migrator: %w", err)
	}
	config8 := autoDefaultSchedulerConfig()
	sqlStore, err := lock.NewSQLStore(db2)
	if err != nil {
		return nil, fmt.Errorf("NewSQLStore: %w", err)
	}
	v8 := autoTasks(notifications2)
	scheduler2 := scheduler.New(config8, sqlStore, v8, logger)
	v9 := autoCommands(migrator2, bus, scheduler2)
	v10 := autoChecks(db2)
	v11 := autoServices()
	config9 := autoConfigOpenAPI(cfg)
	annotations := autoOpenAPI()
	document, err := goncini.NewOpenAPI(config9, router, kernel, annotations)
	if err != nil {
		return nil, fmt.Errorf("NewOpenAPI: %w", err)
	}
	v12 := autoBackground(bus, scheduler2)
	app := goncini.NewApp(kernel, server, router, v9, v10, v11, logger, document, dispatcher, v12)
	test := newTest(app, db2)
	return test, nil
}
