// Code generated by ego generate from services.ego. DO NOT EDIT.

// Package app wires the RealWorld API: goncini's services, the app's own,
// and the config sections they take.
package app

import (
	"database/sql"
	"time"

	"github.com/pressly/goose/v3"
	_ "modernc.org/sqlite" // the "sqlite" database/sql driver

	"github.com/goncini/goncini/db"
	"github.com/goncini/goncini/db/goosedb"
	"github.com/goncini/goncini/httpkernel"
	"github.com/goncini/goncini/ratelimit"
	"github.com/goncini/goncini/routing"
	"github.com/goncini/goncini/security"

	"github.com/goncini/goncini/examples/realworld/articles"
	"github.com/goncini/goncini/examples/realworld/migrations"
	"github.com/goncini/goncini/examples/realworld/users"

	"github.com/effect-go/effect-go/layer"
)

// Services is the app's own services.
//
//line services.ego:25
var Services = layer.Set(
	db.Open, db.NewSQL, migrator,
	security.NewTokens, hasher, firewall,
	users.NewStore, users.NewUsers, logins,
	articles.NewStore, articles.NewArticles,
	routes, clock,
)

// routes puts the API under /api. goncini generate collects the routes of
// an app that doesn't provide them itself.
func routes(u *users.Users, a *articles.Articles) []routing.Routes {
	return []routing.Routes{routing.Prefix("/api", u, a)}
}

// migrator runs the migrations with goose.
func migrator(pool *sql.DB) (db.Migrator, error) {
	return goosedb.New(pool, goose.DialectSQLite3, migrations.FS)
}

// hasher hashes passwords with OWASP's parameters.
func hasher() security.Hasher { return security.Hasher{} }

// firewall authenticates requests by their token, which names a user ID.
func firewall(c security.Config, tokens *security.Tokens, store *users.Store) *security.Firewall[*users.User] {
	return &security.Firewall[*users.User]{Config: c, Tokens: tokens, Load: store.ByID}
}

// middleware puts the firewall in the kernel.
func middleware(f *security.Firewall[*users.User]) []httpkernel.Middleware {
	return []httpkernel.Middleware{f.Middleware}
}

// logins limits the logins of each email from each address: 5 a minute.
func logins(now func() time.Time) *ratelimit.Limiter {
	return &ratelimit.Limiter{Policy: ratelimit.SlidingWindow{Limit: 5, Interval: time.Minute}, Now: now}
}

// clock is the app's clock: the system's.
func clock() func() time.Time { return time.Now }
