// Code generated by ego generate from testing.ego. DO NOT EDIT.

package app

import (
	"database/sql"

	"github.com/goncini/goncini"
)

// Test is the API, with what tests reach into.
//
//line testing.ego:10
type Test struct {
	*goncini.App
	DB *sql.DB
}

func newTest(app *goncini.App, db *sql.DB) *Test {
	return &Test{App: app, DB: db}
}
