// Code generated by ego generate from controller.ego. DO NOT EDIT.

package articles

import (
	"context"
	"github.com/goncini/goncini/httpkernel"
	"github.com/goncini/goncini/routing"
	"github.com/goncini/goncini/security"

	"github.com/goncini/goncini/examples/realworld/users"

	"github.com/effect-go/effect-go/trace"
)

// Articles serves the articles, their favorites, comments and tags.
//
//line controller.ego:12
type Articles struct {
	store *Store
}

func NewArticles(store *Store) *Articles {
	return &Articles{store: store}
}

// Routes registers the endpoints.
func (a *Articles) Routes(r *routing.Router) {
	r.Get("/articles", httpkernel.Endpoint(a.List)).Name("article_list")
	r.Get("/articles/{slug}", httpkernel.Endpoint(a.Show)).Name("article_show")
	r.Get("/articles/{slug}/comments", httpkernel.Endpoint(a.Comments)).Name("comment_list")
	r.Get("/tags", httpkernel.Endpoint(a.Tags)).Name("tag_list")
	auth := r.With(security.Required)
	auth.Get("/articles/feed", httpkernel.Endpoint(a.Feed)).Name("article_feed")
	auth.Post("/articles", httpkernel.Endpoint(a.Create)).Name("article_create")
	auth.Put("/articles/{slug}", httpkernel.Endpoint(a.Update)).Name("article_update")
	auth.Delete("/articles/{slug}", httpkernel.Endpoint(a.Delete)).Name("article_delete")
	auth.Post("/articles/{slug}/favorite", httpkernel.Endpoint(a.Favorite)).Name("article_favorite")
	auth.Delete("/articles/{slug}/favorite", httpkernel.Endpoint(a.Unfavorite)).Name("article_unfavorite")
	auth.Post("/articles/{slug}/comments", httpkernel.Endpoint(a.AddComment)).Name("comment_add")
	auth.Delete("/articles/{slug}/comments/{id<\\d+>}", httpkernel.Endpoint(a.DeleteComment)).Name("comment_delete")
}

// ArticleBody is an article, as the API sends it.
type ArticleBody struct {
	Article Article `json:"article"`
}

// ArticlesBody is a page of articles, with how many there are in all.
type ArticlesBody struct {
	Articles      []Article `json:"articles"`
	ArticlesCount int       `json:"articlesCount"`
}

// Page is where a page of articles starts, and its size.
type Page struct {
	Limit  int `query:"limit" default:"20" validate:"min=1,max=100"`
	Offset int `query:"offset" validate:"min=0"`
}

type ListInput struct {
	Page
	Tag       string `query:"tag"`
	Author    string `query:"author"`
	Favorited string `query:"favorited"`
}

func (a *Articles) List(ctx context.Context, in ListInput) (_ ArticlesBody, err error) {
	ctx, span := trace.Start(ctx, "articles.Articles.List")
	defer trace.End(span, &err)
//line controller.ego:62
	f := Filter{Tag: in.Tag, Author: in.Author, Favorited: in.Favorited}
	list, count, err := a.store.List(ctx, users.Viewer(ctx), f, in.Limit, in.Offset)
	if err != nil {
		return ArticlesBody{}, Unavailable{Cause: err}
	}
//line controller.ego:64
	return ArticlesBody{list, count}, nil
}

func (a *Articles) Feed(ctx context.Context, in Page) (_ ArticlesBody, err error) {
	ctx, span := trace.Start(ctx, "articles.Articles.Feed")
	defer trace.End(span, &err)
//line controller.ego:68
	viewer := users.Viewer(ctx)
	list, count, err := a.store.List(ctx, viewer, Filter{FeedOf: viewer}, in.Limit, in.Offset)
	if err != nil {
		return ArticlesBody{}, Unavailable{Cause: err}
	}
//line controller.ego:70
	return ArticlesBody{list, count}, nil
}

type SlugInput struct {
	Slug string `path:"slug"`
}

func (a *Articles) Show(ctx context.Context, in SlugInput) (_ ArticleBody, err error) {
	ctx, span := trace.Start(ctx, "articles.Articles.Show")
	defer trace.End(span, &err)
//line controller.ego:78
	art, err := a.find(ctx, in.Slug)
	if err != nil {
		return ArticleBody{}, err
	}
//line controller.ego:79
	return ArticleBody{art}, nil
}

// find returns the article with the slug, as the viewer sees it.
func (a *Articles) find(ctx context.Context, slug string) (_ Article, err error) {
	ctx, span := trace.Start(ctx, "articles.Articles.find")
	defer trace.End(span, &err)
//line controller.ego:84
	art, ok, err := a.store.BySlug(ctx, users.Viewer(ctx), slug)
	if err != nil {
		return Article{}, Unavailable{Cause: err}
	}
//line controller.ego:85
	if !ok {
		return Article{}, NoArticle{Slug: slug}
	}
	return art, nil
}

// findOwn returns the article with the slug, if the viewer wrote it.
func (a *Articles) findOwn(ctx context.Context, slug string) (_ Article, err error) {
	ctx, span := trace.Start(ctx, "articles.Articles.findOwn")
	defer trace.End(span, &err)
//line controller.ego:93
	art, err := a.find(ctx, slug)
	if err != nil {
		return Article{}, err
	}
//line controller.ego:94
	if art.AuthorID != users.Viewer(ctx) {
		return Article{}, NotAuthor{Slug: slug}
	}
	return art, nil
}

type CreateInput struct {
	Body struct {
		Article struct {
			Title       string   `json:"title" validate:"required"`
			Description string   `json:"description" validate:"required"`
			Body        string   `json:"body" validate:"required"`
			TagList     []string `json:"tagList" validate:"dive,required"`
		} `json:"article"`
	}
}

func (a *Articles) Create(ctx context.Context, in CreateInput) (_ httpkernel.Created[ArticleBody], err error) {
	ctx, span := trace.Start(ctx, "articles.Articles.Create")
	defer trace.End(span, &err)
//line controller.ego:112
	b := in.Body.Article
	art := Article{Title: b.Title, Description: b.Description, Body: &b.Body, AuthorID: users.Viewer(ctx)}
	v := b.TagList
	if v == nil {
		v = []string{}
	}
	slug, err := a.store.Save(ctx, art, v)
	if err != nil {
		return httpkernel.Created[ArticleBody]{}, Unavailable{Cause: err}
	}
//line controller.ego:115
	created, err := a.find(ctx, slug)
	if err != nil {
		return httpkernel.Created[ArticleBody]{}, err
	}
//line controller.ego:116
	return httpkernel.Created[ArticleBody]{Body: ArticleBody{created}}, nil
}

type UpdateInput struct {
	SlugInput
	Body struct {
		Article struct {
			Title       httpkernel.Optional[string]   `json:"title"`
			Description httpkernel.Optional[string]   `json:"description"`
			Body        httpkernel.Optional[string]   `json:"body"`
			TagList     httpkernel.Optional[[]string] `json:"tagList"`
		} `json:"article"`
	}
}

// Validate refuses to clear what an article must have.
func (in *UpdateInput) Validate() error {
	b := in.Body.Article
	var vs []httpkernel.Violation
	for name, field := range map[string]httpkernel.Optional[string]{"title": b.Title, "description": b.Description, "body": b.Body} {
		if field.Set && (field.Null || field.Value == "") {
			vs = append(vs, httpkernel.Violation{Pointer: "#/article/" + name, Detail: "can't be blank"})
		}
	}
	if b.TagList.Null {
		vs = append(vs, httpkernel.Violation{Pointer: "#/article/tagList", Detail: "can't be null"})
	}
	if len(vs) > 0 {
		return httpkernel.Invalid(vs...)
	}
	return nil
}

func (a *Articles) Update(ctx context.Context, in UpdateInput) (_ ArticleBody, err error) {
	ctx, span := trace.Start(ctx, "articles.Articles.Update")
	defer trace.End(span, &err)
//line controller.ego:150
	art, err := a.findOwn(ctx, in.Slug)
	if err != nil {
		return ArticleBody{}, err
	}
//line controller.ego:151
	b := in.Body.Article
	if b.Title.Set {
		art.Title = b.Title.Value
	}
	if b.Description.Set {
		art.Description = b.Description.Value
	}
	if b.Body.Set {
		art.Body = &b.Body.Value
	}
	var tags []string // nil leaves the tags as they are
	if b.TagList.Set {
		tags = b.TagList.Value
		if tags == nil {
			tags = []string{}
		}
	}
//line controller.ego:165
	if _, err := a.store.Save(ctx, art, tags); err != nil {
		return ArticleBody{}, Unavailable{Cause: err}
	}
//line controller.ego:166
	updated, err := a.find(ctx, art.Slug)
	if err != nil {
		return ArticleBody{}, err
	}
//line controller.ego:167
	return ArticleBody{updated}, nil
}

func (a *Articles) Delete(ctx context.Context, in SlugInput) (_ httpkernel.NoContent, err error) {
	ctx, span := trace.Start(ctx, "articles.Articles.Delete")
	defer trace.End(span, &err)
//line controller.ego:171
	art, err := a.findOwn(ctx, in.Slug)
	if err != nil {
		return httpkernel.NoContent{}, err
	}
//line controller.ego:172
	if err := a.store.Delete(ctx, art.ID); err != nil {
		return httpkernel.NoContent{}, Unavailable{Cause: err}
	}
//line controller.ego:173
	return httpkernel.NoContent{}, nil
}

func (a *Articles) Favorite(ctx context.Context, in SlugInput) (_ ArticleBody, err error) {
	ctx, span := trace.Start(ctx, "articles.Articles.Favorite")
	defer trace.End(span, &err)
	return a.favorite(ctx, in.Slug, true)
}

//line controller.ego:180
func (a *Articles) Unfavorite(ctx context.Context, in SlugInput) (_ ArticleBody, err error) {
	ctx, span := trace.Start(ctx, "articles.Articles.Unfavorite")
	defer trace.End(span, &err)
	return a.favorite(ctx, in.Slug, false)
}

// favorite makes the viewer favorite the article with the slug, or not.
//
//line controller.ego:185
func (a *Articles) favorite(ctx context.Context, slug string, favorite bool) (_ ArticleBody, err error) {
	ctx, span := trace.Start(ctx, "articles.Articles.favorite")
	defer trace.End(span, &err)
//line controller.ego:186
	art, err := a.find(ctx, slug)
	if err != nil {
		return ArticleBody{}, err
	}
//line controller.ego:187
	if err := a.store.Favorite(ctx, users.Viewer(ctx), art.ID, favorite); err != nil {
		return ArticleBody{}, Unavailable{Cause: err}
	}
//line controller.ego:188
	updated, err := a.find(ctx, slug)
	if err != nil {
		return ArticleBody{}, err
	}
//line controller.ego:189
	return ArticleBody{updated}, nil
}

// TagsBody is every tag.
type TagsBody struct {
	Tags []string `json:"tags"`
}

func (a *Articles) Tags(ctx context.Context, in struct{}) (_ TagsBody, err error) {
	ctx, span := trace.Start(ctx, "articles.Articles.Tags")
	defer trace.End(span, &err)
//line controller.ego:198
	tags, err := a.store.Tags(ctx)
	if err != nil {
		return TagsBody{}, Unavailable{Cause: err}
	}
//line controller.ego:199
	return TagsBody{tags}, nil
}
