// Code generated by ego generate from store.ego. DO NOT EDIT.

package articles

import (
	"context"
	"encoding/json/v2"
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/goncini/goncini/db"

	"github.com/effect-go/effect-go/trace"
)

// Store keeps the articles, their tags, favorites and comments.
//
//line store.ego:14
type Store struct {
	sql *db.SQL
	now func() time.Time
}

func NewStore(s *db.SQL, now func() time.Time) *Store {
	return &Store{sql: s, now: now}
}

// Filter selects articles. Its zero value selects them all.
type Filter struct {
	Tag       string
	Author    string // a username
	Favorited string // a username
	FeedOf    int64  // a user ID: the articles of the authors they follow
}

// where returns the conditions of f, and their arguments.
func (f Filter) where() (string, []any) {
	var conds []string
	var args []any
	add := func(cond string, arg any) {
		conds = append(conds, cond)
		args = append(args, arg)
	}
	if f.Tag != "" {
		add("EXISTS (SELECT 1 FROM article_tags t WHERE t.article_id = a.id AND t.tag = ?)", f.Tag)
	}
	if f.Author != "" {
		add("u.username = ?", f.Author)
	}
	if f.Favorited != "" {
		add("EXISTS (SELECT 1 FROM favorites f JOIN users fu ON fu.id = f.user_id WHERE f.article_id = a.id AND fu.username = ?)", f.Favorited)
	}
	if f.FeedOf != 0 {
		add("a.author_id IN (SELECT followed_id FROM follows WHERE follower_id = ?)", f.FeedOf)
	}
	if len(conds) == 0 {
		return "", nil
	}
	return " WHERE " + strings.Join(conds, " AND "), args
}

// selectArticles selects an article as the viewer, a user ID or 0, sees it:
// its author's profile, whether the viewer favorited it, and its tags.
const selectArticles = `SELECT a.id, a.author_id, a.slug, a.title, a.description, a.body, a.created_at, a.updated_at,
	u.username, u.bio, u.image,
	(SELECT count(*) FROM favorites f WHERE f.article_id = a.id),
	EXISTS (SELECT 1 FROM favorites f WHERE f.article_id = a.id AND f.user_id = ?),
	EXISTS (SELECT 1 FROM follows fo WHERE fo.followed_id = a.author_id AND fo.follower_id = ?),
	(SELECT json_group_array(tag) FROM (SELECT tag FROM article_tags t WHERE t.article_id = a.id ORDER BY position))
FROM articles a JOIN users u ON u.id = a.author_id`

// List returns the articles that f selects, newest first, without their
// bodies, from offset and at most limit of them, with how many there are.
func (s *Store) List(ctx context.Context, viewer int64, f Filter, limit, offset int) (_ []Summary, _ int, err error) {
	ctx, span := trace.Start(ctx, "articles.Store.List")
	defer trace.End(span, &err)
//line store.ego:70
	where, args := f.where()
	conn := s.sql.Conn(ctx)
	count, err := db.Value[int](ctx, conn, "SELECT count(*) FROM articles a JOIN users u ON u.id = a.author_id"+where, args...)
	if err != nil {
		return nil, 0, fmt.Errorf("db.Value: %w", err)
	}
//line store.ego:73
	query := selectArticles + where + " ORDER BY a.created_at DESC, a.id DESC LIMIT ? OFFSET ?"
	list, err := db.All(ctx, conn, scanSummary, query, append(append([]any{viewer, viewer}, args...), limit, offset)...)
	if err != nil {
		return nil, 0, fmt.Errorf("db.All: %w", err)
	}
//line store.ego:75
	return list, count, nil
}

// BySlug returns the article with the slug, as the viewer sees it, and
// reports whether there is one.
func (s *Store) BySlug(ctx context.Context, viewer int64, slug string) (_ Article, _ bool, err error) {
	ctx, span := trace.Start(ctx, "articles.Store.BySlug")
	defer trace.End(span, &err)
	return db.One(ctx, s.sql.Conn(ctx), scanArticle, selectArticles+" WHERE a.slug = ?", viewer, viewer, slug)
}

// scanArticle reads an article that selectArticles selects.
//
//line store.ego:85
func scanArticle(row db.Scanner) (Article, error) {
	var art Article
	var tags string
	var created, updated int64
	if err := row.Scan(&art.ID, &art.AuthorID, &art.Slug, &art.Title, &art.Description, &art.Body, &created, &updated,
		&art.Author.Username, &art.Author.Bio, &art.Author.Image,
		&art.FavoritesCount, &art.Favorited, &art.Author.Following, &tags); err != nil {
		return Article{}, err
	}
//line store.ego:92
	if err := json.Unmarshal([]byte(tags), &art.TagList); err != nil {
		return Article{}, err
	}
//line store.ego:93
	art.CreatedAt, art.UpdatedAt = time.UnixMicro(created).UTC(), time.UnixMicro(updated).UTC()
	return art, nil
}

// scanSummary reads an article that selectArticles selects, without its
// body.
func scanSummary(row db.Scanner) (Summary, error) {
	art, err := scanArticle(row)
	return art.Summary, err
}

// Save inserts art with a slug of its title, unique, if its ID is 0, or
// else updates it, keeping its slug; then sets its tags, if tags isn't nil.
// It returns the slug.
func (s *Store) Save(ctx context.Context, art Article, tags []string) (_ string, err error) {
	ctx, span := trace.Start(ctx, "articles.Store.Save")
	defer trace.End(span, &err)
//line store.ego:108
	now := s.now().UnixMicro()
	if err := s.sql.InTx(ctx, func(ctx context.Context) error {
		conn := s.sql.Conn(ctx)
		if art.ID != 0 {
			if _, err := conn.ExecContext(ctx, "UPDATE articles SET title = ?, description = ?, body = ?, updated_at = ? WHERE id = ?",
				art.Title, art.Description, art.Body, now, art.ID); err != nil {
				return fmt.Errorf("conn.ExecContext: %w", err)
			}
		} else {
//line store.ego:115
			v, err := s.freeSlug(ctx, slugify(art.Title))
			if err != nil {
				return err
			}
			art.Slug = v
//line store.ego:116
			res, err := conn.ExecContext(ctx, "INSERT INTO articles (slug, title, description, body, author_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)",
				art.Slug, art.Title, art.Description, art.Body, art.AuthorID, now, now)
			if err != nil {
				return fmt.Errorf("conn.ExecContext: %w", err)
			}
//line store.ego:118
			v2, err := res.LastInsertId()
			if err != nil {
				return fmt.Errorf("res.LastInsertId: %w", err)
			}
			art.ID = v2
		}
//line store.ego:120
		if tags == nil {
			return nil
		}
		if _, err := conn.ExecContext(ctx, "DELETE FROM article_tags WHERE article_id = ?", art.ID); err != nil {
			return fmt.Errorf("conn.ExecContext: %w", err)
		}
//line store.ego:124
		for i, tag := range tags {
			if _, err := conn.ExecContext(ctx, "INSERT INTO article_tags (article_id, position, tag) VALUES (?, ?, ?)", art.ID, i, tag); err != nil {
				return fmt.Errorf("conn.ExecContext: %w", err)
			}
		}
//line store.ego:127
		return nil
	}); err != nil {
		return "", err
	}
//line store.ego:129
	return art.Slug, nil
}

// freeSlug returns base, or base followed by the first number that makes
// it a slug no article has: two articles can have the same title.
func (s *Store) freeSlug(ctx context.Context, base string) (string, error) {
	slug := base
	for n := 2; ; n++ {
		taken, err := db.Value[bool](ctx, s.sql.Conn(ctx), "SELECT EXISTS (SELECT 1 FROM articles WHERE slug = ?)", slug)
		if err != nil {
			return "", err
		}
//line store.ego:138
		if !taken {
			return slug, nil
		}
		slug = base + "-" + strconv.Itoa(n)
	}
}

// Delete deletes the article with the ID, with its tags, favorites and
// comments.
func (s *Store) Delete(ctx context.Context, id int64) (err error) {
	ctx, span := trace.Start(ctx, "articles.Store.Delete")
	defer trace.End(span, &err)
//line store.ego:148
	if _, err := s.sql.Conn(ctx).ExecContext(ctx, "DELETE FROM articles WHERE id = ?", id); err != nil {
		return fmt.Errorf("Conn.ExecContext: %w", err)
	}
//line store.ego:149
	return nil
}

// Favorite makes the user favorite the article, or not.
func (s *Store) Favorite(ctx context.Context, user, article int64, favorite bool) (err error) {
	ctx, span := trace.Start(ctx, "articles.Store.Favorite")
	defer trace.End(span, &err)
//line store.ego:154
	var query string
	if favorite {
		query = "INSERT OR IGNORE INTO favorites (user_id, article_id) VALUES (?, ?)"
	} else {
		query = "DELETE FROM favorites WHERE user_id = ? AND article_id = ?"
	}
//line store.ego:155
	if _, err := s.sql.Conn(ctx).ExecContext(ctx, query, user, article); err != nil {
		return fmt.Errorf("Conn.ExecContext: %w", err)
	}
//line store.ego:156
	return nil
}

// Tags returns every tag of an article, sorted.
func (s *Store) Tags(ctx context.Context) (_ []string, err error) {
	ctx, span := trace.Start(ctx, "articles.Store.Tags")
	defer trace.End(span, &err)
	return db.All(ctx, s.sql.Conn(ctx), scanTag, "SELECT DISTINCT tag FROM article_tags ORDER BY tag")
}

//line store.ego:164
func scanTag(row db.Scanner) (string, error) {
	var tag string
	err := row.Scan(&tag)
	return tag, err
}

// selectComments selects a comment as the viewer, a user ID or 0, sees it.
const selectComments = `SELECT c.id, c.author_id, c.body, c.created_at, c.updated_at, u.username, u.bio, u.image,
	EXISTS (SELECT 1 FROM follows fo WHERE fo.followed_id = c.author_id AND fo.follower_id = ?)
FROM comments c JOIN users u ON u.id = c.author_id`

// Comments returns the comments of the article, oldest first.
func (s *Store) Comments(ctx context.Context, viewer, article int64) (_ []Comment, err error) {
	ctx, span := trace.Start(ctx, "articles.Store.Comments")
	defer trace.End(span, &err)
	return db.All(ctx, s.sql.Conn(ctx), scanComment, selectComments+" WHERE c.article_id = ? ORDER BY c.id", viewer, article)
}

// Comment returns the comment of the article with the ID, and reports
// whether there is one.
//
//line store.ego:182
func (s *Store) Comment(ctx context.Context, viewer, article, id int64) (_ Comment, _ bool, err error) {
	ctx, span := trace.Start(ctx, "articles.Store.Comment")
	defer trace.End(span, &err)
	return db.One(ctx, s.sql.Conn(ctx), scanComment, selectComments+" WHERE c.article_id = ? AND c.id = ?", viewer, article, id)
}

// scanComment reads a comment that selectComments selects.
//
//line store.ego:187
func scanComment(row db.Scanner) (Comment, error) {
	var c Comment
	var created, updated int64
	if err := row.Scan(&c.ID, &c.AuthorID, &c.Body, &created, &updated, &c.Author.Username, &c.Author.Bio, &c.Author.Image, &c.Author.Following); err != nil {
		return Comment{}, err
	}
//line store.ego:191
	c.CreatedAt, c.UpdatedAt = time.UnixMicro(created).UTC(), time.UnixMicro(updated).UTC()
	return c, nil
}

// AddComment adds a comment by the author to the article, and returns its
// ID.
func (s *Store) AddComment(ctx context.Context, article, author int64, body string) (_ int64, err error) {
	ctx, span := trace.Start(ctx, "articles.Store.AddComment")
	defer trace.End(span, &err)
//line store.ego:198
	now := s.now().UnixMicro()
	res, err := s.sql.Conn(ctx).ExecContext(ctx, "INSERT INTO comments (article_id, author_id, body, created_at, updated_at) VALUES (?, ?, ?, ?, ?)",
		article, author, body, now, now)
	if err != nil {
		return 0, fmt.Errorf("Conn.ExecContext: %w", err)
	}
//line store.ego:201
	return res.LastInsertId()
}

// DeleteComment deletes the comment with the ID.
func (s *Store) DeleteComment(ctx context.Context, id int64) (err error) {
	ctx, span := trace.Start(ctx, "articles.Store.DeleteComment")
	defer trace.End(span, &err)
//line store.ego:206
	if _, err := s.sql.Conn(ctx).ExecContext(ctx, "DELETE FROM comments WHERE id = ?", id); err != nil {
		return fmt.Errorf("Conn.ExecContext: %w", err)
	}
//line store.ego:207
	return nil
}
