// Code generated by ego generate from generate.ego. DO NOT EDIT.

package openapi

import (
	"bytes"
	"cmp"
	"encoding/json/jsontext"
	"fmt"
	"mime"
	"net/http"
	"net/http/httptest"
	"reflect"
	"slices"
	"strconv"
	"strings"

	"github.com/goncini/goncini/httpkernel"
	"github.com/goncini/goncini/routing"
)

// Config is the part of a document that the code doesn't say, and where it
// is served.
//
//line generate.ego:22
type Config struct {
	// Title names the API; empty means "API".
	Title string
	// Version is the API's, not OpenAPI's; empty means "0.0.0".
	Version     string
	Description string
	// Servers are the URLs where the API is served; none means the
	// document's own.
	Servers []Server
	// Path is where the document is served; empty means /openapi.json.
	Path string
	// DocsPath is where a page that shows the document is served, with
	// Swagger UI; empty means no page. It is for development: the page
	// loads Swagger UI from a CDN.
	DocsPath string
}

// Annotations are what an API's code says beyond its types: the doc
// comments of its endpoints and types, and the errors each endpoint can
// fail with. goncini generate writes them from the source.
type Annotations struct {
	// Operations are by the full name of the endpoint's handler, as
	// httpkernel.Description.Func gives it.
	Operations map[string]OperationDoc
	Types      map[reflect.Type]TypeDoc
}

// OperationDoc is what the code says of an endpoint.
type OperationDoc struct {
	// Summary is the first sentence of the doc comment, and Description
	// the rest.
	Summary     string
	Description string
	// Errors are the errors that the endpoint can fail with, such as the
	// zero values of an error set's cases: each becomes a response,
	// through the kernel's error mappers and renderer.
	Errors []error
}

// TypeDoc is the doc comment of a type and of its fields.
type TypeDoc struct {
	Description string
	// Fields are by the field's path: Title, or Body.Article.Title for a
	// field of anonymous structs.
	Fields map[string]string
}

// Op is an operation being described, for Describers.
type Op struct {
	*Operation
	// Method and Path are the route's.
	Method, Path string
	// Errors are what the operation can fail with. Once every describer
	// has added its own, each becomes a response, through the kernel's
	// error mappers and renderer.
	Errors []error
	doc    *Document
}

// SecurityScheme adds a security scheme to the document.
func (op *Op) SecurityScheme(name string, s *SecurityScheme) {
	if op.doc.Components.SecuritySchemes == nil {
		op.doc.Components.SecuritySchemes = map[string]*SecurityScheme{}
	}
	op.doc.Components.SecuritySchemes[name] = s
}

// Describer is a handler that says what it adds to the operations it
// serves: a route's handler, or a handler that a route's or the kernel's
// middleware returns, such as a firewall's, which needs a token and
// answers 401.
type Describer interface {
	DescribeOperation(op *Op)
}

// Generate returns the document of an API: the operations of its routes,
// served by k. A route is an operation when its handler is an
// httpkernel.Endpoint or a Describer, and it has a method; the others are
// left out. a adds the doc comments and the errors of each endpoint.
//
// The operations' schemas come from the endpoints' types, as
// encoding/json/v2 encodes them, with the rules of their validate tags.
// Each error an operation can fail with becomes a response, rendered by k
// as an example: binding and validation errors, the errors in a, and those
// that describers add.
func Generate(routes []routing.Info, k *httpkernel.Kernel, c Config, a Annotations) (doc *Document, err error) {
	g := &generator{
		doc: &Document{
			OpenAPI: Version,
			Info:    Info{Title: c.Title, Version: c.Version, Description: c.Description},
			Servers: c.Servers,
			Paths:   map[string]*PathItem{},
		},
		k:       k,
		a:       a,
		schemas: newSchemas(a.Types),
		ids:     map[string]string{},
	}
	if g.doc.Info.Title == "" {
		g.doc.Info.Title = "API"
	}
	if g.doc.Info.Version == "" {
		g.doc.Info.Version = "0.0.0"
	}
	for _, r := range routes {
		if err2 := g.route(r); err2 != nil {
			return nil, err2
		}
	}
//line generate.ego:129
	g.doc.Components.Schemas = g.schemas.finish()
	for _, name := range g.tags {
		g.doc.Tags = append(g.doc.Tags, Tag{Name: name})
	}
	return g.doc, nil
}

// generator is the state of Generate.
type generator struct {
	doc     *Document
	k       *httpkernel.Kernel
	a       Annotations
	schemas *schemas
	tags    []string
	ids     map[string]string // operation IDs, to the routes that have them
}

// route adds the operation of r, if it is one.
func (g *generator) route(r routing.Info) error {
	d, isEndpoint := httpkernel.Describe(r.Handler)
	self, isDescriber := r.Handler.(Describer)
	if r.Method == "" || !isEndpoint && !isDescriber {
		return nil
	}
	path := pathOf(r.Path)
	item := g.doc.Paths[path]
	if item == nil {
		item = &PathItem{}
		g.doc.Paths[path] = item
	}
	field := item.Operation(r.Method)
	if field == nil {
		return nil // a method OpenAPI can't describe, such as CONNECT
	}
	op := &Op{Operation: &Operation{Responses: map[string]*Response{}}, Method: r.Method, Path: path, doc: g.doc}
	if isEndpoint {
		g.endpoint(op, d, r)
	}
	if op.OperationID == "" && r.Name != "" {
		op.OperationID = r.Name
	}
	if op.OperationID != "" {
		if other, taken := g.ids[op.OperationID]; taken {
			return fmt.Errorf("openapi: %s %s and %s have the same operation ID %q", r.Method, r.Path, other, op.OperationID)
		}
		g.ids[op.OperationID] = r.Method + " " + r.Path
	}
	var mws []func(http.Handler) http.Handler
	var v []httpkernel.Middleware
	if g.k != nil {
		v = g.k.Middleware
	}
	for _, mw := range v {
		mws = append(mws, mw)
	}
//line generate.ego:180
	mws = append(mws, r.Middleware...)
	for _, mw := range mws {
		if h, ok := mw(noop).(Describer); ok {
			h.DescribeOperation(op)
		}
	}
	if isDescriber {
		self.DescribeOperation(op)
	}
	if err := g.errors(op); err != nil {
		return err
	}
//line generate.ego:190
	*field = op.Operation
	return nil
}

// noop is the handler that middleware wraps, to describe what it returns.
var noop = http.HandlerFunc(func(http.ResponseWriter, *http.Request) {})

// pathOf is the OpenAPI path of a route's: /files/{path...} is
// /files/{path}.
func pathOf(p string) string {
	return strings.ReplaceAll(p, "...}", "}")
}

// endpoint describes an Endpoint's operation: its ID and tag from its
// handler's name, what it takes and returns, and the errors of binding and
// validation.
func (g *generator) endpoint(op *Op, d httpkernel.Description, r routing.Info) {
	recv, method := splitFunc(d.Func)
	op.OperationID = r.Name
	if op.OperationID == "" {
		op.OperationID = recv + method
	}
	op.Tags = []string{recv}
	if !slices.Contains(g.tags, recv) {
		g.tags = append(g.tags, recv)
	}
	doc := g.a.Operations[d.Func]
	op.Summary, op.Description = doc.Summary, doc.Description
	inDoc := g.a.Types[d.Input]
	var paramViolation *httpkernel.Violation
	for _, p := range d.Params {
		param := &Parameter{Name: p.Name, In: p.In, Required: p.Required, Description: inDoc.Fields[p.Field.Name], Schema: g.paramSchema(p)}
		if req, ok := r.Requirements[p.Name]; ok && p.In == "path" && param.Schema.Type.Is("string") {
			param.Schema.Pattern = "^(?:" + req + ")$"
		}
		op.Parameters = append(op.Parameters, param)
		if paramViolation == nil && canFail(p) {
			v := httpkernel.Violation{Parameter: p.Name, Detail: "is invalid"}
			if p.In == "header" {
				v = httpkernel.Violation{Header: p.Name, Detail: "is invalid"}
			}
			paramViolation = &v
		}
	}
	if paramViolation != nil {
		op.Errors = append(op.Errors, httpkernel.Problem{Status: http.StatusBadRequest, Detail: "invalid request parameters", Errors: []httpkernel.Violation{*paramViolation}})
	}
	validated := d.Validated
	invalid := httpkernel.Violation{Pointer: "#" + firstPointer(d.Body), Detail: "is invalid"}
	for _, p := range d.Params {
		if p.Field.Tag.Get("validate") != "" && !validated {
			validated, invalid = true, httpkernel.Violation{Parameter: p.Name, Detail: "is invalid"}
		}
	}
	if d.Body != nil {
		t := d.Body
		required := t.Kind() != reflect.Pointer
		if !required {
			t = t.Elem()
		}
		var schema *Schema
		if t.Kind() == reflect.Struct && t.Name() == "" {
			schema = g.schemas.object(t, reading, inDoc, "Body.")
		} else {
			schema = g.schemas.of(t, reading)
		}
		op.RequestBody = &RequestBody{Required: required, Description: inDoc.Fields["Body"], Content: map[string]*MediaType{"application/json": {Schema: schema}}}
		op.Errors = append(op.Errors,
			httpkernel.BodyMalformed{Offset: 1, Cause: fmt.Errorf("invalid character")},
			httpkernel.BodyMediaType{ContentType: "text/plain"},
			httpkernel.BodyTooLarge{Limit: httpkernel.DefaultBodyLimit},
			httpkernel.BodyInvalid{Pointer: firstPointer(t), Cause: fmt.Errorf("invalid value")},
		)
		if hasValidateTags(t, map[reflect.Type]bool{}) {
			validated, invalid = true, httpkernel.Violation{Pointer: "#" + firstPointer(t), Detail: "is invalid"}
		}
	}
	v2 := validated
	if v2 {
		v3 := d.Validated
		if !v3 {
			var v4 httpkernel.Validator
			if g.k != nil {
				v4 = g.k.Validator
			}
			v3 = v4 != nil
		}
		v2 = (v3)
	}
	if v2 {
		op.Errors = append(op.Errors, httpkernel.Invalid(invalid))
	}
//line generate.ego:270
	op.Errors = append(op.Errors, doc.Errors...)
	res := &Response{Description: http.StatusText(d.Status)}
	if d.Result != nil {
		res.Content = map[string]*MediaType{"application/json": {Schema: g.schemas.of(d.Result, writing)}}
	}
	op.Responses[strconv.Itoa(d.Status)] = res
}

// splitFunc returns the receiver type's name and the method's name of a
// handler's full name: Articles and Show for
// example.com/api/articles.(*Articles).Show. A function that isn't a method
// has its package's name, exported, as its receiver's.
func splitFunc(name string) (recv, method string) {
	name = name[strings.LastIndexByte(name, '/')+1:]
	parts := strings.Split(name, ".")
	method = exported(parts[len(parts)-1])
	if len(parts) >= 3 {
		recv = strings.Trim(parts[1], "(*)")
		if i := strings.IndexByte(recv, '['); i >= 0 {
			recv = recv[:i]
		}
		return recv, method
	}
	return exported(parts[0]), method
}

// paramSchema is the schema of a parameter's values.
func (g *generator) paramSchema(p httpkernel.ParamDescription) *Schema {
	t := p.Field.Type
	if t.Kind() == reflect.Pointer {
		t = t.Elem()
	}
	s := g.schemas.of(t, reading)
	if v := p.Field.Tag.Get("validate"); v != "" {
		constrain(s, t, v)
	}
	if p.Enum != nil {
		var target *Schema
		if s.Items != nil {
			target = s.Items
		} else {
			target = s
		}
//line generate.ego:308
		target.Enum = enumValues(t, p.Enum)
	}
	if p.Default != nil {
		if p.Multiple {
			s.Default = enumValues(t, p.Default)
		} else {
			s.Default = jsonValue(t, p.Default[0])
		}
	}
	return s
}

// canFail reports whether a parameter can be invalid: required, limited to
// some values, or of a type that a string may not parse as.
func canFail(p httpkernel.ParamDescription) bool {
	t := p.Field.Type
	for t.Kind() == reflect.Pointer || t.Kind() == reflect.Slice {
		t = t.Elem()
	}
	return p.Required && p.In != "path" || p.Enum != nil || t.Kind() != reflect.String
}

// firstPointer is the JSON pointer of the first member of a body of type
// t, for examples of violations; "" for the body itself.
func firstPointer(t reflect.Type) string {
	var p string
	for t != nil {
		for t.Kind() == reflect.Pointer {
			t = t.Elem()
		}
		if t.Kind() != reflect.Struct || t.NumField() == 0 {
			return p
		}
		f := t.Field(0)
		name, _, _ := strings.Cut(f.Tag.Get("json"), ",")
		if name == "" || name == "-" {
			name = f.Name
		}
		p += "/" + name
		t = f.Type
	}
	return p
}

// hasValidateTags reports whether a field of t, or of the types it holds,
// has a validate tag.
func hasValidateTags(t reflect.Type, seen map[reflect.Type]bool) bool {
	for t.Kind() == reflect.Pointer || t.Kind() == reflect.Slice || t.Kind() == reflect.Array || t.Kind() == reflect.Map {
		t = t.Elem()
	}
	if t.Kind() != reflect.Struct || seen[t] {
		return false
	}
	seen[t] = true
	for i := range t.NumField() {
		f := t.Field(i)
		if f.Tag.Get("validate") != "" || hasValidateTags(f.Type, seen) {
			return true
		}
	}
	return false
}

// errors adds a response for each status that op's errors are answered
// with, rendered by the kernel, with an example of each error.
func (g *generator) errors(op *Op) (err error) {
	var render httpkernel.Renderer
	if g.k != nil && g.k.Renderer != nil {
		render = g.k.Renderer
	} else {
		render = httpkernel.RenderProblem
	}
//line generate.ego:375
	req := httptest.NewRequest(op.Method, "/", nil)
	for _, e := range op.Errors {
		rec := &recorder{header: http.Header{}}
		func() {
			defer func() {
				if v := recover(); v != nil {
					err = fmt.Errorf("openapi: rendering %T for %s %s: %v", e, op.Method, op.Path, v)
				}
			}()
			render(rec, req, g.k.Problem(e))
		}()
		rec.WriteHeader(http.StatusOK) // a renderer that wrote nothing
		if err != nil {
			return err
		}
//line generate.ego:388
		status := strconv.Itoa(rec.status)
		res := op.Responses[status]
		if res == nil {
			res = &Response{Description: http.StatusText(rec.status)}
			op.Responses[status] = res
		}
		mediaType, _, _ := mime.ParseMediaType(rec.header.Get("Content-Type"))
		if mediaType == "" {
			mediaType = "application/octet-stream"
		}
		if res.Content == nil {
			res.Content = map[string]*MediaType{}
		}
		mt := res.Content[mediaType]
		if mt == nil {
			mt = &MediaType{}
			if rec.value != nil {
				mt.Schema = g.schemas.of(reflect.TypeOf(rec.value), writing)
			}
			res.Content[mediaType] = mt
		}
		if v := jsontext.Value(rec.body.Bytes()); v.IsValid() {
			if mt.Examples == nil {
				mt.Examples = map[string]*Example{}
			}
			ex := &Example{Summary: e.Error(), Value: v}
			name := exampleName(e)
			for n := 2; mt.Examples[name] != nil && !sameExample(mt.Examples[name], ex); n++ {
				name = exampleName(e) + strconv.Itoa(n)
			}
			mt.Examples[name] = ex
		}
		for h := range rec.header {
			if h == "Content-Type" || h == "Content-Length" {
				continue
			}
			if res.Headers == nil {
				res.Headers = map[string]*Header{}
			}
			res.Headers[h] = &Header{Schema: &Schema{Type: Types{"string"}}}
		}
	}
	return nil
}

// sameExample reports whether two examples say the same.
func sameExample(a, b *Example) bool {
	return a.Summary == b.Summary && bytes.Equal(a.Value, b.Value)
}

// exampleName names the example of an error: its type's name.
func exampleName(err error) string {
	t := reflect.TypeOf(err)
	for t.Kind() == reflect.Pointer {
		t = t.Elem()
	}
	return cmp.Or(t.Name(), "Error")
}

// recorder records what a renderer writes, and the value it writes as
// JSON.
type recorder struct {
	header http.Header
	status int
	body   bytes.Buffer
	value  any
}

func (r *recorder) Header() http.Header { return r.header }

func (r *recorder) WriteHeader(status int) {
	if r.status == 0 {
		r.status = status
	}
}

func (r *recorder) Write(b []byte) (int, error) {
	r.WriteHeader(http.StatusOK)
	return r.body.Write(b)
}

func (r *recorder) RecordValue(v any) { r.value = v }
