// Code generated by ego generate from generate_test.ego. DO NOT EDIT.

package openapi_test

import (
	"bytes"
	"context"
	"encoding/json/jsontext"
	"encoding/json/v2"
	"errors"
	"flag"
	"fmt"
	"net/http"
	"os"
	"reflect"
	"testing"

	"github.com/goncini/goncini/httpkernel"
	"github.com/goncini/goncini/openapi"
	"github.com/goncini/goncini/routing"
	"github.com/goncini/goncini/validator"

	"github.com/effect-go/effect-go/trace"
)

//line generate_test.ego:19
var update = flag.Bool("update", false, "rewrite the golden files")

// NoteError is everything the notes endpoints fail with.
type NoteError interface {
	error
	isNoteError()
}

type NoNote struct{ ID int64 }

func (NoNote) isNoteError() {}

func (e NoNote) Error() string { return fmt.Sprintf("no note %v", e.ID) }

// As lets pointers to NoNote match as NoNote.
func (e NoNote) As(target any) bool {
	if t, ok := target.(*NoNote); ok {
		*t = e
		return true
	}
	return false
}

type Unavailable struct{ Cause error }

func (Unavailable) isNoteError() {}

func (e Unavailable) Error() string { return "the notes are unavailable" }

func (e Unavailable) Unwrap() error { return e.Cause }

// As lets pointers to Unavailable match as Unavailable.
func (e Unavailable) As(target any) bool {
	if t, ok := target.(*Unavailable); ok {
		*t = e
		return true
	}
	return false
}

//line generate_test.ego:27
func noteProblem(err error) httpkernel.Problem {
	var v httpkernel.Problem
	if err == nil {
		v = httpkernel.Problem{}
	} else if e, ok := errors.AsType[NoNote](err); ok {
		v = httpkernel.Problem{Status: http.StatusNotFound, Detail: e.Error()}
	} else if _, ok := errors.AsType[Unavailable](err); ok {
		v = httpkernel.Problem{Status: http.StatusServiceUnavailable}
	} else {
		panic(err)
	}
	return v
}

// Note is a note.
//
//line generate_test.ego:36
type Note struct {
	ID    int64    `json:"id"`
	Title string   `json:"title"`
	Tags  []string `json:"tags"`
	// Bio is the author's.
	Bio    *string `json:"bio"`
	Hidden string  `json:"-"`
	Draft  bool    `json:"draft,omitempty"`
	Parent *Note   `json:"parent,omitzero"`
}

type NoteBody struct {
	Note Note `json:"note"`
}

type ShowInput struct {
	ID int64 `path:"id"`
}

type Page struct {
	Limit int `query:"limit" default:"20" validate:"min=1,max=100"`
}

type ListInput struct {
	Page
	Sort string   `query:"sort" enum:"asc,desc"`
	Tags []string `query:"tag"`
	Key  string   `header:"X-Key"`
}

type CreateInput struct {
	Body struct {
		Note struct {
			Title string                      `json:"title" validate:"required,max=120"`
			Tags  []string                    `json:"tags" validate:"max=5,dive,alpha"`
			Bio   httpkernel.Optional[string] `json:"bio"`
		} `json:"note" validate:"required"`
	}
}

type Notes struct{}

func (n *Notes) Show(ctx context.Context, in ShowInput) (_ NoteBody, err error) {
	ctx, span := trace.Start(ctx, "openapi_test.Notes.Show")
	defer trace.End(span, &err)
	return NoteBody{}, nil
}

//line generate_test.ego:82
func (n *Notes) List(ctx context.Context, in ListInput) (_ []Note, err error) {
	ctx, span := trace.Start(ctx, "openapi_test.Notes.List")
	defer trace.End(span, &err)
	return nil, nil
}

//line generate_test.ego:86
func (n *Notes) Create(ctx context.Context, in CreateInput) (_ httpkernel.Created[NoteBody], err error) {
	ctx, span := trace.Start(ctx, "openapi_test.Notes.Create")
	defer trace.End(span, &err)
	return httpkernel.Created[NoteBody]{}, nil
}

//line generate_test.ego:90
func (n *Notes) Delete(ctx context.Context, in ShowInput) (_ httpkernel.NoContent, err error) {
	ctx, span := trace.Start(ctx, "openapi_test.Notes.Delete")
	defer trace.End(span, &err)
	return httpkernel.NoContent{}, nil
}

// locked answers 423 to every request, and says so.
//
//line generate_test.ego:95
func locked(next http.Handler) http.Handler { return lockedHandler{} }

type lockedHandler struct{}

func (lockedHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {}

func (lockedHandler) DescribeOperation(op *openapi.Op) {
	op.Errors = append(op.Errors, httpkernel.Problem{Status: http.StatusLocked, Header: http.Header{"Retry-After": {"60"}}})
}

// notesAPI returns the routes and kernel of an API of notes, and the
// annotations goncini generate would write for it.
func notesAPI() (*routing.Router, *httpkernel.Kernel, openapi.Annotations) {
	n := &Notes{}
	r := routing.New()
	show := httpkernel.Endpoint(n.Show)
	r.Get("/notes/{id<\\d+>}", show).Name("note_show")
	r.Get("/notes", httpkernel.Endpoint(n.List))
	r.With(locked).Post("/notes", httpkernel.Endpoint(n.Create)).Name("note_create")
	r.Delete("/notes/{id}", httpkernel.Endpoint(n.Delete)).Name("note_delete")
	r.Handle("/health", http.NotFoundHandler())
	k := &httpkernel.Kernel{Handler: r, ErrorMappers: []httpkernel.ErrorMapper{httpkernel.Map[NoteError](noteProblem)}, Validator: validator.New()}
	d, _ := httpkernel.Describe(show)
	a := openapi.Annotations{
		Operations: map[string]openapi.OperationDoc{
			d.Func: {Summary: "Returns a note.", Description: "Anyone can read it.", Errors: []error{NoNote{}, Unavailable{}}},
		},
		Types: map[reflect.Type]openapi.TypeDoc{
			reflect.TypeFor[Note]():        {Description: "Note is a note.", Fields: map[string]string{"Bio": "Bio is the author's."}},
			reflect.TypeFor[CreateInput](): {Fields: map[string]string{"Body.Note.Title": "Title is the note's."}},
		},
	}
	return r, k, a
}

// TestGenerate compares the document of the notes API with the golden
// one: run go test -update to rewrite it, and review the diff.
func TestGenerate(t *testing.T) {
	r, k, a := notesAPI()
	doc, err := openapi.Generate(r.List(), k, openapi.Config{Title: "Notes", Version: "1.0.0"}, a)
	if err != nil {
		t.Fatal(err)
	}
	got, err := json.Marshal(doc, json.Deterministic(true), jsontext.Multiline(true), jsontext.WithIndent("  "))
	if err != nil {
		t.Fatal(err)
	}
	golden(t, "testdata/notes.json", got)
}

// golden compares got with the file, or rewrites the file with -update.
func golden(t *testing.T, file string, got []byte) {
	t.Helper()
	got = append(got, '\n')
	if *update {
		if err := os.WriteFile(file, got, 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	want, err := os.ReadFile(file)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(got, want) {
		t.Errorf("%s differs: run go test -update, and review the diff\n%s", file, got)
	}
}

func TestDuplicateOperationIDs(t *testing.T) {
	n := &Notes{}
	r := routing.New()
	r.Get("/a", httpkernel.Endpoint(n.Show))
	r.Get("/b", httpkernel.Endpoint(n.Show))
	if _, err := openapi.Generate(r.List(), nil, openapi.Config{}, openapi.Annotations{}); err == nil {
		t.Error("no error for two operations named the same")
	}
}
