// Code generated by ego generate from schema.ego. DO NOT EDIT.

package openapi

import (
	"encoding"
	"encoding/json/jsontext"
	"encoding/json/v2"
	"fmt"
	"reflect"
	"slices"
	"strconv"
	"strings"
	"time"
	"unicode"
)

// SchemaProvider is a type that gives its own JSON Schema, such as a type
// with a custom JSON form. Generate calls it on the zero value.
//
//line schema.ego:17
type SchemaProvider interface {
	OpenAPISchema() *Schema
}

// mode is whether a schema describes what the API reads or writes: they
// differ in which members are required.
type mode int

const (
	// writing is what the API writes: members are required unless they are
	// omitted when empty or zero.
	writing mode = iota
	// reading is what the API reads: members are required when their
	// validate tag says so.
	reading
)

func (v mode) String() string {
	switch v {
	case writing:
		return "writing"
	case reading:
		return "reading"
	}
	return "mode(" + strconv.Itoa(int(v)) + ")"
}

// schemaKey is a named struct type, in a mode: a component.
//
//line schema.ego:33
type schemaKey struct {
	t reflect.Type
	m mode
}

// schemas makes the JSON Schemas of Go types, as encoding/json/v2 encodes
// them. Named struct types become components, which the schemas refer to.
type schemas struct {
	docs       map[reflect.Type]TypeDoc
	components map[schemaKey]*Schema
	refs       map[schemaKey][]*Schema // the $refs to each component, filled in by name
	order      []schemaKey
}

func newSchemas(docs map[reflect.Type]TypeDoc) *schemas {
	return &schemas{docs: docs, components: map[schemaKey]*Schema{}, refs: map[schemaKey][]*Schema{}}
}

var (
	timeType          = reflect.TypeFor[time.Time]()
	durationType      = reflect.TypeFor[time.Duration]()
	jsontextValue     = reflect.TypeFor[jsontext.Value]()
	schemaProvider    = reflect.TypeFor[SchemaProvider]()
	textMarshaler     = reflect.TypeFor[encoding.TextMarshaler]()
	textUnmarshaler   = reflect.TypeFor[encoding.TextUnmarshaler]()
	jsonMarshalers    = []reflect.Type{reflect.TypeFor[json.Marshaler](), reflect.TypeFor[json.MarshalerTo]()}
	jsonUnmarshalers  = []reflect.Type{reflect.TypeFor[json.Unmarshaler](), reflect.TypeFor[json.UnmarshalerFrom]()}
	httpkernelPkgPath = "github.com/goncini/goncini/httpkernel"
)

// of returns the schema of t, in mode m.
func (s *schemas) of(t reflect.Type, m mode) *Schema {
	if t.Kind() == reflect.Pointer {
		return nullable(s.of(t.Elem(), m))
	}
	if own := provided(t); own != nil {
		return own
	}
	if t.PkgPath() == httpkernelPkgPath && strings.HasPrefix(t.Name(), "Optional[") {
		// httpkernel.Optional[T]: absent, null or a T.
		value, _ := t.FieldByName("Value")
		return nullable(s.of(value.Type, m))
	}
	switch {
	case t == timeType:
		return &Schema{Type: Types{"string"}, Format: "date-time"}
	case t == durationType:
		return &Schema{Type: Types{"string"}, Format: "duration"}
	case t == jsontextValue:
		return &Schema{}
	case m == writing && implementsAny(t, jsonMarshalers), m == reading && implementsAny(t, jsonUnmarshalers):
		return &Schema{} // a JSON form of its own, unknown
	case m == writing && implements(t, textMarshaler), m == reading && implements(t, textUnmarshaler):
		return &Schema{Type: Types{"string"}}
	}
	switch t.Kind() {
	case reflect.Bool:
		return &Schema{Type: Types{"boolean"}}
	case reflect.Int, reflect.Int8, reflect.Int16:
		return &Schema{Type: Types{"integer"}}
	case reflect.Int32:
		return &Schema{Type: Types{"integer"}, Format: "int32"}
	case reflect.Int64:
		return &Schema{Type: Types{"integer"}, Format: "int64"}
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		return &Schema{Type: Types{"integer"}, Minimum: new(0.0)}
	case reflect.Float32, reflect.Float64:
		return &Schema{Type: Types{"number"}}
	case reflect.String:
		return &Schema{Type: Types{"string"}}
	case reflect.Slice, reflect.Array:
		if t.Elem().Kind() == reflect.Uint8 {
			return &Schema{Type: Types{"string"}, Format: "byte"} // base64
		}
		return &Schema{Type: Types{"array"}, Items: s.of(t.Elem(), m)}
	case reflect.Map:
		return &Schema{Type: Types{"object"}, AdditionalProperties: s.of(t.Elem(), m)}
	case reflect.Struct:
		if t.Name() == "" {
			return s.object(t, m, s.docs[t], "")
		}
		return s.ref(t, m)
	}
	return &Schema{} // an interface: any value
}

// provided returns the schema that t, or *t, gives as a SchemaProvider, or
// nil.
func provided(t reflect.Type) *Schema {
	var v any
	switch {
	case t.Implements(schemaProvider):
		v = reflect.Zero(t).Interface()
	case reflect.PointerTo(t).Implements(schemaProvider):
		v = reflect.New(t).Interface()
	default:
		return nil
	}
	v2 := v.(SchemaProvider).OpenAPISchema()
	if v2 == nil {
		v2 = &Schema{}
	}
	own := *(v2)
//line schema.ego:132
	return &own
}

// ref returns a $ref to the component of t, a named struct type, making it
// first if needed.
func (s *schemas) ref(t reflect.Type, m mode) *Schema {
	key := schemaKey{t, m}
	r := &Schema{Ref: "?"} // finish names it
	s.refs[key] = append(s.refs[key], r)
	if _, ok := s.components[key]; !ok {
		s.components[key] = nil // being made: recursive types refer to it
		s.order = append(s.order, key)
		s.components[key] = s.object(t, m, s.docs[t], "")
	}
	return r
}

// object returns the schema of a struct type t, whose fields are
// documented by doc under the field path prefix.
func (s *schemas) object(t reflect.Type, m mode, doc TypeDoc, prefix string) *Schema {
	var v string
	if prefix == "" {
		v = doc.Description
	} else {
		v = ""
	}
	o := &Schema{Type: Types{"object"}, Properties: map[string]*Schema{}, Description: v}
//line schema.ego:153
	s.fields(o, t, m, doc, prefix)
	if len(o.Properties) == 0 {
		o.Properties = nil
	}
	return o
}

// member is a JSON member that a struct field gives, before
// encoding/json/v2's rules choose among those of the same name.
type member struct {
	name     string
	depth    int  // how deep in embedded structs
	tagged   bool // named by its json tag
	field    reflect.StructField
	options  []string
	doc      TypeDoc
	prefix   string // of the field's path, for its doc
	optional bool   // in an embedded pointer, absent when it is nil
}

// fields adds the members of t's fields to o, as encoding/json/v2 encodes
// them: embedded structs without a JSON name have their members promoted,
// and of the members with the same name, the shallowest wins, or else the
// only one tagged with it, or else none.
func (s *schemas) fields(o *Schema, t reflect.Type, m mode, doc TypeDoc, prefix string) {
	var all []member
	s.collect(&all, o, t, m, doc, prefix, 0, false)
	byName := map[string][]member{}
	var names []string
	for _, mb := range all {
		if byName[mb.name] == nil {
			names = append(names, mb.name)
		}
		byName[mb.name] = append(byName[mb.name], mb)
	}
	for _, name := range names {
		if mb, ok := dominant(byName[name]); ok {
			s.member(o, mb, m)
		}
	}
}

// collect adds the members of t's fields to all, and the fallback of an
// embedded map to o.
func (s *schemas) collect(all *[]member, o *Schema, t reflect.Type, m mode, doc TypeDoc, prefix string, depth int, optional bool) {
	for i := range t.NumField() {
		f := t.Field(i)
		tag := f.Tag.Get("json")
		name, opts, _ := strings.Cut(tag, ",")
		if tag == "-" || !f.IsExported() && !f.Anonymous {
			continue
		}
		options := strings.Split(opts, ",")
		if slices.Contains(options, "embed") || slices.Contains(options, "inline") || f.Anonymous && name == "" {
			elem := f.Type
			if elem.Kind() == reflect.Pointer {
				elem = elem.Elem()
			}
			if elem.Kind() == reflect.Map {
				o.AdditionalProperties = s.of(elem.Elem(), m) // a fallback for any member
				continue
			}
			if elem.Kind() == reflect.Struct {
				inner, innerPrefix := s.docs[elem], ""
				if elem.Name() == "" {
					inner, innerPrefix = doc, prefix+f.Name+"."
				}
				s.collect(all, o, elem, m, inner, innerPrefix, depth+1, optional || f.Type.Kind() == reflect.Pointer)
				continue
			}
		}
		if !f.IsExported() {
			continue
		}
		mb := member{name: name, depth: depth, tagged: name != "", field: f, options: options, doc: doc, prefix: prefix, optional: optional}
		if mb.name == "" {
			mb.name = f.Name
		}
		*all = append(*all, mb)
	}
}

// dominant returns the member that json/v2 writes of those with a name.
func dominant(ms []member) (member, bool) {
	depth := ms[0].depth
	for _, mb := range ms {
		depth = min(depth, mb.depth)
	}
	var shallowest, tagged []member
	for _, mb := range ms {
		if mb.depth == depth {
			shallowest = append(shallowest, mb)
			if mb.tagged {
				tagged = append(tagged, mb)
			}
		}
	}
	switch {
	case len(shallowest) == 1:
		return shallowest[0], true
	case len(tagged) == 1:
		return tagged[0], true
	}
	return member{}, false
}

// member adds a member to o.
func (s *schemas) member(o *Schema, mb member, m mode) {
	f, ft := mb.field, mb.field.Type
	var p *Schema
	if ft.Kind() == reflect.Struct && ft.Name() == "" {
		p = s.object(ft, m, mb.doc, mb.prefix+f.Name+".")
	} else {
		p = s.of(ft, m)
	}
	if slices.Contains(mb.options, "string") {
		p = quoted(p)
	}
	required := false
	if v, ok := f.Tag.Lookup("validate"); ok {
		required = constrain(p, ft, v)
	}
	if m == writing {
		required = !slices.Contains(mb.options, "omitempty") && !slices.Contains(mb.options, "omitzero")
	} else if !required {
		// A struct with required members is required itself: without
		// it, they are missing.
		required = len(s.inner(p, ft, m).Required) > 0
	}
	if d := mb.doc.Fields[mb.prefix+f.Name]; d != "" {
		p = described(p, d)
	}
	o.Properties[mb.name] = p
	if required && !mb.optional && !slices.Contains(o.Required, mb.name) {
		o.Required = append(o.Required, mb.name)
	}
}

// inner returns the object schema of a struct field of type t, whose
// schema is p: p itself, or the component p refers to. It is empty for a
// field of another type, which may be absent.
func (s *schemas) inner(p *Schema, t reflect.Type, m mode) *Schema {
	if t.Kind() != reflect.Struct || p.Type.Is("null") {
		return &Schema{}
	}
	if p.Ref != "" {
		v, ok := s.components[schemaKey{t, m}]
		if !ok {
			v = &Schema{}
		}
		return v
	}
//line schema.ego:301
	return p
}

// quoted is the schema of a number or boolean written as a JSON string,
// by the json tag's string option.
func quoted(p *Schema) *Schema {
	if p.Type.Is("integer") || p.Type.Is("number") || p.Type.Is("boolean") {
		q := Schema{Type: Types{"string"}, Description: p.Description}
		if p.Type.Is("null") {
			q.Type = append(q.Type, "null")
		}
		return &q
	}
	return p
}

// described returns p with a description. A $ref keeps its own schema: the
// description goes next to it.
func described(p *Schema, d string) *Schema {
	if p.Description == "" {
		p.Description = d
	}
	return p
}

// nullable returns the schema that also allows null.
func nullable(p *Schema) *Schema {
	switch {
	case p.Ref != "":
		return &Schema{AnyOf: []*Schema{p, {Type: Types{"null"}}}}
	case len(p.Type) == 0 || p.Type.Is("null"):
		return p
	}
	p.Type = append(p.Type, "null")
	return p
}

// implements reports whether t or *t implements the interface.
func implements(t, iface reflect.Type) bool {
	return t.Implements(iface) || t.Kind() != reflect.Pointer && reflect.PointerTo(t).Implements(iface)
}

// implementsAny reports whether t or *t implements one of the interfaces.
func implementsAny(t reflect.Type, ifaces []reflect.Type) bool {
	return slices.ContainsFunc(ifaces, func(i reflect.Type) bool { return implements(t, i) })
}

// finish names the components and fills in the $refs to them. A type is
// named as Go does, with its package's name before it if another type has
// the same name. Its reading schema shares its writing schema's component
// when they are the same, refs included; or else it is named with Input
// after it. A name taken already gets a number after it.
func (s *schemas) finish() map[string]*Schema {
	if len(s.order) == 0 {
		return nil
	}
	types := map[reflect.Type]bool{}
	byBase := map[string][]reflect.Type{}
	for _, k := range s.order {
		if !types[k.t] {
			types[k.t] = true
			b := baseName(k.t)
			byBase[b] = append(byBase[b], k.t)
		}
	}
	base := map[reflect.Type]string{}
	for b, ts := range byBase {
		for _, t := range ts {
			if len(ts) == 1 {
				base[t] = b
			} else {
				base[t] = exported(packageName(t)) + b
			}
		}
	}
	// Refs hold markers of their keys until the names are known.
//line schema.ego:373
	index := map[schemaKey]int{}
	for i, k := range s.order {
		index[k] = i
		for _, r := range s.refs[k] {
			r.Ref = fmt.Sprintf("#/components/schemas/\x00%d\x00", i)
		}
	}
	// A type's two schemas share a component if they are the same once the
	// refs to types whose schemas share theirs are written the same:
	// assume all do, then split those that differ, until none does.
	shared := map[reflect.Type]bool{}
	for _, k := range s.order {
		if _, both := s.components[schemaKey{k.t, writing}]; both && k.m == reading {
			shared[k.t] = true
		}
	}
	label := func(k schemaKey) string {
		var v string
		if shared[k.t] {
			v = fmt.Sprintf("%s", base[k.t])
		} else {
			v = fmt.Sprintf("%s/%v", base[k.t], k.m)
		}
		return v
	}
//line schema.ego:390
	render := func(sch *Schema) string { return s.render(sch, label) }
	for changed := true; changed; {
		changed = false
		for t := range shared {
			if render(s.components[schemaKey{t, reading}]) != render(s.components[schemaKey{t, writing}]) {
				delete(shared, t)
				changed = true
			}
		}
	}
	names := map[schemaKey]string{}
	out := map[string]*Schema{}
	// Types' own names first, then those with Input.
	keys := slices.Clone(s.order)
	slices.SortStableFunc(keys, func(a, b schemaKey) int {
		var v int
		if a.m == b.m {
			v = 0
		} else if a.m == writing {
			v = -1
		} else {
			v = 1
		}
		return v
	})
//line schema.ego:405
	for _, k := range keys {
		if k.m == reading && shared[k.t] {
			continue
		}
		name := base[k.t]
		if k.m == reading {
			if _, both := s.components[schemaKey{k.t, writing}]; both {
				name += "Input"
			}
		}
		unique := name
		for n := 2; out[unique] != nil; n++ {
			unique = name + strconv.Itoa(n)
		}
		out[unique] = s.components[k]
		names[k] = unique
	}
	for k, i := range index {
		name, ok := names[k]
		if !ok {
			name = names[schemaKey{k.t, writing}]
		}
//line schema.ego:424
		marker := fmt.Sprintf("#/components/schemas/\x00%d\x00", i)
		for _, r := range s.refs[k] {
			if r.Ref == marker {
				r.Ref = "#/components/schemas/" + name
			}
		}
	}
	return out
}

// render writes sch as JSON, with each ref's marker replaced by the label
// of its key, to compare schemas.
func (s *schemas) render(sch *Schema, label func(schemaKey) string) string {
	b, _ := json.Marshal(sch, json.Deterministic(true))
	text := string(b)
	for i, k := range s.order {
		text = strings.ReplaceAll(text, fmt.Sprintf("\\u0000%d\\u0000", i), label(k))
	}
	return text
}

// baseName is the name of a type, with the type arguments of a generic one
// written after it: Page[articles.Article] is PageArticle.
func baseName(t reflect.Type) string {
	name, args, generic := strings.Cut(t.Name(), "[")
	if !generic {
		return name
	}
	var b strings.Builder
	b.WriteString(name)
	for _, a := range strings.FieldsFunc(strings.TrimSuffix(args, "]"), func(r rune) bool { return r == ',' || r == '[' || r == ']' || r == '*' || r == ' ' }) {
		a = a[strings.LastIndexAny(a, "./")+1:]
		b.WriteString(exported(a))
	}
	return b.String()
}

// packageName is the name of t's package: the last element of its path.
func packageName(t reflect.Type) string {
	parts := strings.Split(t.PkgPath(), "/")
	last := parts[len(parts)-1]
	if len(parts) > 1 && len(last) > 1 && last[0] == 'v' && strings.Trim(last[1:], "0123456789") == "" {
		last = parts[len(parts)-2] // a major version: example.com/api/v2
	}
	return last
}

// exported returns s with its first letter upper case.
func exported(s string) string {
	for i, r := range s {
		return string(unicode.ToUpper(r)) + s[i+len(string(r)):]
	}
	return s
}

// constrain adds the rules of a validate tag to p, the schema of a value of
// type t, and reports whether the value is required. Rules after dive are
// the elements'.
func constrain(p *Schema, t reflect.Type, tag string) bool {
	required := false
	rules := strings.Split(tag, ",")
	// With omitempty, the zero value passes every rule: only the upper
	// bounds hold for all values.
	empty := slices.Contains(rules[:slices.Index(append(rules, "dive"), "dive")], "omitempty")
	if empty {
		defer func() {
			p.MinLength, p.MinItems, p.Minimum, p.ExclusiveMinimum = nil, nil, nil, nil
			p.Pattern, p.Format = "", ""
			if p.Enum != nil {
				elem := t
				for elem.Kind() == reflect.Pointer {
					elem = elem.Elem()
				}
				p.Enum = append(p.Enum, reflect.Zero(elem).Interface())
			}
		}()
	}
	defer func() {
		if p.Enum != nil && p.Type.Is("null") {
			p.Enum = append(p.Enum, nil)
		}
	}()
	for i, rule := range rules {
		if rule == "dive" {
			if items := itemsOf(p); items != nil && (t.Kind() == reflect.Slice || t.Kind() == reflect.Array || t.Kind() == reflect.Map) {
				constrain(items, t.Elem(), strings.Join(rules[i+1:], ","))
			}
			break
		}
		name, param, _ := strings.Cut(rule, "=")
		if strings.Contains(rule, "|") {
			continue // alternatives: no single rule holds
		}
		switch name {
		case "required":
			required = true
		case "min", "gte":
			limit(p, t, param, false, true)
		case "max", "lte":
			limit(p, t, param, true, true)
		case "gt":
			limit(p, t, param, false, false)
		case "lt":
			limit(p, t, param, true, false)
		case "len":
			limit(p, t, param, false, true)
			limit(p, t, param, true, true)
		case "oneof":
			p.Enum = enumValues(t, oneOf(param))
		case "unique":
			p.UniqueItems = true
		case "email":
			p.Format = "email"
		case "url", "uri", "http_url":
			p.Format = "uri"
		case "uuid", "uuid4", "uuid_rfc4122", "uuid4_rfc4122":
			p.Format = "uuid"
		case "ipv4":
			p.Format = "ipv4"
		case "ipv6":
			p.Format = "ipv6"
		case "hostname", "hostname_rfc1123":
			p.Format = "hostname"
		case "alpha":
			p.Pattern = "^[a-zA-Z]+$"
		case "alphanum":
			p.Pattern = "^[a-zA-Z0-9]+$"
		case "numeric":
			p.Pattern = `^[-+]?[0-9]+(?:\.[0-9]+)?$`
		}
	}
	return required
}

// itemsOf returns the schema of the elements of an array or map schema.
func itemsOf(p *Schema) *Schema {
	if p.Items != nil {
		return p.Items
	}
	return p.AdditionalProperties
}

// limit adds a bound to p, the schema of a value of type t: on its length
// for a string, on its number of items for a slice, array or map, and on
// its value for a number.
func limit(p *Schema, t reflect.Type, param string, upper, inclusive bool) {
	for t.Kind() == reflect.Pointer {
		t = t.Elem()
	}
	n, err := strconv.ParseFloat(param, 64)
	if err != nil {
		return // a duration, or a field's name: not a bound JSON Schema can say
	}
	switch t.Kind() {
	case reflect.String, reflect.Slice, reflect.Array, reflect.Map:
		count := int(n)
		if !inclusive {
			if upper {
				count = count - 1
			} else {
				count = count + 1
			}
		}
//line schema.ego:583
		if t.Kind() == reflect.String {
			if upper {
				p.MaxLength = &count
			} else {
				p.MinLength = &count
			}
		} else if t.Kind() != reflect.Map {
			if upper {
				p.MaxItems = &count
			} else {
				p.MinItems = &count
			}
		}
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		switch {
		case !upper && inclusive:
			p.Minimum = &n
		case upper && inclusive:
			p.Maximum = &n
		case !upper:
			p.ExclusiveMinimum = &n
		default:
			p.ExclusiveMaximum = &n
		}
	}
}

// oneOf splits the values of a oneof rule: separated by spaces, or quoted
// with single quotes when they hold some.
func oneOf(param string) []string {
	var values []string
	for param != "" {
		param = strings.TrimLeft(param, " ")
		if strings.HasPrefix(param, "'") {
			v, rest, _ := strings.Cut(param[1:], "'")
			values, param = append(values, v), rest
			continue
		}
		v, rest, _ := strings.Cut(param, " ")
		if v != "" {
			values = append(values, v)
		}
		param = rest
	}
	return values
}

// enumValues converts values written as strings to t's JSON values: numbers
// and booleans for those kinds.
func enumValues(t reflect.Type, values []string) []any {
	out := make([]any, 0, len(values))
	for _, v := range values {
		out = append(out, jsonValue(t, v))
	}
	return out
}

// jsonValue is the JSON value of s, written as a parameter of type t.
func jsonValue(t reflect.Type, s string) any {
	for t.Kind() == reflect.Pointer || t.Kind() == reflect.Slice {
		t = t.Elem()
	}
	switch t.Kind() {
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		if n, err := strconv.ParseInt(s, 10, 64); err == nil {
			return n
		}
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		if n, err := strconv.ParseUint(s, 10, 64); err == nil {
			return n
		}
	case reflect.Float32, reflect.Float64:
		if n, err := strconv.ParseFloat(s, 64); err == nil {
			return n
		}
	case reflect.Bool:
		if b, err := strconv.ParseBool(s); err == nil {
			return b
		}
	}
	return s
}
