// Code generated by ego generate from serve.ego. DO NOT EDIT.

package openapi

import (
	"encoding/json/v2"
	"html/template"
	"net/http"
	"strconv"

	"github.com/goncini/goncini/routing"
)

// DefaultPath is where Mount serves the document unless Config.Path says
// otherwise.
//
//line serve.ego:14
const DefaultPath = "/openapi.json"

// Handler returns a handler that serves doc as JSON. The document is
// encoded once: changing it afterwards changes nothing.
func Handler(doc *Document) (http.Handler, error) {
	b, err := json.Marshal(doc, json.Deterministic(true))
	if err != nil {
		return nil, err
	}
//line serve.ego:20
	return documentHandler(b), nil
}

// documentHandler serves an encoded document.
type documentHandler []byte

func (b documentHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Content-Length", strconv.Itoa(len(b)))
	w.Write(b)
}

// String names the handler in route listings.
func (documentHandler) String() string { return "openapi.Handler" }

// Mount registers on r the route that serves doc, named "openapi", at
// c.Path, and the docs page's, named "openapi_docs", at c.DocsPath if it
// isn't empty.
func Mount(r *routing.Router, doc *Document, c Config) error {
	h, err := Handler(doc)
	if err != nil {
		return err
	}
//line serve.ego:40
	path := c.Path
	if path == "" {
		path = DefaultPath
	}
	r.Get(path, h).Name("openapi")
	if c.DocsPath != "" {
		r.Get(c.DocsPath, DocsPage(doc.Info.Title, path)).Name("openapi_docs")
	}
	return nil
}

// DocsPage returns a handler that serves a page showing the document at
// url with Swagger UI, which the page loads from a CDN.
func DocsPage(title, url string) http.Handler {
	return docsHandler{title, url}
}

// docsHandler serves the docs page.
type docsHandler struct {
	title, url string
}

func (h docsHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	docsPage.Execute(w, map[string]string{"Title": h.title, "URL": h.url})
}

// String names the handler in route listings.
func (docsHandler) String() string { return "openapi.DocsPage" }

var docsPage = template.Must(template.New("docs").Parse(`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{.Title}}</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swagger-ui-dist@5/swagger-ui.css">
</head>
<body>
<div id="docs"></div>
<script src="https://cdn.jsdelivr.net/npm/swagger-ui-dist@5/swagger-ui-bundle.js"></script>
<script>SwaggerUIBundle({url: {{.URL}}, dom_id: "#docs", deepLinking: true})</script>
</body>
</html>
`))
