// Code generated by ego generate from controller.ego. DO NOT EDIT.

package users

import (
	"context"
	"strconv"

	"github.com/goncini/goncini/httpkernel"
	"github.com/goncini/goncini/routing"
	"github.com/goncini/goncini/security"

	"github.com/effect-go/effect-go/trace"
)

// Users serves the users and their profiles.
//
//line controller.ego:12
type Users struct {
	store  *Store
	hasher security.Hasher
	tokens *security.Tokens
}

func NewUsers(store *Store, hasher security.Hasher, tokens *security.Tokens) *Users {
	return &Users{store: store, hasher: hasher, tokens: tokens}
}

// Routes registers the endpoints.
func (u *Users) Routes(r *routing.Router) {
	r.Post("/users", httpkernel.Endpoint(u.Register)).Name("user_register")
	r.Post("/users/login", httpkernel.Endpoint(u.Login)).Name("user_login")
	r.Get("/profiles/{username}", httpkernel.Endpoint(u.Profile)).Name("profile_show")
	auth := r.With(security.Required)
	auth.Get("/user", httpkernel.Endpoint(u.Current)).Name("user_current")
	auth.Put("/user", httpkernel.Endpoint(u.Update)).Name("user_update")
	auth.Post("/profiles/{username}/follow", httpkernel.Endpoint(u.Follow)).Name("profile_follow")
	auth.Delete("/profiles/{username}/follow", httpkernel.Endpoint(u.Unfollow)).Name("profile_unfollow")
}

// UserBody is the user that a user sees, with a token.
type UserBody struct {
	User struct {
		Email    string  `json:"email"`
		Token    string  `json:"token"`
		Username string  `json:"username"`
		Bio      *string `json:"bio"`
		Image    *string `json:"image"`
	} `json:"user"`
}

// body returns what user sees of themselves, with a new token.
func (u *Users) body(user *User) (UserBody, error) {
	var b UserBody
	v, err := u.tokens.Issue(strconv.FormatInt(user.ID, 10))
	if err != nil {
		return UserBody{}, err
	}
	b.User.Token = v
//line controller.ego:49
	b.User.Email, b.User.Username, b.User.Bio, b.User.Image = user.Email, user.Username, user.Bio, user.Image
	return b, nil
}

type RegisterInput struct {
	Body struct {
		User struct {
			Username string `json:"username" validate:"required"`
			Email    string `json:"email" validate:"required"`
			Password string `json:"password" validate:"required"`
		} `json:"user"`
	}
}

func (u *Users) Register(ctx context.Context, in RegisterInput) (_ httpkernel.Created[UserBody], err error) {
	ctx, span := trace.Start(ctx, "users.Users.Register")
	defer trace.End(span, &err)
//line controller.ego:64
	b := in.Body.User
	hash, err := u.hasher.Hash(b.Password)
	if err != nil {
		return httpkernel.Created[UserBody]{}, Unavailable{Cause: err}
	}
//line controller.ego:66
	user := &User{Username: b.Username, Email: b.Email, PasswordHash: hash}
	taken, err := u.store.Save(ctx, user)
	if err != nil {
		return httpkernel.Created[UserBody]{}, Unavailable{Cause: err}
	}
//line controller.ego:68
	if taken != "" {
		return httpkernel.Created[UserBody]{}, Taken{Field: taken}
	}
	body, err := u.body(user)
	if err != nil {
		return httpkernel.Created[UserBody]{}, Unavailable{Cause: err}
	}
//line controller.ego:72
	return httpkernel.Created[UserBody]{Body: body}, nil
}

type LoginInput struct {
	Body struct {
		User struct {
			Email    string `json:"email" validate:"required"`
			Password string `json:"password" validate:"required"`
		} `json:"user"`
	}
}

func (u *Users) Login(ctx context.Context, in LoginInput) (_ UserBody, err error) {
	ctx, span := trace.Start(ctx, "users.Users.Login")
	defer trace.End(span, &err)
//line controller.ego:85
	user, ok, err := u.store.ByEmail(ctx, in.Body.User.Email)
	if err != nil {
		return UserBody{}, Unavailable{Cause: err}
	}
//line controller.ego:86
	if !ok {
		return UserBody{}, BadCredentials{}
	}
	valid, err := u.hasher.Verify(user.PasswordHash, in.Body.User.Password)
	if err != nil {
		return UserBody{}, Unavailable{Cause: err}
	}
//line controller.ego:90
	if !valid {
		return UserBody{}, BadCredentials{}
	}
	body, err := u.body(user)
	if err != nil {
		return UserBody{}, Unavailable{Cause: err}
	}
//line controller.ego:94
	return body, nil
}

func (u *Users) Current(ctx context.Context, in struct{}) (_ UserBody, err error) {
	ctx, span := trace.Start(ctx, "users.Users.Current")
	defer trace.End(span, &err)
//line controller.ego:98
	body, err := u.body(Current(ctx))
	if err != nil {
		return UserBody{}, Unavailable{Cause: err}
	}
//line controller.ego:99
	return body, nil
}

type UpdateInput struct {
	Body struct {
		User struct {
			Email    httpkernel.Optional[string] `json:"email"`
			Username httpkernel.Optional[string] `json:"username"`
			Password httpkernel.Optional[string] `json:"password"`
			Bio      httpkernel.Optional[string] `json:"bio"`
			Image    httpkernel.Optional[string] `json:"image"`
		} `json:"user"`
	}
}

// Validate refuses to clear what a user must have. A password has at least
// 8 characters, as NIST 800-63B says, and no other rule.
func (in *UpdateInput) Validate() error {
	b := in.Body.User
	var vs []httpkernel.Violation
	for name, field := range map[string]httpkernel.Optional[string]{"email": b.Email, "username": b.Username, "password": b.Password} {
		if field.Set && (field.Null || field.Value == "") {
			vs = append(vs, httpkernel.Violation{Pointer: "#/user/" + name, Detail: "can't be blank"})
		}
	}
	if b.Password.Present() && b.Password.Value != "" && len([]rune(b.Password.Value)) < 8 {
		vs = append(vs, httpkernel.Violation{Pointer: "#/user/password", Detail: "is too short (minimum is 8 characters)"})
	}
	if len(vs) > 0 {
		return httpkernel.Invalid(vs...)
	}
	return nil
}

func (u *Users) Update(ctx context.Context, in UpdateInput) (_ UserBody, err error) {
	ctx, span := trace.Start(ctx, "users.Users.Update")
	defer trace.End(span, &err)
//line controller.ego:134
	b := in.Body.User
	user := *Current(ctx)
	if b.Email.Set {
		user.Email = b.Email.Value
	}
	if b.Username.Set {
		user.Username = b.Username.Value
	}
	if b.Password.Set {
		v, err := u.hasher.Hash(b.Password.Value)
		if err != nil {
			return UserBody{}, Unavailable{Cause: err}
		}
		user.PasswordHash = v
	}
//line controller.ego:145
	if b.Bio.Set {
		user.Bio = orNull(b.Bio)
	}
	if b.Image.Set {
		user.Image = orNull(b.Image)
	}
	taken, err := u.store.Save(ctx, &user)
	if err != nil {
		return UserBody{}, Unavailable{Cause: err}
	}
//line controller.ego:152
	if taken != "" {
		return UserBody{}, Taken{Field: taken}
	}
	body, err := u.body(&user)
	if err != nil {
		return UserBody{}, Unavailable{Cause: err}
	}
//line controller.ego:156
	return body, nil
}

// orNull returns the value of o, or nil for null and "".
func orNull(o httpkernel.Optional[string]) *string {
	var v *string
	if o.Null || o.Value == "" {
		v = nil
	} else {
		v = &o.Value
	}
	return v
}

// ProfileBody is a profile, as the API sends it.
//
//line controller.ego:165
type ProfileBody struct {
	Profile Profile `json:"profile"`
}

type ProfileInput struct {
	Username string `path:"username"`
}

func (u *Users) Profile(ctx context.Context, in ProfileInput) (_ ProfileBody, err error) {
	ctx, span := trace.Start(ctx, "users.Users.Profile")
	defer trace.End(span, &err)
	return u.profile(ctx, in.Username, nil)
}

//line controller.ego:177
func (u *Users) Follow(ctx context.Context, in ProfileInput) (_ ProfileBody, err error) {
	ctx, span := trace.Start(ctx, "users.Users.Follow")
	defer trace.End(span, &err)
	follow := true
	return u.profile(ctx, in.Username, &follow)
}

//line controller.ego:182
func (u *Users) Unfollow(ctx context.Context, in ProfileInput) (_ ProfileBody, err error) {
	ctx, span := trace.Start(ctx, "users.Users.Unfollow")
	defer trace.End(span, &err)
	follow := false
	return u.profile(ctx, in.Username, &follow)
}

// profile returns the profile of the user with the username, as the viewer
// sees it, after following or unfollowing them if follow isn't nil.
//
//line controller.ego:189
func (u *Users) profile(ctx context.Context, username string, follow *bool) (_ ProfileBody, err error) {
	ctx, span := trace.Start(ctx, "users.Users.profile")
	defer trace.End(span, &err)
//line controller.ego:190
	user, ok, err := u.store.ByUsername(ctx, username)
	if err != nil {
		return ProfileBody{}, Unavailable{Cause: err}
	}
//line controller.ego:191
	if !ok {
		return ProfileBody{}, NoProfile{Username: username}
	}
	viewer := Viewer(ctx)
	if follow != nil {
		if err := u.store.Follow(ctx, viewer, user.ID, *follow); err != nil {
			return ProfileBody{}, Unavailable{Cause: err}
		}
	}
//line controller.ego:198
	following, err := u.store.Follows(ctx, viewer, user.ID)
	if err != nil {
		return ProfileBody{}, Unavailable{Cause: err}
	}
//line controller.ego:199
	return ProfileBody{Profile{Username: user.Username, Bio: user.Bio, Image: user.Image, Following: following}}, nil
}
