// Code generated by ego generate from login_test.ego. DO NOT EDIT.

package users_test

import (
	"testing"
	"testing/synctest"
	"time"

	"github.com/goncini/goncini/webtest"

	"github.com/goncini/goncini/examples/realworld/app"
	"github.com/goncini/goncini/examples/realworld/config"
)

// TestLoginThrottling checks that an email gets 5 logins a minute from an
// address, and that a successful one gives them back.
//
//line login_test.ego:16
func TestLoginThrottling(t *testing.T) {
	synctest.Test(t, func(t *testing.T) {
		a := webtest.Boot(t, config.Load, app.Build)
		webtest.Run(t, a, "db:migrate")
		c := webtest.NewClient(t, a)
		c.Post("/api/users", `{"user":{"username":"ann","email":"ann@example.com","password":"right password"}}`).Status(201)
		wrong := `{"user":{"email":"ann@example.com","password":"wrong"}}`
		right := `{"user":{"email":"ann@example.com","password":"right password"}}`
		for range 4 {
			c.Post("/api/users/login", wrong).Status(401)
		}
		c.Post("/api/users/login", right).Status(200)
		for range 5 {
			c.Post("/api/users/login", wrong).Status(401)
		}
		c.Post("/api/users/login", right).Status(429).HasHeader("Retry-After", "72").Contains(`"credentials":["too many failed attempts"]`)
		c.Post("/api/users/login", `{"user":{"email":"bob@example.com","password":"wrong"}}`).Status(401)
		time.Sleep(time.Minute)
		c.Post("/api/users/login", wrong).Status(429)
		time.Sleep(time.Minute)
		c.Post("/api/users/login", right).Status(200)
	})
}
