// Code generated by ego generate from store.ego. DO NOT EDIT.

package users

import (
	"context"
	"fmt"

	"github.com/goncini/goncini/db"

	"github.com/effect-go/effect-go/trace"
)

// Store keeps the users and who follows whom.
//
//line store.ego:10
type Store struct {
	sql *db.SQL
}

func NewStore(s *db.SQL) *Store {
	return &Store{sql: s}
}

const columns = "id, username, email, password_hash, bio, image"

// ByID returns the user with the ID, and reports whether there is one: the
// firewall's Load.
func (s *Store) ByID(ctx context.Context, id string) (_ *User, _ bool, err error) {
	ctx, span := trace.Start(ctx, "users.Store.ByID")
	defer trace.End(span, &err)
	return db.One(ctx, s.sql.Conn(ctx), scanUser, "SELECT "+columns+" FROM users WHERE id = ?", id)
}

// ByEmail returns the user with the email, and reports whether there is one.
//
//line store.ego:27
func (s *Store) ByEmail(ctx context.Context, email string) (_ *User, _ bool, err error) {
	ctx, span := trace.Start(ctx, "users.Store.ByEmail")
	defer trace.End(span, &err)
	return db.One(ctx, s.sql.Conn(ctx), scanUser, "SELECT "+columns+" FROM users WHERE email = ?", email)
}

// ByUsername returns the user with the username, and reports whether there
// is one.
//
//line store.ego:33
func (s *Store) ByUsername(ctx context.Context, username string) (_ *User, _ bool, err error) {
	ctx, span := trace.Start(ctx, "users.Store.ByUsername")
	defer trace.End(span, &err)
	return db.One(ctx, s.sql.Conn(ctx), scanUser, "SELECT "+columns+" FROM users WHERE username = ?", username)
}

// scanUser reads the columns of a user.
//
//line store.ego:38
func scanUser(row db.Scanner) (*User, error) {
	var u User
	err := row.Scan(&u.ID, &u.Username, &u.Email, &u.PasswordHash, &u.Bio, &u.Image)
	return &u, err
}

// Save inserts u if its ID is 0, or else updates it, unless another user
// has its username or email: then it returns which of them, and changes
// nothing.
func (s *Store) Save(ctx context.Context, u *User) (taken string, err error) {
	ctx, span := trace.Start(ctx, "users.Store.Save")
	defer trace.End(span, &err)
//line store.ego:48
	if err2 := s.sql.InTx(ctx, func(ctx context.Context) error {
		for _, field := range []string{"username", "email"} {
			var value string
			if field == "username" {
				value = u.Username
			} else {
				value = u.Email
			}
//line store.ego:51
			n, err := db.Value[int](ctx, s.sql.Conn(ctx), "SELECT count(*) FROM users WHERE "+field+" = ? AND id != ?", value, u.ID)
			if err != nil {
				return fmt.Errorf("db.Value: %w", err)
			}
//line store.ego:52
			if n > 0 {
				taken = field
				return nil
			}
		}
		if u.ID != 0 {
			if _, err2 := s.sql.Conn(ctx).ExecContext(ctx, "UPDATE users SET username = ?, email = ?, password_hash = ?, bio = ?, image = ? WHERE id = ?",
				u.Username, u.Email, u.PasswordHash, u.Bio, u.Image, u.ID); err2 != nil {
				return fmt.Errorf("Conn.ExecContext: %w", err2)
			}
//line store.ego:60
			return nil
		}
		res, err3 := s.sql.Conn(ctx).ExecContext(ctx, "INSERT INTO users (username, email, password_hash, bio, image) VALUES (?, ?, ?, ?, ?)",
			u.Username, u.Email, u.PasswordHash, u.Bio, u.Image)
		if err3 != nil {
			return fmt.Errorf("Conn.ExecContext: %w", err3)
		}
//line store.ego:64
		v, err4 := res.LastInsertId()
		if err4 != nil {
			return fmt.Errorf("res.LastInsertId: %w", err4)
		}
		u.ID = v
//line store.ego:65
		return nil
	}); err2 != nil {
		return "", err2
	}
//line store.ego:67
	return taken, nil
}

// Follow makes follower follow followed, or stop following them.
func (s *Store) Follow(ctx context.Context, follower, followed int64, follow bool) (err error) {
	ctx, span := trace.Start(ctx, "users.Store.Follow")
	defer trace.End(span, &err)
//line store.ego:72
	var query string
	if follow {
		query = "INSERT OR IGNORE INTO follows (follower_id, followed_id) VALUES (?, ?)"
	} else {
		query = "DELETE FROM follows WHERE follower_id = ? AND followed_id = ?"
	}
//line store.ego:73
	if _, err := s.sql.Conn(ctx).ExecContext(ctx, query, follower, followed); err != nil {
		return fmt.Errorf("Conn.ExecContext: %w", err)
	}
//line store.ego:74
	return nil
}

// Follows reports whether follower follows followed.
func (s *Store) Follows(ctx context.Context, follower, followed int64) (_ bool, err error) {
	ctx, span := trace.Start(ctx, "users.Store.Follows")
	defer trace.End(span, &err)
	return db.Value[bool](ctx, s.sql.Conn(ctx), "SELECT EXISTS (SELECT 1 FROM follows WHERE follower_id = ? AND followed_id = ?)", follower, followed)
}
