// Code generated by ego generate from users.ego. DO NOT EDIT.

// Package users is the users feature: registration, login, the current
// user, and profiles with their followers.
package users

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/goncini/goncini/httpkernel"
	"github.com/goncini/goncini/ratelimit"
	"github.com/goncini/goncini/security"

	"github.com/goncini/goncini/examples/realworld/conduit"
)

// User is a user, as stored.
//
//line users.ego:18
type User struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
	Bio          *string
	Image        *string
}

// Profile is a user as others see them.
type Profile struct {
	Username  string  `json:"username"`
	Bio       *string `json:"bio"`
	Image     *string `json:"image"`
	Following bool    `json:"following"`
}

// UserError is everything the users endpoints fail with.
type UserError interface {
	error
	isUserError()
}

// Taken means that another user has the username or email: Field.
type Taken struct{ Field string }

func (Taken) isUserError() {}

func (e Taken) Error() string { return fmt.Sprintf("%v has already been taken", e.Field) }

// As lets pointers to Taken match as Taken.
func (e Taken) As(target any) bool {
	if t, ok := target.(*Taken); ok {
		*t = e
		return true
	}
	return false
}

// BadCredentials means that no user has the email and password.
type BadCredentials struct{}

func (BadCredentials) isUserError() {}

func (e BadCredentials) Error() string { return "invalid credentials" }

// As lets pointers to BadCredentials match as BadCredentials.
func (e BadCredentials) As(target any) bool {
	if t, ok := target.(*BadCredentials); ok {
		*t = e
		return true
	}
	return false
}

// TooManyLogins means that the email had too many failed logins from
// the client's address: it may try again after RetryAfter.
type TooManyLogins struct{ RetryAfter time.Duration }

func (TooManyLogins) isUserError() {}

func (e TooManyLogins) Error() string { return "too many failed logins" }

// As lets pointers to TooManyLogins match as TooManyLogins.
func (e TooManyLogins) As(target any) bool {
	if t, ok := target.(*TooManyLogins); ok {
		*t = e
		return true
	}
	return false
}

// NoProfile means that no user has the username.
type NoProfile struct{ Username string }

func (NoProfile) isUserError() {}

func (e NoProfile) Error() string { return fmt.Sprintf("no user %v", e.Username) }

// As lets pointers to NoProfile match as NoProfile.
func (e NoProfile) As(target any) bool {
	if t, ok := target.(*NoProfile); ok {
		*t = e
		return true
	}
	return false
}

// Unavailable means that the store failed.
type Unavailable struct{ Cause error }

func (Unavailable) isUserError() {}

func (e Unavailable) Error() string { return "the users are unavailable" }

func (e Unavailable) Unwrap() error { return e.Cause }

// As lets pointers to Unavailable match as Unavailable.
func (e Unavailable) As(target any) bool {
	if t, ok := target.(*Unavailable); ok {
		*t = e
		return true
	}
	return false
}

// Problem says what each UserError looks like over HTTP.
//
//line users.ego:51
func Problem(err error) httpkernel.Problem {
	var v httpkernel.Problem
	if err == nil {
		v = httpkernel.Problem{}
	} else if e, ok := errors.AsType[Taken](err); ok {
		v = conduit.Problem(http.StatusConflict, e.Field, "has already been taken")
	} else if _, ok := errors.AsType[BadCredentials](err); ok {
		v = conduit.Problem(http.StatusUnauthorized, "credentials", "invalid")
	} else if e, ok := errors.AsType[TooManyLogins](err); ok {
		v = tooManyLogins(e)
	} else if _, ok := errors.AsType[NoProfile](err); ok {
		v = conduit.Problem(http.StatusNotFound, "profile", "not found")
	} else if _, ok := errors.AsType[Unavailable](err); ok {
		v = httpkernel.Problem{Status: http.StatusServiceUnavailable}
	} else {
		panic(err)
	}
	return v
}

// tooManyLogins is a 429, with ratelimit's Retry-After header.
//
//line users.ego:63
func tooManyLogins(e TooManyLogins) httpkernel.Problem {
	p := conduit.Problem(http.StatusTooManyRequests, "credentials", "too many failed attempts")
	p.Header = ratelimit.Exceeded{RetryAfter: e.RetryAfter}.Problem().Header
	return p
}

// Problems is what a kernel registers to answer UserErrors.
var Problems = httpkernel.Map[UserError](Problem)

// Current returns the user that the request ctx belongs to was
// authenticated as. Its routes are behind security.Required, so there is
// one.
func Current(ctx context.Context) *User {
	u, err := security.CurrentUser[*User](ctx)
	if err != nil {
		panic(err)
	}
//line users.ego:77
	return u
}

// Viewer returns the ID of the user the request ctx belongs to was
// authenticated as, or 0 for an anonymous request.
func Viewer(ctx context.Context) int64 {
	u, _ := security.User[*User](ctx)
	var v int64
	if u != nil {
		v = u.ID
	}
	return v
}
