// Code generated by ego generate from welcome_test.ego. DO NOT EDIT.

package users_test

import (
	"bytes"
	"io"
	stdmime "mime"
	"mime/multipart"
	"mime/quotedprintable"
	"net/mail"
	"strings"
	"testing"

	"github.com/goncini/goncini/mailer/mailertest"
	"github.com/goncini/goncini/webtest"

	"github.com/goncini/goncini/examples/realworld/app"
	"github.com/goncini/goncini/examples/realworld/config"
)

// TestWelcomeEmail is M4's third gate: registering sends a welcome email
// out of the request, a message that a worker sends to an SMTP server,
// which gets a multipart email with its text and HTML intact.
//
//line welcome_test.ego:23
func TestWelcomeEmail(t *testing.T) {
	smtp := mailertest.NewServer(t)
	t.Setenv("MAILER_DSN", smtp.DSN())
	a := webtest.Boot(t, config.Load, app.Build)
	webtest.Run(t, a, "db:migrate")
	c := webtest.NewClient(t, a)
	c.Post("/api/users", `{"user":{"username":"zoé","email":"zoe@example.com","password":"a password"}}`).Status(201)
	if len(smtp.Messages()) != 0 {
		t.Fatal("sent in the request")
	}
	webtest.Run(t, a, "messenger:consume", "-drain")
	got := smtp.Messages()
	if len(got) != 1 || got[0].From != "hello@conduit.example" || got[0].To[0] != "zoe@example.com" {
		t.Fatalf("received %+v", got)
	}
	msg, err := mail.ReadMessage(bytes.NewReader(got[0].Data))
	if err != nil {
		panic(err)
	}
//line welcome_test.ego:39
	subject, err := new(stdmime.WordDecoder).DecodeHeader(msg.Header.Get("Subject"))
	if err != nil {
		panic(err)
	}
//line welcome_test.ego:40
	if subject != "Welcome to Conduit, zoé" {
		t.Errorf("subject %q", subject)
	}
	_, params, err := stdmime.ParseMediaType(msg.Header.Get("Content-Type"))
	if err != nil {
		panic(err)
	}
//line welcome_test.ego:44
	r := multipart.NewReader(msg.Body, params["boundary"])
	bodies := map[string]string{}
	for {
		p, err := r.NextRawPart()
		if err == io.EOF {
			break
		}
		media, _, err2 := stdmime.ParseMediaType(p.Header.Get("Content-Type"))
		if err2 != nil {
			panic(err2)
		}
//line welcome_test.ego:52
		b, err3 := io.ReadAll(quotedprintable.NewReader(p))
		if err3 != nil {
			panic(err3)
		}
//line welcome_test.ego:53
		bodies[media] = string(b)
	}
	text := strings.ReplaceAll(bodies["text/plain"], "\r\n", "\n") // SMTP's line endings
	if !strings.HasPrefix(text, "Welcome to Conduit, zoé.\n\nFollow") || !strings.Contains(bodies["text/html"], "<b>Conduit</b>, zoé.") {
		t.Errorf("bodies %q", bodies)
	}
}
