// Code generated by ego generate from access.ego. DO NOT EDIT.

package security

import (
	"context"
	"fmt"
	"net/http"
	"slices"
	"strconv"
	"strings"

	"github.com/goncini/goncini/httpkernel"
	"github.com/goncini/goncini/openapi"
)

// AccessError is everything authorization fails with.
//
//line access.ego:14
type AccessError interface {
	error
	isAccessError()
}

// AccessDenied means that the user may not do Attribute: a 403.
type AccessDenied struct{ Attribute string }

func (AccessDenied) isAccessError() {}

func (e AccessDenied) Error() string { return fmt.Sprintf("access denied: %v", e.Attribute) }

// As lets pointers to AccessDenied match as AccessDenied.
func (e AccessDenied) As(target any) bool {
	if t, ok := target.(*AccessDenied); ok {
		*t = e
		return true
	}
	return false
}

// Problem is a 403.
//
//line access.ego:20
func (e AccessDenied) Problem() httpkernel.Problem {
	return httpkernel.Problem{Status: http.StatusForbidden, Detail: "access denied"}
}

// Vote is what a voter says of an attribute and a subject.
type Vote int

const (
	// Abstain means that the voter doesn't decide on them.
	Abstain Vote = iota
	Grant
	Deny
)

func (v Vote) String() string {
	switch v {
	case Abstain:
		return "Abstain"
	case Grant:
		return "Grant"
	case Deny:
		return "Deny"
	}
	return "Vote(" + strconv.Itoa(int(v)) + ")"
}

// Voter decides whether the user of a request may do something, an
// attribute such as "edit", to a subject, such as an article, as Symfony's
// voters do. It finds the user in ctx, with User.
//
//line access.ego:35
type Voter interface {
	Vote(ctx context.Context, attribute string, subject any) Vote
}

// On returns a voter of the subjects of type S, which abstains on the
// others:
//
//	security.On((ctx context.Context, attribute string, art Article) => …)
func On[S any](vote func(ctx context.Context, attribute string, subject S) Vote) Voter {
	return typedVoter[S](vote)
}

type typedVoter[S any] func(ctx context.Context, attribute string, subject S) Vote

func (v typedVoter[S]) Vote(ctx context.Context, attribute string, subject any) Vote {
	if s, ok := subject.(S); ok {
		return v(ctx, attribute, s)
	}
	return Abstain
}

// Strategy is how votes make a decision.
type Strategy int

const (
	// Affirmative grants access when a voter grants it: the default.
	Affirmative Strategy = iota
	// Consensus grants access when more voters grant it than deny it.
	Consensus
	// Unanimous grants access when a voter grants it and none denies it.
	Unanimous
)

func (v Strategy) String() string {
	switch v {
	case Affirmative:
		return "Affirmative"
	case Consensus:
		return "Consensus"
	case Unanimous:
		return "Unanimous"
	}
	return "Strategy(" + strconv.Itoa(int(v)) + ")"
}

// Authenticated is the attribute that every authenticated user has.
//
//line access.ego:67
const Authenticated = "IS_AUTHENTICATED"

// RoleHolder is a user type that has roles, such as "ROLE_ADMIN".
type RoleHolder interface {
	Roles() []string
}

// Access decides what users may do, from voters' votes, as Symfony's
// AccessDecisionManager does. Besides its Voters, it grants Authenticated
// to authenticated users, and the attributes that start with ROLE_ to the
// users that have those roles, directly or through Hierarchy.
type Access struct {
	Voters   []Voter
	Strategy Strategy
	// Hierarchy gives roles the roles they include: ROLE_ADMIN includes
	// ROLE_MODERATOR.
	Hierarchy map[string][]string
	// AllowIfAllAbstain grants access when every voter abstains; access is
	// denied then by default.
	AllowIfAllAbstain bool
}

// NewAccess returns the access of the voters, with the role hierarchy of
// c.
func NewAccess(c Config, voters []Voter) *Access {
	return &Access{Voters: voters, Hierarchy: c.RoleHierarchy}
}

// IsGranted reports whether the user of ctx may do attribute to subject;
// subject is nil for an attribute that has none, such as a role.
func (a *Access) IsGranted(ctx context.Context, attribute string, subject any) bool {
	grants, denials := 0, 0
	count := func(v Vote) {
		switch v {
		case Grant:
//line access.ego:101
			grants++
		case Deny:
//line access.ego:102
			denials++
		case Abstain:

		}
	}
//line access.ego:107
	count(a.builtIn(ctx, attribute))
	for _, v := range a.Voters {
		count(v.Vote(ctx, attribute, subject))
	}
	if grants == 0 && denials == 0 {
		return a.AllowIfAllAbstain
	}
	var v2 bool
	switch a.Strategy {
	case Affirmative:
		v2 = grants > 0
	case Consensus:
		v2 = grants > denials
	case Unanimous:
		v2 = grants > 0 && denials == 0
	default:
		panic(a.Strategy)
	}
	return v2
}

// Check returns nil if the user of ctx may do attribute to subject, or
// else AccessDenied, a 403, or Unauthenticated, a 401, for an anonymous
// request, which a user might be allowed: Symfony's
// denyAccessUnlessGranted.
//
//line access.ego:125
func (a *Access) Check(ctx context.Context, attribute string, subject any) error {
	if a.IsGranted(ctx, attribute, subject) {
		return nil
	}
	st, ok := ctx.Value(stateKey{}).(*state)
	if !ok {
		st = nil
	}
//line access.ego:130
	var v any
	if st != nil {
		v = st.user
	}
	if v == nil {
//line access.ego:131
		var v2 string
		if st != nil {
			v2 = st.scheme
		}
		return Unauthenticated{Scheme: v2}
	}
//line access.ego:133
	return AccessDenied{Attribute: attribute}
}

// builtIn is the vote on Authenticated and roles.
func (a *Access) builtIn(ctx context.Context, attribute string) Vote {
	st, ok2 := ctx.Value(stateKey{}).(*state)
	if !ok2 {
		st = nil
	}
//line access.ego:139
	var user any
	if st != nil {
		user = st.user
	}
//line access.ego:140
	switch {
	case attribute == Authenticated:
		var v Vote
		if user != nil {
			v = Grant
		} else {
			v = Deny
		}
		return v
//line access.ego:143
	case !strings.HasPrefix(attribute, "ROLE_"):
		return Abstain
	}
	holder, ok := user.(RoleHolder)
	if !ok {
		return Deny
	}
	var v2 Vote
	if slices.Contains(a.reachable(holder.Roles()), attribute) {
		v2 = Grant
	} else {
		v2 = Deny
	}
	return v2
}

// reachable returns the roles and those they include, through Hierarchy.
//
//line access.ego:154
func (a *Access) reachable(roles []string) []string {
	out := slices.Clone(roles)
	for i := 0; i < len(out); i++ {
		for _, r := range a.Hierarchy[out[i]] {
			if !slices.Contains(out, r) {
				out = append(out, r)
			}
		}
	}
	return out
}

// Require returns middleware that lets through the requests whose user
// may do attribute, without a subject, such as a role: the others get
// Check's 401 or 403. It goes on a route, or a group of them, behind a
// firewall:
//
//	admin := r.With(access.Require("ROLE_ADMIN"))
func (a *Access) Require(attribute string) func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler { return &requiring{a, attribute, next} }
}

// requiring is a handler that requires an attribute.
type requiring struct {
	a         *Access
	attribute string
	next      http.Handler
}

func (h *requiring) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if err := h.a.Check(r.Context(), h.attribute, nil); err != nil {
		httpkernel.WriteError(w, r, err)
		return
	}
	h.next.ServeHTTP(w, r)
}

// DescribeOperation says that the operation needs a user, as Required
// does, and answers 403 to the others.
func (h *requiring) DescribeOperation(op *openapi.Op) {
	required{}.DescribeOperation(op)
	op.Errors = append(op.Errors, AccessDenied{Attribute: h.attribute})
}
