// Code generated by ego generate from firewall.ego. DO NOT EDIT.

package security

import (
	"cmp"
	"context"
	"errors"
	"fmt"
	"net/http"
	"slices"
	"strings"

	"github.com/goncini/goncini/httpkernel"
	"github.com/goncini/goncini/openapi"
)

// AuthError is everything authentication fails with. Each case is a 401
// problem with a WWW-Authenticate header, for the scheme of the firewall.
//
//line firewall.ego:17
type AuthError interface {
	error
	isAuthError()
}

// Unauthenticated means that the request needs a user, and has no
// credentials.
type Unauthenticated struct{ Scheme string }

func (Unauthenticated) isAuthError() {}

func (e Unauthenticated) Error() string { return "authentication is required" }

// As lets pointers to Unauthenticated match as Unauthenticated.
func (e Unauthenticated) As(target any) bool {
	if t, ok := target.(*Unauthenticated); ok {
		*t = e
		return true
	}
	return false
}

// InvalidToken means that the request's token can't be trusted, for
// Reason.
type InvalidToken struct {
	Scheme string
	Reason string
}

func (InvalidToken) isAuthError() {}

func (e InvalidToken) Error() string { return fmt.Sprintf("invalid token: %v", e.Reason) }

// As lets pointers to InvalidToken match as InvalidToken.
func (e InvalidToken) As(target any) bool {
	if t, ok := target.(*InvalidToken); ok {
		*t = e
		return true
	}
	return false
}

// Problem is the response to e.
//
//line firewall.ego:30
func (e Unauthenticated) Problem() httpkernel.Problem {
	return httpkernel.Problem{
		Status: http.StatusUnauthorized,
		Detail: e.Error(),
		Header: challenge(e.Scheme, ""),
	}
}

// Problem is the response to e.
func (e InvalidToken) Problem() httpkernel.Problem {
	return httpkernel.Problem{
		Status: http.StatusUnauthorized,
		Detail: e.Error(),
		Header: challenge(e.Scheme, ` error="invalid_token"`),
	}
}

// challenge is the WWW-Authenticate header of a 401 for the scheme, as RFC
// 6750 writes it.
func challenge(scheme, params string) http.Header {
	h := http.Header{}
	h.Set("WWW-Authenticate", cmp.Or(scheme, "Bearer")+params)
	return h
}

// Firewall authenticates requests that have a token in their
// Authorization header, and loads the user it names with Load. Requests
// without one go through as anonymous; those whose token is invalid, or
// names a user that doesn't exist, get a 401.
//
// U is the app's type of users. An app provides its firewall:
//
//	func firewall(c security.Config, tokens *security.Tokens, users *users.Store) *security.Firewall[*users.User] {
//		return &security.Firewall[*users.User]{Config: c, Tokens: tokens, Load: users.ByID}
//	}
//
// and puts its Middleware in the kernel's, with a []httpkernel.Middleware
// provider passed to layer.Build.
type Firewall[U any] struct {
	// Config gives the scheme of the Authorization header.
	Config Config
	// Tokens verifies the tokens.
	Tokens *Tokens
	// Load returns the user that a token's subject identifies, and reports
	// whether there is one. Its errors are the server's: 500s.
	Load func(ctx context.Context, subject string) (U, bool, error)
}

// state is what a firewall found out about a request.
type state struct {
	scheme string
	user   any // nil for an anonymous request
}

type stateKey struct{}

// Middleware authenticates requests, as Firewall says.
func (f *Firewall[U]) Middleware(next http.Handler) http.Handler {
	return &firewalled[U]{f: f, scheme: cmp.Or(f.Config.Scheme, "Bearer"), next: next}
}

// firewalled is a handler behind a firewall.
type firewalled[U any] struct {
	f      *Firewall[U]
	scheme string
	next   http.Handler
}

func (h *firewalled[U]) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	st := &state{scheme: h.scheme}
	header := r.Header.Get("Authorization")
	if header != "" {
		user, err := h.f.authenticate(r.Context(), h.scheme, header)
		if err != nil {
			httpkernel.WriteError(w, r, err)
			return
		}
		st.user = user
	}
	h.next.ServeHTTP(w, r.WithContext(context.WithValue(r.Context(), stateKey{}, st)))
}

// DescribeOperation says that the operation takes a token, which it may
// do without, and answers 401 to an invalid one. The scheme is named as
// the Authorization header's: Bearer, an HTTP scheme, or another, such as
// Token, as an API key in the header.
func (h *firewalled[U]) DescribeOperation(op *openapi.Op) {
	scheme := &openapi.SecurityScheme{Type: "http", Scheme: "bearer", BearerFormat: "JWT"}
	if !strings.EqualFold(h.scheme, "Bearer") {
		scheme = &openapi.SecurityScheme{
			Type:        "apiKey",
			In:          "header",
			Name:        "Authorization",
			Description: fmt.Sprintf("The Authorization header, with the %s scheme: Authorization: %s eyJhbGciOiJIUzI1NiJ9…", h.scheme, h.scheme),
		}
	}
	op.SecurityScheme(h.scheme, scheme)
	op.Security = append(op.Security, openapi.SecurityRequirement{}, openapi.SecurityRequirement{h.scheme: {}})
	op.Errors = append(op.Errors, InvalidToken{Scheme: h.scheme, Reason: "it has expired"})
}

// authenticate returns the user of an Authorization header.
func (f *Firewall[U]) authenticate(ctx context.Context, scheme, header string) (U, error) {
	var zero U
	got, token, _ := strings.Cut(header, " ")
	if !strings.EqualFold(got, scheme) || token == "" {
		return zero, InvalidToken{Scheme: scheme, Reason: fmt.Sprintf("the Authorization header isn't %s and a token", scheme)}
	}
	subject, err := f.Tokens.Verify(strings.TrimSpace(token))
	if e, ok := errors.AsType[InvalidToken](err); ok {
		e.Scheme = scheme
		return zero, e
	}
	if err != nil {
		return *new(U), err
	}
//line firewall.ego:144
	user, ok, err2 := f.Load(ctx, subject)
	if err2 != nil {
		return *new(U), err2
	}
//line firewall.ego:145
	if !ok {
		return zero, InvalidToken{Scheme: scheme, Reason: "its user doesn't exist"}
	}
	return user, nil
}

// User returns the user that the request ctx belongs to was authenticated
// as, and reports whether it was: false for an anonymous request, or a
// request no firewall saw.
func User[U any](ctx context.Context) (U, bool) {
	st, _ := ctx.Value(stateKey{}).(*state)
	var v any
	if st != nil {
		v = st.user
	}
	u, ok := v.(U)
//line firewall.ego:157
	return u, ok
}

// CurrentUser returns the user that the request ctx belongs to was
// authenticated as, or fails with Unauthenticated, a 401.
func CurrentUser[U any](ctx context.Context) (U, error) {
	if u, ok := User[U](ctx); ok {
		return u, nil
	}
	var zero U
	st, _ := ctx.Value(stateKey{}).(*state)
	var v string
	if st != nil {
		v = st.scheme
	}
	return zero, Unauthenticated{Scheme: v}
}

// Required answers 401 to the requests that aren't authenticated: those
// without a token. It goes on the routes that need a user, behind a
// firewall in the kernel's middleware:
//
//	r.With(security.Required).Post("/articles", httpkernel.Endpoint(a.Create))
//
//line firewall.ego:176
func Required(next http.Handler) http.Handler {
	return required{next}
}

// required is a handler that needs a user.
type required struct {
	next http.Handler
}

func (h required) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	st, _ := r.Context().Value(stateKey{}).(*state)
	var v any
	if st != nil {
		v = st.user
	}
	if v == nil {
//line firewall.ego:188
		var v2 string
		if st != nil {
			v2 = st.scheme
		}
		httpkernel.WriteError(w, r, Unauthenticated{Scheme: v2})
//line firewall.ego:189
		return
	}
	h.next.ServeHTTP(w, r)
}

// DescribeOperation says that the operation needs a token, and answers 401
// without one: it drops the empty requirement that a firewall adds.
func (required) DescribeOperation(op *openapi.Op) {
	op.Security = slices.DeleteFunc(op.Security, func(r openapi.SecurityRequirement) bool { return len(r) == 0 })
	var scheme string
	if len(op.Security) > 0 {
		for name := range op.Security[0] {
			scheme = name
		}
	}
	op.Errors = append(op.Errors, Unauthenticated{Scheme: scheme})
}
