// Code generated by ego generate from security_test.ego. DO NOT EDIT.

package security_test

import (
	"context"
	"errors"
	"log/slog"
	"strings"
	"testing"
	"testing/synctest"
	"time"

	"golang.org/x/crypto/bcrypt"

	"github.com/goncini/goncini/httpkernel"
	"github.com/goncini/goncini/routing"
	"github.com/goncini/goncini/security"
	"github.com/goncini/goncini/webtest"
)

//line security_test.ego:20
const secret = "a secret of at least thirty-two bytes"

func TestHasher(t *testing.T) {
	var h security.Hasher
	hash, err := h.Hash("correct horse")
	if err != nil {
		panic(err)
	}
//line security_test.ego:25
	if !strings.HasPrefix(hash, "$argon2id$v=19$m=19456,t=2,p=1$") {
		t.Errorf("hash %s", hash)
	}
	other, err := h.Hash("correct horse")
	if err != nil {
		panic(err)
	}
//line security_test.ego:29
	if other == hash {
		t.Error("two hashes of a password are the same: no salt")
	}
	legacyHash, err := bcrypt.GenerateFromPassword([]byte("correct horse"), bcrypt.MinCost)
	if err != nil {
		panic(err)
	}
//line security_test.ego:33
	legacy := string(legacyHash)
	for _, hash := range []string{hash, legacy} {
		right, err := h.Verify(hash, "correct horse")
		if err != nil {
			panic(err)
		}
//line security_test.ego:36
		wrong, err := h.Verify(hash, "wrong horse")
		if err != nil {
			panic(err)
		}
//line security_test.ego:37
		if !right || wrong {
			t.Errorf("Verify(%s): %v with the password, %v without", hash, right, wrong)
		}
	}
	if h.NeedsRehash(hash) || !h.NeedsRehash(legacy) || !(security.Hasher{Time: 3}).NeedsRehash(hash) {
		t.Error("NeedsRehash is wrong")
	}
	for _, bad := range []string{"", "plain", "$argon2id$v=18$m=1,t=1,p=1$c2FsdA$a2V5", "$argon2id$v=19$m=x$c2FsdA$a2V5"} {
		if _, err := h.Verify(bad, "x"); err == nil {
			t.Errorf("Verify(%q) didn't fail", bad)
		}
	}
}

func TestTokens(t *testing.T) {
	if _, err := security.NewTokens(security.Config{Secret: "short"}); err == nil {
		t.Error("a short secret was accepted")
	}
	tokens, err := security.NewTokens(security.Config{Secret: secret, Issuer: "api"})
	if err != nil {
		panic(err)
	}
//line security_test.ego:56
	token, err := tokens.Issue("42")
	if err != nil {
		panic(err)
	}
//line security_test.ego:57
	sub, err := tokens.Verify(token)
	if err != nil {
		panic(err)
	}
//line security_test.ego:58
	if sub != "42" {
		t.Errorf("subject %q", sub)
	}
	others, err := security.NewTokens(security.Config{Secret: strings.ToUpper(secret), Issuer: "api"})
	if err != nil {
		panic(err)
	}
//line security_test.ego:62
	otherIssuer, err := security.NewTokens(security.Config{Secret: secret, Issuer: "other"})
	if err != nil {
		panic(err)
	}
//line security_test.ego:63
	foreign, err := others.Issue("42")
	if err != nil {
		panic(err)
	}
//line security_test.ego:64
	wrongIssuer, err := otherIssuer.Issue("42")
	if err != nil {
		panic(err)
	}
//line security_test.ego:65
	unsigned := "eyJhbGciOiJub25lIn0.eyJzdWIiOiI0MiJ9."
	for name, bad := range map[string]string{"foreign": foreign, "wrong issuer": wrongIssuer, "unsigned": unsigned, "garbage": "x.y.z", "tampered": token[:len(token)-2] + "xx"} {
		_, err := tokens.Verify(bad)
		if e, ok := errors.AsType[security.InvalidToken](err); !ok || e.Reason != "it isn't one of the API's" {
			t.Errorf("%s: %v", name, err)
		}
	}
}

func TestTokensExpire(t *testing.T) {
	synctest.Test(t, func(t *testing.T) {
		tokens, err := security.NewTokens(security.Config{Secret: secret, TTL: time.Hour})
		if err != nil {
			panic(err)
		}
		token, err := tokens.Issue("42")
		if err != nil {
			panic(err)
		}
		time.Sleep(59 * time.Minute)
		if _, err := tokens.Verify(token); err != nil {
			panic(err)
		}
		time.Sleep(2 * time.Minute)
		if _, err := tokens.Verify(token); err == nil || err.Error() != "invalid token: it has expired" {
			t.Errorf("after the TTL: %v", err)
		}
	})
}

//line security_test.ego:87
type user struct{ Name string }

// api is an API with a public route and a route that needs a user, behind
// a firewall whose users are ann (1) and, when the store is down, nobody.
func api(t *testing.T) (*webtest.Client, *security.Tokens) {
	tokens, err := security.NewTokens(security.Config{Secret: secret})
	if err != nil {
		panic(err)
	}
//line security_test.ego:93
	fw := &security.Firewall[*user]{
		Config: security.Config{Scheme: "Token"},
		Tokens: tokens,
		Load: func(ctx context.Context, id string) (*user, bool, error) {
			switch id {
			case "1":
//line security_test.ego:98
				return &user{Name: "ann"}, true, nil
			case "down":
//line security_test.ego:99
				return nil, false, errors.New("the store is down")
			default:
//line security_test.ego:100
				return nil, false, nil
			}
		},
	}
	whoami := httpkernel.Endpoint(func(ctx context.Context, in struct{}) (string, error) {
		if u, ok := security.User[*user](ctx); ok {
			return u.Name, nil
		}
		return "anonymous", nil
	})
	me := httpkernel.Endpoint(func(ctx context.Context, in struct{}) (string, error) {
		u, err := security.CurrentUser[*user](ctx)
		if err != nil {
			return "", err
		}
//line security_test.ego:112
		return u.Name, nil
	})
	r := routing.New()
	r.Get("/whoami", whoami)
	r.With(security.Required).Get("/me", me)
	r.Get("/me-unguarded", me) // CurrentUser fails without Required
	k := &httpkernel.Kernel{Handler: r, Middleware: []httpkernel.Middleware{fw.Middleware}, Logger: slog.New(slog.DiscardHandler)}
	return webtest.NewClient(t, k), tokens
}

func TestFirewall(t *testing.T) {
	c, tokens := api(t)
	annToken, err := tokens.Issue("1")
	if err != nil {
		panic(err)
	}
//line security_test.ego:125
	nobodyToken, err := tokens.Issue("2")
	if err != nil {
		panic(err)
	}
//line security_test.ego:126
	downToken, err := tokens.Issue("down")
	if err != nil {
		panic(err)
	}
//line security_test.ego:127
	ann := c.WithHeader("Authorization", "Token "+annToken)

	c.Get("/whoami").Status(200).Contains(`"anonymous"`)
	ann.Get("/whoami").Status(200).Contains(`"ann"`)
	ann.Get("/me").Status(200).Contains(`"ann"`)
	c.Get("/me").Problem(401).HasDetail("authentication is required").Response().HasHeader("WWW-Authenticate", "Token")
	c.Get("/me-unguarded").Problem(401).HasDetail("authentication is required")

	invalid := `Token error="invalid_token"`
	for header, detail := range map[string]string{
		"Bearer " + annToken:   "invalid token: the Authorization header isn't Token and a token",
		"Token":                "invalid token: the Authorization header isn't Token and a token",
		"Token nope":           "invalid token: it isn't one of the API's",
		"Token " + nobodyToken: "invalid token: its user doesn't exist",
	} {
		// An invalid token is refused even on a public route.
		c.WithHeader("Authorization", header).Get("/whoami").Problem(401).HasDetail(detail).Response().HasHeader("WWW-Authenticate", invalid)
	}
	c.WithHeader("Authorization", "token "+annToken).Get("/whoami").Status(200) // schemes ignore case
	c.WithHeader("Authorization", "Token "+downToken).Get("/whoami").Problem(500)
}

func TestCurrentUserWithoutAFirewall(t *testing.T) {
	_, err := security.CurrentUser[*user](context.Background())
	p := httpkernel.ProblemFor(err)
	if p.Status != 401 || p.Header.Get("WWW-Authenticate") != "Bearer" {
		t.Errorf("problem %+v", p)
	}
	if _, ok := security.User[*user](context.Background()); ok {
		t.Error("a user without a firewall")
	}
}
