// Code generated by ego generate from token.ego. DO NOT EDIT.

package security

import (
	"cmp"
	"errors"
	"time"

	"github.com/golang-jwt/jwt/v5"
)

// Config configures tokens and the firewall.
//
//line token.ego:12
type Config struct {
	// Secret signs the tokens: at least 32 bytes, read with
	// env.Secret("APP_SECRET"). Changing it invalidates every token.
	Secret string
	// TTL is how long a token is valid; zero means 24 hours.
	TTL time.Duration
	// Issuer is written in the tokens and required of them; empty means
	// none.
	Issuer string
	// Scheme is the scheme of the Authorization header, as in
	// "Authorization: Bearer <token>"; empty means Bearer.
	Scheme string
}

// Tokens issues and verifies signed tokens, JWTs signed with HMAC-SHA256,
// that name a user.
type Tokens struct {
	secret []byte
	ttl    time.Duration
	issuer string
}

// NewTokens returns the tokens that c configures.
func NewTokens(c Config) (*Tokens, error) {
	if len(c.Secret) < 32 {
		return nil, errors.New("security: Config.Secret has fewer than 32 bytes")
	}
	return &Tokens{secret: []byte(c.Secret), ttl: cmp.Or(c.TTL, 24*time.Hour), issuer: c.Issuer}, nil
}

// Issue returns a token for the user that subject identifies, such as its
// ID, valid for the TTL.
func (t *Tokens) Issue(subject string) (string, error) {
	now := time.Now()
	claims := jwt.RegisteredClaims{
		Subject:   subject,
		Issuer:    t.issuer,
		IssuedAt:  jwt.NewNumericDate(now),
		ExpiresAt: jwt.NewNumericDate(now.Add(t.ttl)),
	}
	return jwt.NewWithClaims(jwt.SigningMethodHS256, claims).SignedString(t.secret)
}

// Verify returns the subject of token, if Tokens issued it and it hasn't
// expired. Its errors are InvalidToken cases, without a scheme.
func (t *Tokens) Verify(token string) (string, error) {
	opts := []jwt.ParserOption{jwt.WithValidMethods([]string{"HS256"}), jwt.WithExpirationRequired()}
	if t.issuer != "" {
		opts = append(opts, jwt.WithIssuer(t.issuer))
	}
	var claims jwt.RegisteredClaims
	_, err := jwt.ParseWithClaims(token, &claims, func(*jwt.Token) (any, error) { return t.secret, nil }, opts...)
	switch {
	case errors.Is(err, jwt.ErrTokenExpired):
		return "", InvalidToken{Reason: "it has expired"}
	case err != nil:
		return "", InvalidToken{Reason: "it isn't one of the API's"}
	case claims.Subject == "":
		return "", InvalidToken{Reason: "it names no user"}
	}
	return claims.Subject, nil
}
