// Code generated by ego generate from listing.ego. DO NOT EDIT.

// Package listing is what endpoints that list things share, as API
// Platform's pagination and order filter are: pages by offset, with links
// to the others, pages by cursor, and sorting by the fields a list allows.
//
//	type ListInput struct {
//		listing.Window                                  // ?limit=20&offset=40
//		Sort listing.Sort[ArticleOrder] `query:"sort" default:"-createdAt"`
//		Tag  string                     `query:"tag"`   // a filter: a typed parameter
//	}
//
//	effect (a *Articles) List(in ListInput) (listing.Page[Article], ArticleError) {
//		items, total := check a.store.List(in.Tag, in.Sort.SQL(), in.Limit, in.Offset) as Unavailable
//		return listing.Page[Article]{Items: items, Total: total, Window: in.Window}, nil
//	}
//
// Filters are typed parameters, such as tag above or
// `query:"createdAt[after]"` for a range, which the OpenAPI document
// describes like any other.
package listing

import (
	"encoding/base64"
	"encoding/json/v2"
	"errors"
	"net/http"
	"reflect"
	"regexp"
	"slices"
	"strconv"
	"strings"

	"github.com/goncini/goncini/httpkernel"
	"github.com/goncini/goncini/openapi"
)

// Window is where a page starts in a list, and its size: ?limit=20&offset=40.
//
//line listing.ego:37
type Window struct {
	Limit  int `query:"limit" default:"20" validate:"min=1,max=100"` // how many items, at most
	Offset int `query:"offset" validate:"min=0"`                     // how many items to skip
}

// Page is a page of a list, written as JSON with Link headers (RFC 8288) to
// the first, previous, next and last pages: the request's URL with other
// offsets.
type Page[T any] struct {
	Items []T `json:"items"`
	// Total is how many items the whole list has.
	Total int `json:"total"`
	// Window is where the page is, for its links.
	Window Window `json:"-"`
}

// Respond writes p, with its links.
func (p Page[T]) Respond(w http.ResponseWriter, r *http.Request) error {
	for _, link := range Links(r, p.Window, p.Total) {
		w.Header().Add("Link", link)
	}
	return httpkernel.WriteJSON(w, http.StatusOK, p)
}

// DescribeResponse says that a page is a 200 with a Page.
func (Page[T]) DescribeResponse() (int, reflect.Type) {
	return http.StatusOK, reflect.TypeFor[Page[T]]()
}

// Links returns the Link header values of the page at o of a list of total
// items: to the first page, the previous one if any, the next one if any,
// and the last, as r's URL with other offsets.
func Links(r *http.Request, o Window, total int) []string {
	if o.Limit <= 0 {
		return nil
	}
	// The path as the request wrote it, which can't start with //: that
	// would be another host's.
	path := "/" + strings.TrimLeft(r.URL.EscapedPath(), "/")
	link := func(offset int, rel string) string {
		q := r.URL.Query()
		q.Set("limit", strconv.Itoa(o.Limit))
		q.Set("offset", strconv.Itoa(offset))
		return "<" + path + "?" + q.Encode() + `>; rel="` + rel + `"`
	}
	last := max(0, (total-1)/o.Limit*o.Limit)
	links := []string{link(0, "first")}
	if o.Offset > 0 {
		links = append(links, link(min(max(0, o.Offset-o.Limit), last), "prev"))
	}
	if o.Offset < total-o.Limit { // o.Offset+o.Limit < total, without overflowing
		links = append(links, link(o.Offset+o.Limit, "next"))
	}
	return append(links, link(last, "last"))
}

// Cursor is where a page starts in a list sorted by keys that don't change,
// such as IDs: the keys of the previous page's last item, opaque to
// clients. Paging by cursor is faster than by offset in a long list, and
// skips or repeats nothing when the list changes between pages.
//
//	type FeedInput struct {
//		Limit int                   `query:"limit" default:"20"`
//		After listing.Cursor[int64] `query:"after"`
//	}
//	type FeedBody struct {
//		Items []Item                `json:"items"`
//		Next  listing.Cursor[int64] `json:"next,omitzero"` // none after the last page
//	}
type Cursor[K any] struct {
	// Key is the keys of the item to start after.
	Key K
	// Set reports whether there is a cursor: the first page has none.
	Set bool
}

// After returns the cursor of the page after the item with key.
func After[K any](key K) Cursor[K] {
	return Cursor[K]{Key: key, Set: true}
}

// MarshalText writes the cursor: its key as JSON, in base 64.
func (c Cursor[K]) MarshalText() ([]byte, error) {
	b, err := json.Marshal(c.Key)
	if err != nil {
		return nil, err
	}
//line listing.ego:121
	return []byte(base64.RawURLEncoding.EncodeToString(b)), nil
}

// UnmarshalText reads a cursor that MarshalText wrote.
func (c *Cursor[K]) UnmarshalText(text []byte) error {
	b, err := base64.RawURLEncoding.DecodeString(string(text))
	if err != nil || json.Unmarshal(b, &c.Key) != nil {
		return errors.New("not a cursor of this list")
	}
	c.Set = true
	return nil
}

// OpenAPISchema describes cursors as opaque strings.
func (Cursor[K]) OpenAPISchema() *openapi.Schema {
	return &openapi.Schema{Type: openapi.Types{"string"}, Description: "an opaque cursor"}
}

// Order lists the fields that a list can be sorted by: their names in the
// API, to the SQL expressions that sort by them. Its zero value is used.
type Order interface {
	Fields() map[string]string
}

// Sort is how a list is sorted, as a parameter: fields separated by
// commas, each first if descending with -, such as -createdAt,title. Only
// the fields of O are allowed, so its SQL is safe to put in a query.
type Sort[O Order] []SortField

// SortField is a field to sort by.
type SortField struct {
	Name string // the API's
	Desc bool
}

// UnmarshalText parses a sort, refusing fields that O doesn't list.
func (s *Sort[O]) UnmarshalText(text []byte) error {
	var fields O
	allowed := fields.Fields()
	var out Sort[O]
	for part := range strings.SplitSeq(string(text), ",") {
		f := SortField{Name: strings.TrimSpace(part)}
		if name, ok := strings.CutPrefix(f.Name, "-"); ok {
			f.Name, f.Desc = name, true
		}
		if _, ok := allowed[f.Name]; !ok {
			return errors.New("can't sort by " + strconv.Quote(f.Name) + ": sort by " + strings.Join(names(allowed), ", "))
		}
		out = append(out, f)
	}
	*s = out
	return nil
}

// MarshalText writes the sort as UnmarshalText reads it.
func (s Sort[O]) MarshalText() ([]byte, error) {
	parts := make([]string, len(s))
	for i, f := range s {
		if f.Desc {
			parts[i] = "-" + f.Name
		} else {
			parts[i] = f.Name
		}
	}
//line listing.ego:181
	return []byte(strings.Join(parts, ",")), nil
}

// SQL returns the sort as an ORDER BY list, made of O's expressions:
// a.created_at DESC, a.title. It is empty for no fields.
func (s Sort[O]) SQL() string {
	var fields O
	allowed := fields.Fields()
	parts := make([]string, len(s))
	for i, f := range s {
		var v2 string
		if f.Desc {
			v2 = " DESC"
		} else {
			v2 = ""
		}
		parts[i] = allowed[f.Name] + v2
	}
//line listing.ego:193
	return strings.Join(parts, ", ")
}

// OpenAPISchema describes a sort as a string of the fields of O.
func (Sort[O]) OpenAPISchema() *openapi.Schema {
	var fields O
	var quoted []string
	for _, name := range names(fields.Fields()) {
		quoted = append(quoted, regexp.QuoteMeta(name))
	}
	alts := strings.Join(quoted, "|")
	return &openapi.Schema{
		Type:        openapi.Types{"string"},
		Pattern:     "^-?(" + alts + ")(,-?(" + alts + "))*$",
		Description: "fields to sort by, separated by commas, each first if descending with -",
	}
}

// names returns the names of the fields, sorted.
func names(fields map[string]string) []string {
	var out []string
	for name := range fields {
		out = append(out, name)
	}
	slices.Sort(out)
	return out
}
