// Code generated by ego generate from rediscache_test.ego. DO NOT EDIT.

package rediscache_test

import (
	"context"
	"os"
	"testing"

	"github.com/goncini/goncini/cache"
	"github.com/goncini/goncini/cache/rediscache"
	"github.com/goncini/goncini/cache/storetest"
)

// store returns a store on the Redis of REDISCACHE_TEST_URL, emptied, or
// skips the test without one.
//
//line rediscache_test.ego:15
func store(t *testing.T) *rediscache.Store {
	url := os.Getenv("REDISCACHE_TEST_URL")
	if url == "" {
		t.Skip("REDISCACHE_TEST_URL names no Redis to test with")
	}
	client, closeClient, err := rediscache.NewClient(rediscache.Config{URL: url})
	if err != nil {
		panic(err)
	}
//line rediscache_test.ego:21
	t.Cleanup(func() {
		closeClient()
	})
//line rediscache_test.ego:22
	s := rediscache.NewStore(client)
	if err := s.Client.FlushDB(context.Background()).Err(); err != nil {
		panic(err)
	}
//line rediscache_test.ego:24
	return s
}

func TestStore(t *testing.T) {
	storetest.Run(t, func(t *testing.T) cache.Store { return store(t) })
}

func TestCache(t *testing.T) {
	s := store(t)
	if err := s.PingContext(context.Background()); err != nil {
		panic(err)
	}
//line rediscache_test.ego:34
	c := cache.New(cache.Config{Prefix: "test:"}, s)
	ctx := context.Background()
	calls := 0
	compute := func(ctx context.Context, item *cache.Item) ([]string, error) {
		calls++
		item.Tags = []string{"articles"}
		return []string{"go"}, nil
	}
	if _, err := cache.Get(ctx, c, "tags", compute); err != nil {
		panic(err)
	}
//line rediscache_test.ego:43
	if _, err := cache.Get(ctx, c, "tags", compute); err != nil {
		panic(err)
	}
//line rediscache_test.ego:44
	if err := c.Invalidate(ctx, "articles"); err != nil {
		panic(err)
	}
//line rediscache_test.ego:45
	got, err := cache.Get(ctx, c, "tags", compute)
	if err != nil {
		panic(err)
	}
//line rediscache_test.ego:46
	if calls != 2 || got[0] != "go" {
		t.Errorf("calls %d, got %v", calls, got)
	}
}
