// Code generated by ego generate from kernel_test.ego. DO NOT EDIT.

package routing_test

import (
	"log/slog"
	"net/http"
	"strings"
	"testing"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	sdktrace "go.opentelemetry.io/otel/sdk/trace"
	"go.opentelemetry.io/otel/sdk/trace/tracetest"
	"go.opentelemetry.io/otel/trace"

	"github.com/goncini/goncini/httpkernel"
	"github.com/goncini/goncini/routing"
)

// TestBehindAKernel serves a router from an httpkernel.Kernel: requests
// that match no route get problems, and an endpoint in a group with
// middleware gets its path value and names the request's span.
//
//line kernel_test.ego:22
func TestBehindAKernel(t *testing.T) {
	spans := tracetest.NewSpanRecorder()
	prev := otel.GetTracerProvider()
	otel.SetTracerProvider(sdktrace.NewTracerProvider(sdktrace.WithSpanProcessor(spans)))
	t.Cleanup(func() { otel.SetTracerProvider(prev) })

	// Middleware that hands the route a copy of the request, as most do.
	copying := func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
			next.ServeHTTP(w, req.WithContext(req.Context()))
		})
	}
	r := routing.New()
	r.Group("/api").With(copying).Get("/articles/{slug}", httpkernel.Endpoint(controller{}.Show))
	k := &httpkernel.Kernel{Handler: r, Logger: slog.New(slog.DiscardHandler)}

	rec := serve(k, "GET", "/nope")
	if rec.Code != 404 || rec.Header().Get("Content-Type") != "application/problem+json" ||
		!strings.Contains(rec.Body.String(), `"detail":"no route matches GET /nope"`) {
		t.Errorf("GET /nope: %d %s", rec.Code, rec.Body)
	}
	rec = serve(k, "POST", "/api/articles/x")
	if rec.Code != 405 || rec.Header().Get("Allow") != "GET, HEAD" ||
		!strings.Contains(rec.Body.String(), `"detail":"POST isn't allowed on /api/articles/x"`) {
		t.Errorf("POST /api/articles/x: %d %v %s", rec.Code, rec.Header(), rec.Body)
	}

	if rec := serve(k, "GET", "/api/articles/hello"); rec.Code != 200 || rec.Body.String() != `"hello"` {
		t.Errorf("GET /api/articles/hello: %d %s", rec.Code, rec.Body)
	}
	var server sdktrace.ReadOnlySpan
	for _, s := range spans.Ended() {
		if s.SpanKind() == trace.SpanKindServer {
			server = s // the last request's
		}
	}
	if server == nil {
		t.Fatal("no server span")
	}
	route := ""
	for _, kv := range server.Attributes() {
		if kv.Key == attribute.Key("http.route") {
			route = kv.Value.AsString()
		}
	}
	if server.Name() != "GET /api/articles/{slug}" || route != "/api/articles/{slug}" {
		t.Errorf("span %q with route %q", server.Name(), route)
	}
}
