// Code generated by ego generate from list_test.ego. DO NOT EDIT.

package routing_test

import (
	"context"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/goncini/goncini/httpkernel"
	"github.com/goncini/goncini/routing"
)

// controller has a typed handler, as an app's controllers do.
//
//line list_test.ego:14
type controller struct{}

type showIn struct {
	Slug string `path:"slug"`
}

func (controller) Show(ctx context.Context, in showIn) (string, error) { return in.Slug, nil }

func TestList(t *testing.T) {
	r := routing.New()
	first := nextLine()
	show := r.Get("/articles/{slug}", httpkernel.Endpoint(controller{}.Show))
	second := nextLine()
	r.Group("/admin").Handle("/", echo())
	if name := r.List()[0].Name; name != "" {
		t.Errorf("name before Name: %q", name)
	}
	show.Name("article_show")

	got := r.List()
	if len(got) != 2 {
		t.Fatalf("%d routes, want 2", len(got))
	}
	if a := got[0]; a.Name != "article_show" || a.Method != "GET" || a.Path != "/articles/{slug}" ||
		a.Pattern != "GET /articles/{slug}" || a.Source != first {
		t.Errorf("first route = %+v", a)
	}
	if b := got[1]; b.Name != "" || b.Method != "" || b.Path != "/admin/" || b.Pattern != "/admin/{$}" || b.Source != second {
		t.Errorf("second route = %+v", b)
	}
}

func TestMatch(t *testing.T) {
	r := routing.New()
	r.Get("/articles/{slug}", echo()).Name("article_show")
	r.Get("/files/{path...}", echo()).Name("file")

	for target, want := range map[string]string{
		"/articles/x":   "article_show",
		"/files/a/b":    "file",
		"/files//a":     "file", // redirected to /files/a
		"/articles/x/y": "",
		"/nope":         "",
	} {
		info, ok := r.Match(httptest.NewRequest(http.MethodGet, target, nil))
		if ok != (want != "") || info.Name != want {
			t.Errorf("Match(GET %s) = %q, %v; want %q", target, info.Name, ok, want)
		}
	}
	if info, ok := r.Match(httptest.NewRequest(http.MethodPost, "/articles/x", nil)); ok {
		t.Errorf("Match(POST /articles/x) = %q", info.Name)
	}
}
