// Code generated by ego generate from url_test.ego. DO NOT EDIT.

package routing_test

import (
	"errors"
	"math"
	"strings"
	"testing"
	"time"

	"github.com/goncini/goncini/routing"
)

//line url_test.ego:13
type userID int64

type slug string

// shout is written as text in capitals.
type shout string

func (s shout) MarshalText() ([]byte, error) { return []byte(strings.ToUpper(string(s))), nil }

// broken can't be written as text.
type broken struct{}

func (broken) MarshalText() ([]byte, error) { return nil, errors.New("broken") }

func TestURL(t *testing.T) {
	r := routing.New()
	r.Get("/", echo()).Name("home")
	r.Get("/articles", echo()).Name("list")
	r.Get("/articles/{slug}", echo("slug")).Name("show")
	r.Get("/users/{user}/posts/{post}", echo("user", "post")).Name("post")
	r.Get("/files/{path...}", echo("path")).Name("file")
	r.Get("/dir/", echo()).Name("dir")
	r.Get("/café/{x}", echo("x")).Name("cafe")

	when := time.Date(2026, 10, 4, 9, 30, 0, 0, time.UTC)
	n := 42
	tests := []struct {
		name   string
		params routing.Params
		want   string
	}{
		{"home", nil, "/"},
		{"list", nil, "/articles"},
		{"list", routing.Params{"page": 2, "tag": []string{"go", "api"}, "draft": nil}, "/articles?page=2&tag=go&tag=api"},
		{"show", routing.Params{"slug": "hello-world"}, "/articles/hello-world"},
		{"show", routing.Params{"slug": "a b/c?d#e%f"}, "/articles/a%20b%2Fc%3Fd%23e%25f"},
		{"show", routing.Params{"slug": "été"}, "/articles/%C3%A9t%C3%A9"},
		{"show", routing.Params{"slug": slug("typed")}, "/articles/typed"},
		{"show", routing.Params{"slug": shout("loud")}, "/articles/LOUD"},
		{"show", routing.Params{"slug": &n}, "/articles/42"},
		{"post", routing.Params{"user": userID(7), "post": uint8(255)}, "/users/7/posts/255"},
		{"post", routing.Params{"user": true, "post": 1.5}, "/users/true/posts/1.5"},
		{"post", routing.Params{"user": 90 * time.Second, "post": when}, "/users/1m30s/posts/2026-10-04T09:30:00Z"},
		{"file", routing.Params{"path": "a/b c/d.txt"}, "/files/a/b%20c/d.txt"},
		{"file", routing.Params{"path": ""}, "/files/"},
		{"dir", routing.Params{"q": "x y&z"}, "/dir/?q=x+y%26z"},
		{"cafe", routing.Params{"x": "1"}, "/caf%C3%A9/1"},
	}
	for _, tt := range tests {
		got, err := r.URL(tt.name, tt.params)
		if err != nil || got != tt.want {
			t.Errorf("URL(%q, %v) = %q, %v; want %q", tt.name, tt.params, got, err, tt.want)
		}
	}
}

// TestURLsLeadBackToTheirValues serves the URLs built for awkward values,
// and checks that the route gets each value back.
func TestURLsLeadBackToTheirValues(t *testing.T) {
	r := routing.New()
	r.Get("/one/{v}", echo("v")).Name("one")
	r.Get("/rest/{v...}", echo("v")).Name("rest")
	values := []string{"plain", "a b", "a/b", "%", "%2F", "?#", "...", ".x", "é", "+&=;,", "~!*'()", " ", "日本"}
	for _, v := range values {
		for _, name := range []string{"one", "rest"} {
			u, err := r.URL(name, routing.Params{"v": v})
			if err != nil {
				panic(err)
			}
//line url_test.ego:79
			var want string
			if name == "one" {
				want = "GET /one/{v} v=" + v
			} else {
				want = "GET /rest/{v...} v=" + v
			}
//line url_test.ego:80
			if rec := serve(r, "GET", u); rec.Code != 200 || rec.Body.String() != want {
				t.Errorf("%s with %q: GET %s gives %d %q", name, v, u, rec.Code, rec.Body)
			}
		}
	}
	for _, v := range []string{"", "a/b", "a/.../b", "a/b/", "%2F/x", "a/%2E%2E/b"} {
		u, err := r.URL("rest", routing.Params{"v": v})
		if err != nil {
			panic(err)
		}
//line url_test.ego:87
		if rec := serve(r, "GET", u); rec.Code != 200 || rec.Body.String() != "GET /rest/{v...} v="+v {
			t.Errorf("rest with %q: GET %s gives %d %q", v, u, rec.Code, rec.Body)
		}
	}
}

func TestURLErrors(t *testing.T) {
	r := routing.New()
	r.Get("/articles/{slug}", echo()).Name("show")
	r.Get("/files/{path...}", echo()).Name("file")
	var nilInt *int
	tests := []struct {
		name   string
		params routing.Params
		want   string
	}{
		{"nope", nil, `no route is named "nope"`},
		{"show", nil, `route "show" needs parameter "slug"`},
		{"show", routing.Params{"slug": nilInt}, `route "show" needs parameter "slug"`},
		{"show", routing.Params{"slug": ""}, `route "show": parameter "slug" is empty`},
		{"show", routing.Params{"slug": "/"}, `route "show": parameter "slug" can't be "/"`},
		{"show", routing.Params{"slug": "."}, `route "show": parameter "slug" can't be "."`},
		{"show", routing.Params{"slug": ".."}, `route "show": parameter "slug" can't be ".."`},
		{"show", routing.Params{"slug": math.NaN()}, `route "show": parameter "slug" is not a finite number`},
		{"show", routing.Params{"slug": make(chan int)}, `route "show": parameter "slug" is a chan int, which has no text form`},
		{"show", routing.Params{"slug": broken{}}, `route "show": parameter "slug" can't be written as text: broken`},
		{"show", routing.Params{"slug": "x", "page": []any{1, nil}}, `route "show": parameter "page" is nil`},
		{"file", routing.Params{"path": "a//b"}, `route "file": parameter "path" has an empty segment`},
		{"file", routing.Params{"path": "/abs"}, `route "file": parameter "path" has an empty segment`},
		{"file", routing.Params{"path": "a/../b"}, `route "file": parameter "path" has a ".." segment`},
		{"file", routing.Params{"path": "./a"}, `route "file": parameter "path" has a "." segment`},
	}
	for _, tt := range tests {
		got, err := r.URL(tt.name, tt.params)
		if err == nil || err.Error() != tt.want {
			t.Errorf("URL(%q, %v) = %q, %v; want the error %s", tt.name, tt.params, got, err, tt.want)
		}
	}
}

func TestURLErrorCases(t *testing.T) {
	r := routing.New()
	r.Get("/articles/{slug}", echo()).Name("show")
	unnamed := r.Get("/unnamed/{x}", echo())

	kind := func(err error) string {
		var v string
		if err == nil {
			v = "none"
		} else if e, ok := errors.AsType[routing.UnknownRoute](err); ok {
			v = "unknown " + e.Name
		} else if e, ok := errors.AsType[routing.MissingParam](err); ok {
			v = "missing " + e.Route + " " + e.Param
		} else if e, ok := errors.AsType[routing.InvalidParam](err); ok {
			v = "invalid " + e.Route + " " + e.Param
		} else if e, ok := errors.AsType[routing.Shadowed](err); ok {
			v = "shadowed " + e.Route + " " + e.URL
		} else {
			v = "other"
		}
		return v
	}
//line url_test.ego:142
	_, err := r.URL("nope", nil)
	if got := kind(err); got != "unknown nope" {
		t.Errorf("unknown route: %s", got)
	}
	_, err = r.URL("show", routing.Params{"slug": ""})
	if got := kind(err); got != "invalid show slug" {
		t.Errorf("empty value: %s", got)
	}
	_, err = unnamed.URL(nil)
	if got := kind(err); got != "missing GET /unnamed/{x} x" {
		t.Errorf("unnamed route: %s", got)
	}
	u, err := unnamed.URL(routing.Params{"x": 1})
	if err != nil {
		panic(err)
	}
//line url_test.ego:155
	if u != "/unnamed/1" {
		t.Errorf("unnamed route: %s", u)
	}
	r.Get("/articles/feed", echo()).Name("feed")
	_, err = r.URL("show", routing.Params{"slug": "feed"})
	if got := kind(err); got != "shadowed show /articles/feed" {
		t.Errorf("shadowed URL: %s", got)
	}
}

// TestURLRefusesURLsThatOtherRoutesServe builds URLs that a more specific
// route would serve, directly or after ServeMux's trailing-slash redirect.
func TestURLRefusesURLsThatOtherRoutesServe(t *testing.T) {
	r := routing.New()
	api := r.Group("/api").NamePrefix("api_")
	api.Get("/articles/feed", echo()).Name("feed")
	api.Get("/articles/{slug}", echo()).Name("article")
	r.Get("/files/{path...}", echo()).Name("file")
	r.Get("/files/{dir}/", echo()).Name("dir")
	r.Handle("/any/{x}", echo()).Name("any")
	r.Handle("/any/special", echo())

	tests := []struct {
		name   string
		params routing.Params
		want   string
	}{
		{"api_article", routing.Params{"slug": "feed"}, `route "api_article": /api/articles/feed would be served by "api_feed" (GET /api/articles/feed)`},
		{"file", routing.Params{"path": "docs"}, `route "file": /files/docs would be served by "dir" (GET /files/{dir}/{$})`},
		{"file", routing.Params{"path": "docs/"}, `route "file": /files/docs/ would be served by "dir" (GET /files/{dir}/{$})`},
		{"any", routing.Params{"x": "special"}, `route "any": /any/special would be served by /any/special`},
	}
	for _, tt := range tests {
		got, err := r.URL(tt.name, tt.params)
		if err == nil || err.Error() != tt.want {
			t.Errorf("URL(%q, %v) = %q, %v; want the error %s", tt.name, tt.params, got, err, tt.want)
		}
	}
	for name, params := range map[string]routing.Params{
		"api_article": {"slug": "hello"},
		"file":        {"path": "docs/a.md"},
		"dir":         {"dir": "docs"},
		"any":         {"x": "other"},
	} {
		if u, err := r.URL(name, params); err != nil {
			t.Errorf("URL(%q, %v) = %q, %v", name, params, u, err)
		}
	}
}

func TestQueryLeavesEmptyValuesOut(t *testing.T) {
	r := routing.New()
	r.Get("/articles", echo()).Name("list")
	u, err := r.URL("list", routing.Params{"q": "", "tag": []string{"go", "", "api"}, "none": []string{""}, "nil": (*int)(nil)})
	if err != nil {
		panic(err)
	}
//line url_test.ego:209
	if u != "/articles?tag=go&tag=api" {
		t.Errorf("URL = %s", u)
	}
}
