// Code generated by ego generate from url_test.ego. DO NOT EDIT.

package routing_test

import (
	"errors"
	"math"
	"strings"
	"testing"
	"time"

	"github.com/goncini/goncini/routing"
)

//line url_test.ego:13
type userID int64

type slug string

// shout is written as text in capitals.
type shout string

func (s shout) MarshalText() ([]byte, error) { return []byte(strings.ToUpper(string(s))), nil }

// broken can't be written as text.
type broken struct{}

func (broken) MarshalText() ([]byte, error) { return nil, errors.New("broken") }

func TestURL(t *testing.T) {
	r := routing.New()
	r.Get("/", echo()).Name("home")
	r.Get("/articles", echo()).Name("list")
	r.Get("/articles/{slug}", echo("slug")).Name("show")
	r.Get("/users/{user}/posts/{post}", echo("user", "post")).Name("post")
	r.Get("/files/{path...}", echo("path")).Name("file")
	r.Get("/dir/", echo()).Name("dir")
	r.Get("/café/{x}", echo("x")).Name("cafe")

	when := time.Date(2026, 10, 4, 9, 30, 0, 0, time.UTC)
	n := 42
	tests := []struct {
		name   string
		params routing.Params
		want   string
	}{
		{"home", nil, "/"},
		{"list", nil, "/articles"},
		{"list", routing.Params{"page": 2, "tag": []string{"go", "", "api"}, "q": "", "none": []string{""}, "draft": nil}, "/articles?page=2&tag=go&tag=api"},
		{"show", routing.Params{"slug": "hello-world"}, "/articles/hello-world"},
		{"show", routing.Params{"slug": "a b/c?d#e%f"}, "/articles/a%20b%2Fc%3Fd%23e%25f"},
		{"show", routing.Params{"slug": "été"}, "/articles/%C3%A9t%C3%A9"},
		{"show", routing.Params{"slug": slug("typed")}, "/articles/typed"},
		{"show", routing.Params{"slug": shout("loud")}, "/articles/LOUD"},
		{"show", routing.Params{"slug": &n}, "/articles/42"},
		{"post", routing.Params{"user": userID(7), "post": uint8(255)}, "/users/7/posts/255"},
		{"post", routing.Params{"user": true, "post": 1.5}, "/users/true/posts/1.5"},
		{"post", routing.Params{"user": 90 * time.Second, "post": when}, "/users/1m30s/posts/2026-10-04T09:30:00Z"},
		{"file", routing.Params{"path": "a/b c/d.txt"}, "/files/a/b%20c/d.txt"},
		{"file", routing.Params{"path": ""}, "/files/"},
		{"dir", routing.Params{"q": "x y&z"}, "/dir/?q=x+y%26z"},
		{"cafe", routing.Params{"x": "1"}, "/caf%C3%A9/1"},
	}
	for _, tt := range tests {
		got, err := r.URL(tt.name, tt.params)
		if err != nil || got != tt.want {
			t.Errorf("URL(%q, %v) = %q, %v; want %q", tt.name, tt.params, got, err, tt.want)
		}
	}
}

// TestURLsLeadBackToTheirValues serves the URLs built for awkward values,
// and checks that the route gets each value back.
func TestURLsLeadBackToTheirValues(t *testing.T) {
	r := routing.New()
	r.Get("/one/{v}", echo("v")).Name("one")
	r.Get("/rest/{v...}", echo("v")).Name("rest")
	values := []string{"plain", "a b", "a/b", "%", "%2F", "?#", "...", ".x", "é", "+&=;,", "~!*'()", " ", "日本"}
	for _, v := range values {
		for _, name := range []string{"one", "rest"} {
			u, err := r.URL(name, routing.Params{"v": v})
			if err != nil {
				panic(err)
			}
//line url_test.ego:79
			var want string
			if name == "one" {
				want = "GET /one/{v} v=" + v
			} else {
				want = "GET /rest/{v...} v=" + v
			}
//line url_test.ego:80
			if rec := serve(r, "GET", u); rec.Code != 200 || rec.Body.String() != want {
				t.Errorf("%s with %q: GET %s gives %d %q", name, v, u, rec.Code, rec.Body)
			}
		}
	}
	for _, v := range []string{"", "a/b", "a/.../b", "a/b/", "%2F/x", "a/%2E%2E/b"} {
		u, err := r.URL("rest", routing.Params{"v": v})
		if err != nil {
			panic(err)
		}
//line url_test.ego:87
		if rec := serve(r, "GET", u); rec.Code != 200 || rec.Body.String() != "GET /rest/{v...} v="+v {
			t.Errorf("rest with %q: GET %s gives %d %q", v, u, rec.Code, rec.Body)
		}
	}
}

// TestURLErrors checks each case of URLError, and its message. The
// ShadowedURL rows are URLs that a more specific route serves, directly or
// after ServeMux's trailing-slash redirect.
func TestURLErrors(t *testing.T) {
	r := routing.New()
	api := r.Group("/api").NamePrefix("api_")
	api.Get("/articles/{slug}", echo()).Name("article")
	api.Get("/articles/feed", echo()).Name("feed")
	r.Get("/files/{path...}", echo()).Name("file")
	r.Get("/files/{dir}/", echo()).Name("dir")
	r.Handle("/any/{x}", echo()).Name("any")
	r.Handle("/any/special", echo())
	var nilInt *int
	tests := []struct {
		name   string
		params routing.Params
		kind   string
		want   string
	}{
		{"nope", nil, "UnknownRoute", `no route is named "nope"`},
		{"api_article", nil, "MissingParam", `route "api_article" needs parameter "slug"`},
		{"api_article", routing.Params{"slug": nilInt}, "MissingParam", `route "api_article" needs parameter "slug"`},
		{"api_article", routing.Params{"slug": ""}, "InvalidParam", `route "api_article": parameter "slug" is empty`},
		{"api_article", routing.Params{"slug": "/"}, "InvalidParam", `route "api_article": parameter "slug" can't be "/"`},
		{"api_article", routing.Params{"slug": "."}, "InvalidParam", `route "api_article": parameter "slug" can't be "."`},
		{"api_article", routing.Params{"slug": ".."}, "InvalidParam", `route "api_article": parameter "slug" can't be ".."`},
		{"api_article", routing.Params{"slug": math.NaN()}, "InvalidParam", `route "api_article": parameter "slug" is not a finite number`},
		{"api_article", routing.Params{"slug": make(chan int)}, "InvalidParam", `route "api_article": parameter "slug" is a chan int, which has no text form`},
		{"api_article", routing.Params{"slug": broken{}}, "InvalidParam", `route "api_article": parameter "slug" can't be written as text: broken`},
		{"api_article", routing.Params{"slug": "x", "page": []any{1, nil}}, "InvalidParam", `route "api_article": parameter "page" is nil`},
		{"file", routing.Params{"path": "a//b"}, "InvalidParam", `route "file": parameter "path" has an empty segment`},
		{"file", routing.Params{"path": "/abs"}, "InvalidParam", `route "file": parameter "path" has an empty segment`},
		{"file", routing.Params{"path": "a/../b"}, "InvalidParam", `route "file": parameter "path" has a ".." segment`},
		{"file", routing.Params{"path": "./a"}, "InvalidParam", `route "file": parameter "path" has a "." segment`},
		{"api_article", routing.Params{"slug": "feed"}, "ShadowedURL", `route "api_article": /api/articles/feed would be served by GET /api/articles/feed`},
		{"file", routing.Params{"path": "docs"}, "ShadowedURL", `route "file": /files/docs would be served by GET /files/{dir}/{$}`},
		{"file", routing.Params{"path": "docs/"}, "ShadowedURL", `route "file": /files/docs/ would be served by GET /files/{dir}/{$}`},
		{"any", routing.Params{"x": "special"}, "ShadowedURL", `route "any": /any/special would be served by /any/special`},
	}
	for _, tt := range tests {
		got, err := r.URL(tt.name, tt.params)
		var kind string
		if err == nil {
			kind = "none"
		} else if _, ok := errors.AsType[routing.UnknownRoute](err); ok {
			kind = "UnknownRoute"
		} else if _, ok := errors.AsType[routing.MissingParam](err); ok {
			kind = "MissingParam"
		} else if _, ok := errors.AsType[routing.InvalidParam](err); ok {
			kind = "InvalidParam"
		} else if _, ok := errors.AsType[routing.ShadowedURL](err); ok {
			kind = "ShadowedURL"
		} else {
			panic(err)
		}
//line url_test.ego:141
		if kind != tt.kind || err.Error() != tt.want {
			t.Errorf("URL(%q, %v) = %q, %v (%s); want the %s %s", tt.name, tt.params, got, err, kind, tt.kind, tt.want)
		}
	}

	// Next to those, URLs that their own route serves.
	for name, params := range map[string]routing.Params{
		"api_article": {"slug": "hello"},
		"file":        {"path": "docs/a.md"},
		"dir":         {"dir": "docs"},
		"any":         {"x": "other"},
	} {
		if u, err := r.URL(name, params); err != nil {
			t.Errorf("URL(%q, %v) = %q, %v", name, params, u, err)
		}
	}

	// A route without a name is named by its pattern.
	unnamed := r.Get("/unnamed/{x}", echo())
	if _, err := unnamed.URL(nil); err == nil || err.Error() != `route "GET /unnamed/{x}" needs parameter "x"` {
		t.Errorf("unnamed route: %v", err)
	}
}
