// Code generated by ego generate from gormdb_test.ego. DO NOT EDIT.

package gormdb_test

import (
	"bytes"
	"context"
	"errors"
	"strings"
	"testing"

	"github.com/glebarez/sqlite"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"

	"github.com/goncini/goncini/db"
	"github.com/goncini/goncini/db/gormdb"
)

//line gormdb_test.ego:18
type Article struct {
	Slug string `gorm:"primaryKey"`
}

// open opens GORM on a pool that goncini's db.Open opened, as an app does.
func open(t *testing.T) *gormdb.Transactor {
	pool, closePool, err := db.Open(context.Background(), db.Config{Driver: "sqlite", URL: ":memory:", MaxOpenConns: 1})
	if err != nil {
		panic(err)
	}
//line gormdb_test.ego:25
	t.Cleanup(func() {
		closePool()
	})
//line gormdb_test.ego:26
	gdb, err := gorm.Open(sqlite.Dialector{Conn: pool}, &gorm.Config{Logger: logger.Discard})
	if err != nil {
		panic(err)
	}
//line gormdb_test.ego:27
	return gormdb.New(gdb)
}

func TestAutoMigrate(t *testing.T) {
	tr := open(t)
	ctx := context.Background()
	m := gormdb.AutoMigrate(tr.DB, &Article{})
	var out bytes.Buffer
	if err := m.Status(ctx, &out); err != nil {
		panic(err)
	}
//line gormdb_test.ego:36
	if err := m.Up(ctx, &out); err != nil {
		panic(err)
	}
//line gormdb_test.ego:37
	if err := m.Status(ctx, &out); err != nil {
		panic(err)
	}
//line gormdb_test.ego:38
	want := "MODEL                 TABLE\n*gormdb_test.Article  missing\n" +
		"migrated the tables of 1 models\n" +
		"MODEL                 TABLE\n*gormdb_test.Article  exists\n"
	if out.String() != want {
		t.Errorf("output:\n%s\nwant:\n%s", out.String(), want)
	}
	if err := m.Down(ctx, &out); err == nil {
		t.Error("Down succeeded")
	}
}

func TestInTx(t *testing.T) {
	tr := open(t)
	ctx := context.Background()
	if err := tr.DB.AutoMigrate(&Article{}); err != nil {
		panic(err)
	}
//line gormdb_test.ego:53
	insert := func(ctx context.Context, slug string) error { return tr.Conn(ctx).Create(&Article{Slug: slug}).Error }
	failed := errors.New("failed")

	if err := tr.InTx(ctx, func(ctx context.Context) error { return insert(ctx, "a") }); err != nil {
		panic(err)
	}
//line gormdb_test.ego:57
	if err := tr.InTx(ctx, func(ctx context.Context) error { insert(ctx, "b"); return failed }); !errors.Is(err, failed) {
		t.Errorf("failure: %v", err)
	}
	if err := tr.InTx(ctx, func(ctx context.Context) error {
		return tr.InTx(ctx, func(ctx context.Context) error { return insert(ctx, "c") })
	}); err != nil {
		panic(err)
	}
//line gormdb_test.ego:61
	err := tr.InTx(ctx, func(ctx context.Context) error {
		insert(ctx, "d")
		return tr.InTx(ctx, func(_ context.Context) error { return failed })
	})
	if !errors.Is(err, failed) {
		t.Errorf("nested failure: %v", err)
	}
	func() {
		defer func() { recover() }()
		tr.InTx(ctx, func(ctx context.Context) error { insert(ctx, "e"); panic("boom") })
	}()

	var all []Article
	if err := tr.Conn(ctx).Order("slug").Find(&all).Error; err != nil {
		t.Fatal(err)
	}
	var slugs []string
	for _, a := range all {
		slugs = append(slugs, a.Slug)
	}
	if got := strings.Join(slugs, " "); got != "a c" {
		t.Errorf("slugs: %q, want %q", got, "a c")
	}
}
