// Code generated by ego generate from prod.ego. DO NOT EDIT.

package config

//line prod.ego:3
func prod(c *Config) {
	c.HTTP.TrustedProxies = []string{"private"}
	c.HTTP.TrustedHosts = []string{"articles.example.com"}
	c.Log.JSON = true
}
