// Code generated by ego generate from main.ego. DO NOT EDIT.

// Command articles is a small API built with httpkernel: an effect-go error
// set mapped to responses, typed endpoints, validation, and a server that
// shuts down gracefully.
//
//	go run ./examples/articles
//	curl -i localhost:8080/articles -H 'Content-Type: application/json' -d '{"title":"Hello","body":"First post"}'
package main

import (
	"log/slog"
	"net/http"
	"os"
	"time"

	"github.com/goncini/goncini/httpkernel"

	"github.com/effect-go/effect-go/scope"
	"github.com/effect-go/effect-go/trace"
)

//line main.ego:18
func main() {
	slog.SetDefault(slog.New(trace.LogHandler(slog.NewTextHandler(os.Stderr, nil))))
	v, ok := os.LookupEnv("ADDR")
	if !ok {
		v = ":8080"
	}
	srv := &httpkernel.Server{
		Addr:    v,
		Handler: NewKernel(NewArticles(time.Now), slog.Default()),
	}
//line main.ego:24
	scope.Main(func(s *scope.Scope) error { return srv.ListenAndServe(s.Context()) })
}

// NewKernel serves the articles API, logging each request.
func NewKernel(a *Articles, logger *slog.Logger) *httpkernel.Kernel {
	mux := http.NewServeMux()
	a.Routes(mux)
	return &httpkernel.Kernel{
		Handler:      mux,
		Middleware:   []httpkernel.Middleware{httpkernel.AccessLog(logger)},
		ErrorMappers: []httpkernel.ErrorMapper{Problems},
		Logger:       logger,
	}
}
