// Code generated by ego generate from openapi_test.ego. DO NOT EDIT.

package main

import (
	"encoding/json/v2"
	"fmt"
	"os"
	"slices"
	"strconv"
	"strings"
	"testing"

	"github.com/goncini/goncini/openapi"
	"github.com/goncini/goncini/webtest"

	"github.com/goncini/goncini/examples/realworld/app"
	"github.com/goncini/goncini/examples/realworld/config"
)

// TestDocumentCoversRealWorlds compares the app's OpenAPI document, which
// goncini generates, with RealWorld's own, in testdata/openapi: every
// operation of RealWorld's is in the app's, with the same parameters, the
// same request body and the same successful response, whose schemas are
// compatible. The error responses are checked by TestSpec, which fails on
// any status the document doesn't declare.
//
//line openapi_test.ego:24
func TestDocumentCoversRealWorlds(t *testing.T) {
	a := webtest.Boot(t, config.Load, app.Build)
	ours := a.OpenAPI
	var theirs openapi.Document
	b, err := os.ReadFile("testdata/openapi/realworld.json")
	if err != nil {
		panic(err)
	}
//line openapi_test.ego:29
	if err := json.Unmarshal(b, &theirs); err != nil {
		t.Fatal(err)
	}
	cmp := &comparison{ours: ours, theirs: &theirs}
	for _, path := range slices.Sorted(maps(theirs.Paths)) {
		item := theirs.Paths[path]
		for _, method := range []string{"GET", "PUT", "POST", "DELETE", "PATCH"} {
			op := *item.Operation(method)
			if op == nil {
				continue
			}
			what := method + " " + path
			ourItem := ours.Paths["/api"+path]
			if ourItem == nil || *ourItem.Operation(method) == nil {
				cmp.fail(what, "isn't in the app's document")
				continue
			}
			cmp.operation(what, op, *ourItem.Operation(method))
		}
	}
	for _, e := range cmp.errs {
		t.Error(e)
	}
}

// comparison compares two documents, collecting their differences.
type comparison struct {
	ours, theirs *openapi.Document
	errs         []string
}

func (c *comparison) fail(at, format string, args ...any) {
	c.errs = append(c.errs, at+": "+fmt.Sprintf(format, args...))
}

// operation compares an operation of RealWorld's with the app's.
func (c *comparison) operation(what string, theirs, ours *openapi.Operation) {
	for _, tp := range theirs.Parameters {
		tp = c.theirParameter(tp)
		i := slices.IndexFunc(ours.Parameters, func(p *openapi.Parameter) bool { return p.Name == tp.Name && p.In == tp.In })
		if i < 0 {
			c.fail(what, "the app has no %s parameter %s", tp.In, tp.Name)
			continue
		}
		op := ours.Parameters[i]
		if tp.Required != op.Required {
			c.fail(what, "the parameter %s is required: %v for RealWorld, %v for the app", tp.Name, tp.Required, op.Required)
		}
		c.schema(what+" parameter "+tp.Name, tp.Schema, op.Schema, reading)
	}
	if rb := theirs.RequestBody; rb != nil {
		if name, ok := strings.CutPrefix(rb.Ref, "#/components/requestBodies/"); ok {
			rb = c.theirs.Components.RequestBodies[name]
		}
		switch {
		case ours.RequestBody == nil:
			c.fail(what, "the app takes no request body")
		case rb.Required != ours.RequestBody.Required:
			c.fail(what, "the request body is required: %v for RealWorld, %v for the app", rb.Required, ours.RequestBody.Required)
		default:
			c.schema(what+" request body", rb.Content["application/json"].Schema, ours.RequestBody.Content["application/json"].Schema, reading)
		}
	}
	for status, res := range theirs.Responses {
		if !strings.HasPrefix(status, "2") {
			continue
		}
		ourRes := ours.Responses[status]
		if ourRes == nil {
			c.fail(what, "the app has no %s response", status)
			continue
		}
		if name, ok := strings.CutPrefix(res.Ref, "#/components/responses/"); ok {
			res = c.theirs.Components.Responses[name]
		}
		if mt := res.Content["application/json"]; mt != nil {
			var v *openapi.Schema
			if ourRes.Content["application/json"] != nil {
				v = ourRes.Content["application/json"].Schema
			}
			c.schema(what+" "+status+" response", mt.Schema, v, writing)
		}
	}
}

// theirParameter returns p, or the component it refers to.
//
//line openapi_test.ego:111
func (c *comparison) theirParameter(p *openapi.Parameter) *openapi.Parameter {
	if name, ok := strings.CutPrefix(p.Ref, "#/components/parameters/"); ok {
		return c.theirs.Components.Parameters[name]
	}
	return p
}

// direction is whether a schema is of what the API reads or writes: the
// app may write more members than RealWorld requires, and may read fewer.
type direction int

const (
	reading direction = iota
	writing
)

func (v direction) String() string {
	switch v {
	case reading:
		return "reading"
	case writing:
		return "writing"
	}
	return "direction(" + strconv.Itoa(int(v)) + ")"
}

// schema compares a schema of RealWorld's with the app's, at the path what.
//
//line openapi_test.ego:126
func (c *comparison) schema(what string, theirs, ours *openapi.Schema, dir direction) {
	theirs = resolve(c.theirs, theirs)
	ours, ourNull := nullableOf(resolve(c.ours, ours))
	ours = resolve(c.ours, ours)
	if theirs == nil || ours == nil {
		if theirs != nil {
			c.fail(what, "has no schema in the app's document")
		}
		return
	}
	theirNull := theirs.Type.Is("null")
	if theirNull != ourNull && (dir == writing || theirNull) {
		c.fail(what, "allows null: %v for RealWorld, %v for the app", theirNull, ourNull)
	}
	for _, typ := range theirs.Type {
		if typ != "null" && !ours.Type.Is(typ) {
			c.fail(what, "is a %s for RealWorld, a %v for the app", typ, ours.Type)
		}
	}
	for name, tp := range theirs.Properties {
		op, ok := ours.Properties[name]
		if !ok {
			c.fail(what, "the app has no member %s", name)
			continue
		}
		c.schema(what+"/"+name, tp, op, dir)
	}
	for _, name := range theirs.Required {
		if dir == writing && !slices.Contains(ours.Required, name) {
			c.fail(what, "the app doesn't always write %s, which RealWorld requires", name)
		}
	}
	for _, name := range ours.Required {
		if dir == reading && !slices.Contains(theirs.Required, name) {
			c.fail(what, "the app requires %s, which RealWorld doesn't", name)
		}
	}
	if theirs.Items != nil {
		c.schema(what+"/items", theirs.Items, ours.Items, dir)
	}
	if theirs.AdditionalProperties != nil {
		c.schema(what+"/*", theirs.AdditionalProperties, ours.AdditionalProperties, dir)
	}
}

// resolve returns s, or the schema it refers to.
func resolve(doc *openapi.Document, s *openapi.Schema) *openapi.Schema {
	for s != nil && s.Ref != "" {
		s = doc.Components.Schemas[strings.TrimPrefix(s.Ref, "#/components/schemas/")]
	}
	return s
}

// nullableOf returns the schema that s allows besides null, and whether it
// allows null: s, or the other schema of an anyOf with null.
func nullableOf(s *openapi.Schema) (*openapi.Schema, bool) {
	if s == nil {
		return nil, false
	}
	if len(s.AnyOf) == 2 && s.AnyOf[1].Type.Is("null") {
		return s.AnyOf[0], true
	}
	return s, s.Type.Is("null")
}

// maps returns the keys of a map.
func maps[V any](m map[string]V) func(func(string) bool) {
	return func(yield func(string) bool) {
		for k := range m {
			if !yield(k) {
				return
			}
		}
	}
}
