// Code generated by ego generate from articles_test.ego. DO NOT EDIT.

package httpkernel_test

import (
	"context"
	"errors"
	"fmt"
	"net/http"

	"github.com/goncini/goncini/httpkernel"

	"github.com/effect-go/effect-go/trace"
)

// ArticleError is what the articles service of the tests fails with.
//
//line articles_test.ego:10
type ArticleError interface {
	error
	isArticleError()
}

type ArticleNotFound struct{ Slug string }

func (ArticleNotFound) isArticleError() {}

func (e ArticleNotFound) Error() string { return fmt.Sprintf("no article %v", e.Slug) }

// As lets pointers to ArticleNotFound match as ArticleNotFound.
func (e ArticleNotFound) As(target any) bool {
	if t, ok := target.(*ArticleNotFound); ok {
		*t = e
		return true
	}
	return false
}

type ArticleLocked struct{ Slug string }

func (ArticleLocked) isArticleError() {}

func (e ArticleLocked) Error() string { return fmt.Sprintf("the article %v is locked", e.Slug) }

// As lets pointers to ArticleLocked match as ArticleLocked.
func (e ArticleLocked) As(target any) bool {
	if t, ok := target.(*ArticleLocked); ok {
		*t = e
		return true
	}
	return false
}

type ArticleStorage struct{ Cause error }

func (ArticleStorage) isArticleError() {}

func (e ArticleStorage) Error() string { return fmt.Sprintf("storage: %v", e.Cause) }

func (e ArticleStorage) Unwrap() error { return e.Cause }

// As lets pointers to ArticleStorage match as ArticleStorage.
func (e ArticleStorage) As(target any) bool {
	if t, ok := target.(*ArticleStorage); ok {
		*t = e
		return true
	}
	return false
}

// articleProblem is the response to each case: a new case doesn't compile
// until it has one.
//
//line articles_test.ego:18
func articleProblem(err error) httpkernel.Problem {
	var v httpkernel.Problem
	if err == nil {
		v = httpkernel.Problem{}
	} else if e, ok := errors.AsType[ArticleNotFound](err); ok {
		v = httpkernel.Problem{Status: http.StatusNotFound, Detail: e.Error()}
	} else if e, ok := errors.AsType[ArticleLocked](err); ok {
		v = httpkernel.Problem{Status: http.StatusConflict, Detail: e.Error()}
	} else if _, ok := errors.AsType[ArticleStorage](err); ok {
		v = httpkernel.Problem{Status: http.StatusServiceUnavailable, Detail: "try again later"}
	} else {
		panic(err)
	}
	return v
}

// articleProblems pairs the set with its problems, once.
//
//line articles_test.ego:28
var articleProblems = httpkernel.Map[ArticleError](articleProblem)

type articles struct {
	titles map[string]string
}

type showArticle struct {
	Slug string `path:"slug"`
}

type articleOut struct {
	Slug  string `json:"slug"`
	Title string `json:"title"`
}

// Show is an effect method: it compiles to a func(ctx, showArticle)
// (articleOut, error), which httpkernel.Endpoint serves.
func (a *articles) Show(ctx context.Context, in showArticle) (_ articleOut, err error) {
	ctx, span := trace.Start(ctx, "httpkernel_test.articles.Show")
	defer trace.End(span, &err)
//line articles_test.ego:46
	title, ok := a.titles[in.Slug]
	if !ok {
		return articleOut{}, ArticleNotFound{Slug: in.Slug}
	}
	if title == "" {
		return articleOut{}, ArticleLocked{Slug: in.Slug}
	}
	return articleOut{Slug: in.Slug, Title: title}, nil
}
