// Code generated by ego generate from bind.ego. DO NOT EDIT.

package httpkernel

import (
	"encoding"
	"errors"
	"fmt"
	"math"
	"net/http"
	"net/url"
	"reflect"
	"slices"
	"strconv"
	"strings"
	"time"
)

// binder fills the input of an Endpoint from a request. It is built once,
// when the Endpoint is.
//
//line bind.ego:18
type binder struct {
	params []param
	body   int // index of the Body field, or -1
}

// param is an input field bound to a path, query or header value.
type param struct {
	field    []int // index of the field, through embedded structs
	in       paramSource
	key      string // name of the wildcard, parameter or header
	required bool
	def      []string                            // values used when absent, or nil
	enum     []string                            // allowed values, or nil for any
	slice    bool                                // the field takes every value
	pointer  bool                                // the field is a pointer, nil when absent
	parse    func(string) (reflect.Value, error) // its errors are violation details
}

var (
	textUnmarshaler = reflect.TypeFor[encoding.TextUnmarshaler]()
	durationType    = reflect.TypeFor[time.Duration]()
)

// newBinder plans how to bind the struct type t. It panics if t can't be an
// input.
func newBinder(t reflect.Type) *binder {
	if t.Kind() != reflect.Struct {
		panic(fmt.Sprintf("httpkernel.Endpoint: the input type %v isn't a struct", t))
	}
	b := &binder{body: -1}
	mustNotHide(t, t, nil)
	for _, f := range reflect.VisibleFields(t) {
		if f.Name == "Body" && len(f.Index) == 1 {
			b.body = f.Index[0]
			continue
		}
		in, key, opts, ok := source(t, f)
		if !ok {
			continue
		}
		where := fmt.Sprintf("httpkernel.Endpoint: field %v.%s", t, f.Name)
		if !f.IsExported() {
			panic(fmt.Sprintf("%s is unexported", where))
		}
		if throughPointer(t, f.Index) {
			panic(fmt.Sprintf("%s is in an embedded pointer", where))
		}
		p := param{field: f.Index, in: in, key: key, required: in == inPath}
		for _, o := range opts {
			if o != "required" {
				panic(fmt.Sprintf("%s has an unknown option %q", where, o))
			}
			p.required = true
		}
		ft := f.Type
		if ft.Kind() == reflect.Pointer {
			p.pointer, ft = true, ft.Elem()
		} else if ft.Kind() == reflect.Slice && !ft.Implements(textUnmarshaler) && !reflect.PointerTo(ft).Implements(textUnmarshaler) {
			p.slice, ft = true, ft.Elem()
		}
		if p.parse, ok = parser(ft); !ok {
			panic(fmt.Sprintf("%s has type %v, which can't hold a %s value", where, f.Type, in.tag()))
		}
		if enum, ok := f.Tag.Lookup("enum"); ok {
			p.enum = strings.Split(enum, ",")
		}
		if def, ok := f.Tag.Lookup("default"); ok {
			if p.required {
				panic(fmt.Sprintf("%s is required and has a default", where))
			}
			if p.slice {
				p.def = strings.Split(def, ",")
			} else {
				p.def = []string{def}
			}
//line bind.ego:89
			if detail := p.set(reflect.New(f.Type).Elem(), p.def); detail != "" {
				panic(fmt.Sprintf("%s has an invalid default %q: it %s", where, def, detail))
			}
		}
		b.params = append(b.params, p)
	}
	return b
}

// mustNotHide panics if a field of t, the input type in, or of the structs
// it embeds, has a path, query or header tag but is hidden by a field of
// the same name nearer to in, which Go's selectors would pick instead: a
// value that would never be bound.
func mustNotHide(in, t reflect.Type, index []int) {
	for i := range t.NumField() {
		f := t.Field(i)
		at := append(slices.Clone(index), i)
		if ft := f.Type; f.Anonymous && (ft.Kind() == reflect.Struct || ft.Kind() == reflect.Pointer && ft.Elem().Kind() == reflect.Struct) {
			var v reflect.Type
			if ft.Kind() == reflect.Pointer {
				v = ft.Elem()
			} else {
				v = ft
			}
			mustNotHide(in, v, at)
		}
//line bind.ego:109
		if len(at) == 1 || !hasSourceTag(f) {
			continue
		}
		if visible, ok := in.FieldByName(f.Name); !ok || !slices.Equal(visible.Index, at) {
			panic(fmt.Sprintf("httpkernel.Endpoint: field %v.%s, which has a %s tag, is hidden by another field named %s: rename one", in, f.Name, sourceTag(f), f.Name))
		}
	}
}

// hasSourceTag reports whether f has a path, query or header tag.
func hasSourceTag(f reflect.StructField) bool {
	return sourceTag(f) != ""
}

// sourceTag is the name of f's path, query or header tag, or "".
func sourceTag(f reflect.StructField) string {
	for _, s := range []paramSource{inPath, inQuery, inHeader} {
		if _, ok := f.Tag.Lookup(s.tag()); ok {
			return s.tag()
		}
	}
	return ""
}

// source returns where a field gets its value from its tags: path, query or
// header, with the name and the options after it.
func source(t reflect.Type, f reflect.StructField) (in paramSource, key string, opts []string, ok bool) {
	for _, s := range []paramSource{inPath, inQuery, inHeader} {
		tag, found := f.Tag.Lookup(s.tag())
		if !found {
			continue
		}
		if ok {
			panic(fmt.Sprintf("httpkernel.Endpoint: field %v.%s has two of the path, query and header tags", t, f.Name))
		}
		parts := strings.Split(tag, ",")
		in, key, opts, ok = s, parts[0], parts[1:], true
		if key == "" {
			panic(fmt.Sprintf("httpkernel.Endpoint: field %v.%s has an empty %s name", t, f.Name, s.tag()))
		}
	}
	return in, key, opts, ok
}

// tag is the struct tag that names the source.
func (s paramSource) tag() string {
	var v string
	switch s {
	case inPath:
		v = "path"
	case inQuery:
		v = "query"
	case inHeader:
		v = "header"
	default:
		panic(s)
	}
	return v
}

// throughPointer reports whether the field at index is reached through an
// embedded pointer, which may be nil.
//
//line bind.ego:164
func throughPointer(t reflect.Type, index []int) bool {
	for _, i := range index[:len(index)-1] {
		f := t.Field(i)
		if f.Type.Kind() == reflect.Pointer {
			return true
		}
		t = f.Type
	}
	return false
}

// parser returns how to parse a value into type t, and whether t is
// supported. The errors of the parse function are violation details.
func parser(t reflect.Type) (func(string) (reflect.Value, error), bool) {
	switch {
	case t == timeType:
		return parsing(t, timeDetail, func(s string) (time.Time, error) { return time.Parse(time.RFC3339, s) }), true
	case t == durationType:
		return parsing(t, "must be a duration, such as 1m30s", time.ParseDuration), true
	case reflect.PointerTo(t).Implements(textUnmarshaler):
		return func(s string) (reflect.Value, error) {
			v := reflect.New(t)
			if err := v.Interface().(encoding.TextUnmarshaler).UnmarshalText([]byte(s)); err != nil {
				return reflect.Value{}, fmt.Errorf("is invalid: %w", err)
			}
			return v.Elem(), nil
		}, true
	}
//line bind.ego:190
	switch t.Kind() {
	case reflect.String:
		return parsing(t, "", asString), true
	case reflect.Bool:
		return parsing(t, "must be true or false", strconv.ParseBool), true
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		lo, hi := int64(-1)<<(t.Bits()-1), int64(1)<<(t.Bits()-1)-1
		var detail string
		if t.Bits() == 64 {
			detail = "must be an integer"
		} else {
			detail = fmt.Sprintf("must be an integer from %d to %d", lo, hi)
		}
//line bind.ego:198
		return parsing(t, detail, func(s string) (int64, error) { return strconv.ParseInt(s, 10, t.Bits()) }), true
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		hi := uint64(math.MaxUint64) >> (64 - t.Bits())
		var detail string
		if t.Bits() == 64 {
			detail = "must be a non-negative integer"
		} else {
			detail = fmt.Sprintf("must be an integer from 0 to %d", hi)
		}
//line bind.ego:202
		return parsing(t, detail, func(s string) (uint64, error) { return strconv.ParseUint(s, 10, t.Bits()) }), true
	case reflect.Float32, reflect.Float64:
		return parsing(t, "must be a number", func(s string) (float64, error) { return parseFinite(s, t.Bits()) }), true
	}
	return nil, false
}

// parsing makes the parser of type t out of a function that parses a V,
// converting the result to t. A value that doesn't parse gets detail as its
// error.
func parsing[V any](t reflect.Type, detail string, parse func(string) (V, error)) func(string) (reflect.Value, error) {
	return func(s string) (reflect.Value, error) {
		v, err := parse(s)
		if err != nil {
			return reflect.Value{}, fmt.Errorf("%v", detail)
		}
		return reflect.ValueOf(v).Convert(t), nil
	}
}

// asString parses a string: any is fine.
func asString(s string) (string, error) { return s, nil }

// bind fills in from r: the parameters first, then the body. Invalid
// parameters are a 400 Problem listing them all; a body that can't be read
// is a BodyError.
func (b *binder) bind(w http.ResponseWriter, r *http.Request, in reflect.Value, bodyLimit int64) error {
	var violations []Violation
	var query url.Values
	queryRead := false
	for i := range b.params {
		p := &b.params[i]
		var values []string
		switch p.in {
		case inPath:

//line bind.ego:237
			if v := r.PathValue(p.key); v != "" {
				values = []string{v}
			}

		case inQuery:

//line bind.ego:242
			if !queryRead {
				var err error
				if query, err = url.ParseQuery(r.URL.RawQuery); err != nil {
					violations = append(violations, Violation{Detail: "malformed query string"})
				}
				queryRead = true
			}
			values = nonEmpty(query[p.key])

		case inHeader:
//line bind.ego:251
			values = nonEmpty(r.Header.Values(p.key))
		}
		if len(values) == 0 {
			if p.required && !emptyRemainder(r, p) {
				violations = append(violations, p.violation("is required"))
				continue
			}
			if values = p.def; values == nil {
				continue
			}
		}
		if detail := p.set(in.FieldByIndex(p.field), values); detail != "" {
			violations = append(violations, p.violation(detail))
		}
	}
	if len(violations) > 0 {
		return Problem{Status: http.StatusBadRequest, Detail: "invalid request parameters", Errors: violations}
	}
	if b.body < 0 {
		return nil
	}
	body := in.Field(b.body)
	if body.Kind() != reflect.Pointer {
		return BodyDecoder{Limit: bodyLimit}.Decode(w, r, body.Addr().Interface())
	}
	if r.Body == nil || r.Body == http.NoBody || r.ContentLength == 0 {
		return nil // an optional body, absent
	}
	v := reflect.New(body.Type().Elem())
	if err := (BodyDecoder{Limit: bodyLimit}).Decode(w, r, v.Interface()); err != nil {
		if _, empty := errors.AsType[BodyEmpty](err); empty {
			return nil // a chunked body that turned out empty
		}
		return err
	}
	body.Set(v)
	return nil
}

// emptyRemainder reports whether p is a {name...} wildcard of the pattern
// that matched r, which can match nothing, as /files/{path...} matches
// /files/.
func emptyRemainder(r *http.Request, p *param) bool {
	return p.in == inPath && strings.Contains(r.Pattern, fmt.Sprintf("{%s...}", p.key))
}

// set parses values into the field f, and returns a violation detail if a
// value is invalid.
func (p *param) set(f reflect.Value, values []string) string {
	if !p.slice {
		values = values[:1]
	}
	if p.enum != nil && slices.ContainsFunc(values, func(v string) bool { return !slices.Contains(p.enum, v) }) {
		return fmt.Sprintf("must be one of: %s", strings.Join(p.enum, ", "))
	}
	if p.slice {
		s := reflect.MakeSlice(f.Type(), 0, len(values))
		for _, raw := range values {
			v, err := p.parse(raw)
			if err != nil {
				return err.Error()
			}
			s = reflect.Append(s, v)
		}
		f.Set(s)
		return ""
	}
	v, err := p.parse(values[0])
	if err != nil {
		return err.Error()
	}
	if p.pointer {
		ptr := reflect.New(v.Type())
		ptr.Elem().Set(v)
		v = ptr
	}
	f.Set(v)
	return ""
}

// violation is a violation of p with the detail.
func (p *param) violation(detail string) Violation {
	return violationOf(p.in, p.key, detail)
}

// nonEmpty returns the values that aren't empty.
func nonEmpty(values []string) []string {
	var out []string
	for _, v := range values {
		if v != "" {
			out = append(out, v)
		}
	}
	return out
}
