// Code generated by ego generate from body.ego. DO NOT EDIT.

package httpkernel

import (
	"bytes"
	"encoding/json/jsontext"
	"encoding/json/v2"
	"errors"
	"fmt"
	"io"
	"mime"
	"net/http"
	"strings"
)

// DefaultBodyLimit is the most bytes DecodeJSON reads from a request body:
// 1 MiB.
//
//line body.ego:14
const DefaultBodyLimit = 1 << 20

// BodyError is everything DecodeJSON can fail with. ProblemFor gives each
// case its response: 415, 413, 400 or 422 for the client's mistakes, and 500
// for BodyUnsupportedType, the API's.
type BodyError interface {
	error
	isBodyError()
}

type BodyMediaType struct{ ContentType string }

func (BodyMediaType) isBodyError() {}

func (e BodyMediaType) Error() string {
	return fmt.Sprintf("unsupported Content-Type %q: send application/json", e.ContentType)
}

// As lets pointers to BodyMediaType match as BodyMediaType.
func (e BodyMediaType) As(target any) bool {
	if t, ok := target.(*BodyMediaType); ok {
		*t = e
		return true
	}
	return false
}

type BodyTooLarge struct{ Limit int64 }

func (BodyTooLarge) isBodyError() {}

func (e BodyTooLarge) Error() string {
	return fmt.Sprintf("the request body is larger than %v bytes", e.Limit)
}

// As lets pointers to BodyTooLarge match as BodyTooLarge.
func (e BodyTooLarge) As(target any) bool {
	if t, ok := target.(*BodyTooLarge); ok {
		*t = e
		return true
	}
	return false
}

type BodyEmpty struct{}

func (BodyEmpty) isBodyError() {}

func (e BodyEmpty) Error() string { return "the request body is empty" }

// As lets pointers to BodyEmpty match as BodyEmpty.
func (e BodyEmpty) As(target any) bool {
	if t, ok := target.(*BodyEmpty); ok {
		*t = e
		return true
	}
	return false
}

type BodyMalformed struct {
	Offset int64
	Cause  error
}

func (BodyMalformed) isBodyError() {}

func (e BodyMalformed) Error() string { return fmt.Sprintf("malformed JSON at byte %v", e.Offset) }

func (e BodyMalformed) Unwrap() error { return e.Cause }

// As lets pointers to BodyMalformed match as BodyMalformed.
func (e BodyMalformed) As(target any) bool {
	if t, ok := target.(*BodyMalformed); ok {
		*t = e
		return true
	}
	return false
}

type BodyInvalid struct {
	Pointer string
	Cause   error
}

func (BodyInvalid) isBodyError() {}

func (e BodyInvalid) Error() string { return fmt.Sprintf("invalid JSON value at %q", e.Pointer) }

func (e BodyInvalid) Unwrap() error { return e.Cause }

// As lets pointers to BodyInvalid match as BodyInvalid.
func (e BodyInvalid) As(target any) bool {
	if t, ok := target.(*BodyInvalid); ok {
		*t = e
		return true
	}
	return false
}

type BodyUnreadable struct{ Cause error }

func (BodyUnreadable) isBodyError() {}

func (e BodyUnreadable) Error() string { return "could not read the request body" }

func (e BodyUnreadable) Unwrap() error { return e.Cause }

// As lets pointers to BodyUnreadable match as BodyUnreadable.
func (e BodyUnreadable) As(target any) bool {
	if t, ok := target.(*BodyUnreadable); ok {
		*t = e
		return true
	}
	return false
}

type BodyUnsupportedType struct{ Cause error }

func (BodyUnsupportedType) isBodyError() {}

func (e BodyUnsupportedType) Error() string { return "the request body's Go type has no JSON form" }

func (e BodyUnsupportedType) Unwrap() error { return e.Cause }

// As lets pointers to BodyUnsupportedType match as BodyUnsupportedType.
func (e BodyUnsupportedType) As(target any) bool {
	if t, ok := target.(*BodyUnsupportedType); ok {
		*t = e
		return true
	}
	return false
}

// DecodeJSON reads the JSON body of r into v, which must be a non-nil
// pointer:
//   - the Content-Type must be application/json, or end in +json;
//   - the body must be one JSON value of at most DefaultBodyLimit bytes;
//   - names match struct fields exactly, case included; members with no
//     field are ignored.
//
// Its errors are the BodyError cases, checked in that order: a body too
// large is a BodyTooLarge even if it is malformed too, and malformed JSON is
// a BodyMalformed even if a value doesn't fit its field. A BodyDecoder has
// other settings.
//
//line body.ego:37
func DecodeJSON(w http.ResponseWriter, r *http.Request, v any) error {
	return BodyDecoder{}.Decode(w, r, v)
}

// BodyDecoder decodes JSON request bodies with settings other than
// DecodeJSON's.
type BodyDecoder struct {
	// Limit is the most bytes read from a body; zero means DefaultBodyLimit.
	Limit int64
	// RejectUnknown makes a member with no matching field a BodyInvalid,
	// instead of ignoring it.
	RejectUnknown bool
}

// Decode reads the JSON body of r into v, as DecodeJSON does, with d's
// settings. A body too large also makes the response close the connection,
// since the rest of it is left unread.
func (d BodyDecoder) Decode(w http.ResponseWriter, r *http.Request, v any) error {
	ct := r.Header.Get("Content-Type")
	if !isJSON(ct) {
		return BodyMediaType{ContentType: ct}
	}
	limit := d.Limit
	if limit <= 0 {
		limit = DefaultBodyLimit
	}
	body := r.Body
	if body == nil {
		body = http.NoBody
	}
	b, err := io.ReadAll(http.MaxBytesReader(w, body, limit))
	if _, ok := errors.AsType[*http.MaxBytesError](err); ok {
		if w != nil {
			w.Header().Set("Connection", "close")
		}
		return BodyTooLarge{Limit: limit}
	}
	if err != nil {
		return BodyUnreadable{Cause: err}
	}
	if len(bytes.Trim(b, " \t\r\n")) == 0 {
		return BodyEmpty{}
	}
	if offset, cause := syntaxError(b); cause != nil {
		return BodyMalformed{Offset: offset, Cause: cause}
	}
	return valueError(json.Unmarshal(b, v, json.RejectUnknownMembers(d.RejectUnknown)))
}

// isJSON reports whether a Content-Type is JSON: application/json, or a type
// ending in +json such as application/merge-patch+json.
func isJSON(contentType string) bool {
	t, _, err := mime.ParseMediaType(contentType)
	return err == nil && (t == "application/json" || strings.HasSuffix(t, "+json"))
}

var errTrailingData = errors.New("unexpected data after the JSON value")

// syntaxError returns where b stops being one well-formed JSON value, and
// why, or a nil cause if it is one.
func syntaxError(b []byte) (offset int64, cause error) {
	dec := jsontext.NewDecoder(bytes.NewReader(b))
	if _, err := dec.ReadValue(); err != nil {
		if se, ok := errors.AsType[*jsontext.SyntacticError](err); ok {
			return se.ByteOffset, err
		}
		return dec.InputOffset(), err
	}
	end := dec.InputOffset()
	if _, err := dec.ReadToken(); err != io.EOF {
		rest := b[end:]
		return end + int64(len(rest)-len(bytes.TrimLeft(rest, " \t\r\n"))), errTrailingData
	}
	return 0, nil
}

// valueError is the case for an error from unmarshaling well-formed JSON.
func valueError(err error) error {
	if err == nil {
		return nil
	}
	if se, ok := errors.AsType[*json.SemanticError](err); ok {
		if se.GoType != nil && undecodable(se.GoType) {
			return BodyUnsupportedType{Cause: err}
		}
		return BodyInvalid{Pointer: string(se.JSONPointer), Cause: err}
	}
	if se, ok := errors.AsType[*jsontext.SyntacticError](err); ok {
		return BodyMalformed{Offset: se.ByteOffset, Cause: err}
	}
	return BodyInvalid{Cause: err}
}

// bodyProblem is the response to each case. err is declared as a BodyError,
// so the match needs no _ arm, and a new case doesn't compile until it has a
// response.
func bodyProblem(err error) Problem {
	var v Problem
	if err == nil {
		v = Problem{}
	} else if e, ok := errors.AsType[BodyMediaType](err); ok {
		v = Problem{Status: http.StatusUnsupportedMediaType, Detail: e.Error()}
	} else if e, ok := errors.AsType[BodyTooLarge](err); ok {
		v = Problem{Status: http.StatusRequestEntityTooLarge, Detail: e.Error()}
	} else if e, ok := errors.AsType[BodyEmpty](err); ok {
		v = Problem{Status: http.StatusBadRequest, Detail: e.Error()}
	} else if e, ok := errors.AsType[BodyMalformed](err); ok {
		v = Problem{Status: http.StatusBadRequest, Detail: fmt.Sprintf("%s: %s", e.Error(), syntaxReason(e.Cause))}
	} else if e, ok := errors.AsType[BodyInvalid](err); ok {
		v = invalidBody(e)
	} else if e, ok := errors.AsType[BodyUnreadable](err); ok {
		v = Problem{Status: http.StatusBadRequest, Detail: e.Error()}
	} else if _, ok := errors.AsType[BodyUnsupportedType](err); ok {
		v = Problem{Status: http.StatusInternalServerError}
	} else {
		panic(err)
	}
	return v
}

// invalidBody is the 422 for a value that doesn't fit its field, with a
// violation pointing at it.
//
//line body.ego:157
func invalidBody(e BodyInvalid) Problem {
	return Problem{
		Status: http.StatusUnprocessableEntity,
		Detail: "the request body has an invalid value",
		Errors: []Violation{{Pointer: "#" + e.Pointer, Detail: semanticReason(e.Cause)}},
	}
}
