// Code generated by ego generate from events_test.ego. DO NOT EDIT.

package httpkernel_test

import (
	"bytes"
	"context"
	"errors"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/goncini/goncini/event"
	"github.com/goncini/goncini/httpkernel"
)

// TestKernelEvents checks the kernel's events: a request listener that
// answers, an error listener that changes the problem, and a response
// listener that sees what was sent.
//
//line events_test.ego:19
func TestKernelEvents(t *testing.T) {
	d := event.New()
	maintenance := false
	event.On(d, func(ctx context.Context, e *httpkernel.RequestEvent) error {
		if maintenance && e.Request.URL.Path != "/health" {
			return httpkernel.Problem{Status: http.StatusServiceUnavailable, Detail: "down for maintenance"}
		}
		return nil
	})
	var reported []error
	event.On(d, func(ctx context.Context, e *httpkernel.ErrorEvent) error {
		reported = append(reported, e.Err)
		e.Problem.Detail += " (reported)"
		return nil
	})
	var sent []int
	event.On(d, func(ctx context.Context, e *httpkernel.ResponseEvent) error {
		sent = append(sent, e.Status)
		return errors.New("a failing listener is only logged")
	})
	k := &httpkernel.Kernel{
		Handler: http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if r.URL.Path == "/fail" {
				httpkernel.WriteError(w, r, httpkernel.Problem{Status: http.StatusConflict, Detail: "taken"})
				return
			}
			w.Write([]byte("ok"))
		}),
		Events: d,
	}
	k.Logger, _ = logged()
	get := func(path string) *httptest.ResponseRecorder {
		w := httptest.NewRecorder()
		k.ServeHTTP(w, httptest.NewRequest(http.MethodGet, path, nil))
		return w
	}
	if w := get("/"); w.Code != 200 {
		t.Errorf("/: %d", w.Code)
	}
	if w := get("/fail"); w.Code != 409 || !strings.Contains(w.Body.String(), "taken (reported)") {
		t.Errorf("/fail: %d %s", w.Code, w.Body)
	}
	maintenance = true
	if w := get("/"); w.Code != 503 || !strings.Contains(w.Body.String(), "down for maintenance (reported)") {
		t.Errorf("maintenance: %d %s", w.Code, w.Body)
	}
	if w := get("/health"); w.Code != 200 {
		t.Errorf("/health: %d", w.Code)
	}
	if len(reported) != 2 || len(sent) != 4 || sent[1] != 409 || sent[2] != 503 {
		t.Errorf("reported %v, sent %v", reported, sent)
	}
}

// TestResponseEventEdges checks that a panicking response listener is
// logged, and that an aborted response has no status.
func TestResponseEventEdges(t *testing.T) {
	d := event.New()
	var statuses []int
	event.On(d, func(ctx context.Context, e *httpkernel.ResponseEvent) error {
		statuses = append(statuses, e.Status)
		panic("boom")
	})
	k := &httpkernel.Kernel{Handler: http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		panic(http.ErrAbortHandler)
	}), Events: d}
	var logs *bytes.Buffer
	k.Logger, logs = logged()
	func() {
		defer func() {
			if v := recover(); v != http.ErrAbortHandler {
				t.Errorf("recovered %v", v)
			}
		}()
		k.ServeHTTP(httptest.NewRecorder(), httptest.NewRequest(http.MethodGet, "/", nil))
	}()
	if len(statuses) != 1 || statuses[0] != 0 || !strings.Contains(logs.String(), "panicked") {
		t.Errorf("statuses %v, logs %s", statuses, logs)
	}
}
