// Code generated by ego generate from hosts_test.ego. DO NOT EDIT.

package httpkernel_test

import (
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/goncini/goncini/httpkernel"
)

//line hosts_test.ego:12
func TestTrustHosts(t *testing.T) {
	trust, err := httpkernel.TrustHosts("api.example.com", "*.example.net", "127.0.0.1", "[::1]")
	if err != nil {
		panic(err)
	}
//line hosts_test.ego:14
	proxies, err := httpkernel.TrustProxies("10.0.0.0/8")
	if err != nil {
		panic(err)
	}
//line hosts_test.ego:15
	k := &httpkernel.Kernel{
		Handler: http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		}),
		Middleware: []httpkernel.Middleware{proxies.Middleware, trust},
	}
//line hosts_test.ego:19
	for host, want := range map[string]int{
		"api.example.com":      200,
		"API.Example.com:8443": 200,
		"api.example.com.":     200,
		"eu.example.net":       200,
		"a.b.example.net":      200,
		"127.0.0.1:8080":       200,
		"[::1]:8080":           200,
		"example.net":          400, // *. is for subdomains only
		"evil.com":             400,
		"api.example.com.evil": 400,
		"notexample.net":       400,
	} {
		r := httptest.NewRequest(http.MethodGet, "/", nil)
		r.Host = host
		rec := httptest.NewRecorder()
		k.ServeHTTP(rec, r)
		if rec.Code != want {
			t.Errorf("Host %s: %d %s, want %d", host, rec.Code, rec.Body, want)
		}
		if want == 400 && !strings.Contains(rec.Body.String(), `"detail":"untrusted host`) {
			t.Errorf("Host %s: %s", host, rec.Body)
		}
	}

	// The host a trusted proxy reports is the one checked.
	r := httptest.NewRequest(http.MethodGet, "http://api.example.com/", nil)
	r.RemoteAddr = "10.0.0.5:80"
	r.Header.Set("X-Forwarded-For", "198.51.100.9")
	r.Header.Set("X-Forwarded-Host", "evil.com")
	rec := httptest.NewRecorder()
	k.ServeHTTP(rec, r)
	if rec.Code != 400 {
		t.Errorf("forwarded evil.com: %d", rec.Code)
	}

	for _, bad := range []string{"", "*.", "api.example.com:443", "*.*.example.com", "exa mple.com", "http://example.com"} {
		if _, err := httpkernel.TrustHosts(bad); err == nil {
			t.Errorf("TrustHosts(%q) accepted it", bad)
		}
	}
}
