// Code generated by ego generate from optional_test.ego. DO NOT EDIT.

package httpkernel_test

import (
	"context"
	"testing"

	"github.com/goncini/goncini/httpkernel"
)

//line optional_test.ego:10
func TestOptional(t *testing.T) {
	type input struct {
		Body struct {
			Bio   httpkernel.Optional[string]   `json:"bio"`
			Email httpkernel.Optional[string]   `json:"email"`
			Tags  httpkernel.Optional[[]string] `json:"tags"`
		}
	}
	var got input
	k := &httpkernel.Kernel{Handler: httpkernel.Endpoint(func(ctx context.Context, in input) (httpkernel.NoContent, error) {
		got = in
		return httpkernel.NoContent{}, nil
	})}
	rec := do(k, "PUT", "/", `{"bio":null,"tags":["go"]}`)
	if rec.Code != 204 {
		t.Fatalf("%d %s", rec.Code, rec.Body)
	}
	b := got.Body
	if !b.Bio.Set || !b.Bio.Null || b.Bio.Present() || b.Email.Set || !b.Tags.Present() || b.Tags.Value[0] != "go" {
		t.Errorf("decoded %+v", b)
	}
	if rec := do(k, "PUT", "/", `{"email":1}`); rec.Code != 422 || problem(t, rec).Errors[0].Pointer != "#/email" {
		t.Errorf("a number for a string: %d %s", rec.Code, rec.Body)
	}
}
