// Code generated by ego generate from server.ego. DO NOT EDIT.

package httpkernel

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"net"
	"net/http"
	"time"

	"github.com/effect-go/effect-go/scope"
)

// Server serves a handler, usually a Kernel, until its context is done, then
// shuts down gracefully: it stops accepting connections and waits for the
// requests in flight, up to ShutdownTimeout. Its zero values are safe
// defaults.
//
//	func main() {
//		srv := &httpkernel.Server{Addr: ":8080", Handler: kernel}
//		scope.Main(func(s *scope.Scope) error { return srv.ListenAndServe(s.Context()) })
//	}
//
//line server.ego:15
type Server struct {
	// Addr is the TCP address to listen on, such as ":8080"; empty means
	// ":http".
	Addr string
	// Handler serves the requests.
	Handler http.Handler
	// ReadHeaderTimeout bounds the time to read a request's headers; zero
	// means 10 seconds, so slow clients can't hold connections.
	ReadHeaderTimeout time.Duration
	// ReadTimeout bounds the time to read a whole request; zero means none.
	ReadTimeout time.Duration
	// WriteTimeout bounds the time to write a response; zero means none.
	WriteTimeout time.Duration
	// IdleTimeout bounds how long a kept-alive connection waits for its next
	// request; zero means 2 minutes.
	IdleTimeout time.Duration
	// ShutdownTimeout bounds how long shutting down waits for the requests
	// in flight; zero means 30 seconds.
	ShutdownTimeout time.Duration
	// MaxHeaderBytes limits the size of request headers; zero means
	// http.DefaultMaxHeaderBytes.
	MaxHeaderBytes int
	// Logger logs the address served and the server's own errors, such as
	// failed TLS handshakes; nil means slog.Default().
	Logger *slog.Logger
}

// ListenAndServe listens on s.Addr, then serves until ctx is done, as Serve
// does.
func (s *Server) ListenAndServe(ctx context.Context) error {
	var addr string
	if s.Addr != "" {
		addr = s.Addr
	} else {
		addr = ":http"
	}
//line server.ego:55
	var lc net.ListenConfig
	ln, err := lc.Listen(ctx, "tcp", addr)
	if err != nil {
		return err
	}
//line server.ego:57
	return s.Serve(ctx, ln)
}

// Serve serves on ln until ctx is done, then shuts down. Requests keep the
// values of ctx but aren't cancelled with it, so those in flight can finish.
//
// Serve returns nil after a clean shutdown. It returns an error if the
// server fails, or if requests are still running at ShutdownTimeout: their
// connections are then closed.
func (s *Server) Serve(ctx context.Context, ln net.Listener) error {
	logger := s.Logger
	if logger == nil {
		logger = slog.Default()
	}
//line server.ego:68
	srv := &http.Server{
		Handler:           s.Handler,
		ReadHeaderTimeout: orDefault(s.ReadHeaderTimeout, 10*time.Second),
		ReadTimeout:       s.ReadTimeout,
		WriteTimeout:      s.WriteTimeout,
		IdleTimeout:       orDefault(s.IdleTimeout, 2*time.Minute),
		MaxHeaderBytes:    s.MaxHeaderBytes,
		BaseContext:       func(net.Listener) context.Context { return context.WithoutCancel(ctx) },
		ErrorLog:          slog.NewLogLogger(logger.Handler(), slog.LevelError),
	}
	logger.InfoContext(ctx, "serving HTTP", slog.String("addr", ln.Addr().String()))
	_, err := scope.Run[struct{}](ctx, func(sc *scope.Scope) (struct{}, error) {
		serving := scope.Fork[struct{}](sc, func(_ context.Context) (struct{}, error) {
			if err := srv.Serve(ln); !errors.Is(err, http.ErrServerClosed) {
				return struct{}{}, err
			}
			return struct{}{}, nil
		})
		select {
		case <-serving.Done():
			return serving.Join() // the server failed before ctx was done
		case <-ctx.Done():
		}
		timeout := orDefault(s.ShutdownTimeout, 30*time.Second)
		sctx, cancel := context.WithTimeout(context.WithoutCancel(ctx), timeout)
		defer cancel()
		var stuck error
		if err := srv.Shutdown(sctx); err != nil {
			srv.Close()
			stuck = fmt.Errorf("httpkernel: requests still running %v after shutdown began: their connections were closed", timeout)
		}
		_, err := serving.Join()
		return struct{}{}, errors.Join(stuck, err)
	})
	return err
}

// orDefault returns d, or def if d is zero.
func orDefault(d, def time.Duration) time.Duration {
	var v time.Duration
	if d == 0 {
		v = def
	} else {
		v = d
	}
	return v
}
