// Code generated by ego generate from dialect_test.ego. DO NOT EDIT.

package db_test

import (
	"database/sql"
	"testing"

	_ "modernc.org/sqlite"

	"github.com/goncini/goncini/db"
)

//line dialect_test.ego:12
func TestDialect(t *testing.T) {
	sqlite, err := sql.Open("sqlite", ":memory:")
	if err != nil {
		panic(err)
	}
//line dialect_test.ego:14
	words, err := sql.Open("words", "")
	if err != nil {
		panic(err)
	}
//line dialect_test.ego:15
	if db.DialectOf(sqlite) != db.SQLite || db.DialectOf(words) != db.Unknown {
		t.Errorf("dialects %v, %v", db.DialectOf(sqlite), db.DialectOf(words))
	}
	query := `SELECT '?' FROM "a?b" WHERE x = ? AND y = ?`
	if got := db.PostgreSQL.Rebind(query); got != `SELECT '?' FROM "a?b" WHERE x = $1 AND y = $2` {
		t.Errorf("PostgreSQL: %s", got)
	}
	if got := db.SQLite.Rebind(query); got != query {
		t.Errorf("SQLite: %s", got)
	}
}
