// Code generated by ego generate from app_test.ego. DO NOT EDIT.

package app_test

import (
	"context"
	"errors"
	"testing"

	"github.com/goncini/goncini"

	"github.com/goncini/goncini/examples/articles/app"
	"github.com/goncini/goncini/examples/articles/config"

	"github.com/effect-go/effect-go/scope"
)

// TestEnvironments builds the app in each environment, which checks that
// their configs have no missing secret and are values goncini accepts.
//
//line app_test.ego:16
func TestEnvironments(t *testing.T) {
	for _, name := range []string{"dev", "test", "prod"} {
		env := goncini.NewEnv(name, nil)
		cfg := config.Load(env)
		if err := env.Err(); err != nil {
			t.Errorf("%s: %v", name, err)
			continue
		}
		_, err := scope.Run(context.Background(), func(s *scope.Scope) (*goncini.App, error) { return app.Build(s.Context(), s, cfg) })
		if err != nil {
			t.Errorf("%s: %v", name, err)
		}
	}
	env := goncini.NewEnv("prdo", nil)
	config.Load(env)
	if _, ok := errors.AsType[goncini.UnknownEnv](env.Err()); !ok {
		t.Errorf("APP_ENV=prdo: %v", env.Err())
	}
}
