// Code generated by ego generate. DO NOT EDIT.

//go:build !egolayers

package app

import (
	"context"
	"fmt"
	"time"

	"github.com/effect-go/effect-go/scope"
	"github.com/goncini/goncini"
	"github.com/goncini/goncini/db"
	"github.com/goncini/goncini/examples/articles/articles"
	"github.com/goncini/goncini/examples/articles/config"
)

// Build builds the app for cfg.
func Build(ctx context.Context, s *scope.Scope, cfg config.Config) (*goncini.App, error) {
	http := httpConfig(cfg)
	config2 := dbConfig(cfg)
	db2, cleanup, err := db.Open(config2)
	if err != nil {
		return nil, fmt.Errorf("db.Open: %w", err)
	}
	s.Defer(func(context.Context) error { return cleanup() })
	sql2 := db.NewSQL(db2)
	store := articles.NewStore(sql2)
	v := clock()
	articles2 := articles.NewArticles(store, v)
	v2 := routes(articles2)
	router := goncini.NewRouter(v2)
	v3 := goncini.NewMiddleware()
	v4 := problems()
	renderer := goncini.NewRenderer()
	validator := goncini.NewValidator()
	log := logConfig(cfg)
	logger := goncini.NewLogger(log)
	kernel, err := goncini.NewKernel(http, router, v3, v4, renderer, validator, logger)
	if err != nil {
		return nil, fmt.Errorf("NewKernel: %w", err)
	}
	server := goncini.NewServer(http, kernel, logger)
	slugCommand := articles.NewSlugCommand(articles2)
	migrator2, err := migrator(db2)
	if err != nil {
		return nil, fmt.Errorf("migrator: %w", err)
	}
	v5 := commands(slugCommand, migrator2)
	v6 := checks(db2)
	app := goncini.NewApp(kernel, server, router, v5, v6, logger)
	return app, nil
}

// BuildTest builds the app with a test's clock.
func BuildTest(ctx context.Context, s *scope.Scope, cfg config.Config, now func() time.Time) (*goncini.App, error) {
	http := httpConfig(cfg)
	config2 := dbConfig(cfg)
	db2, cleanup, err := db.Open(config2)
	if err != nil {
		return nil, fmt.Errorf("db.Open: %w", err)
	}
	s.Defer(func(context.Context) error { return cleanup() })
	sql2 := db.NewSQL(db2)
	store := articles.NewStore(sql2)
	articles2 := articles.NewArticles(store, now)
	v := routes(articles2)
	router := goncini.NewRouter(v)
	v2 := goncini.NewMiddleware()
	v3 := problems()
	renderer := goncini.NewRenderer()
	validator := goncini.NewValidator()
	log := logConfig(cfg)
	logger := goncini.NewLogger(log)
	kernel, err := goncini.NewKernel(http, router, v2, v3, renderer, validator, logger)
	if err != nil {
		return nil, fmt.Errorf("NewKernel: %w", err)
	}
	server := goncini.NewServer(http, kernel, logger)
	slugCommand := articles.NewSlugCommand(articles2)
	migrator2, err := migrator(db2)
	if err != nil {
		return nil, fmt.Errorf("migrator: %w", err)
	}
	v4 := commands(slugCommand, migrator2)
	v5 := checks(db2)
	app := goncini.NewApp(kernel, server, router, v4, v5, logger)
	return app, nil
}
