// Code generated by ego generate. DO NOT EDIT.

//go:build !egolayers

package app

import (
	"context"
	"fmt"

	"github.com/effect-go/effect-go/scope"
	"github.com/goncini/goncini"
	"github.com/goncini/goncini/examples/articles/articles"
	"github.com/goncini/goncini/examples/articles/config"
	"time"
)

// Build builds the app for cfg.
func Build(ctx context.Context, s *scope.Scope, cfg config.Config) (*goncini.App, error) {
	http := httpConfig(cfg)
	v := clock()
	articles := articles.NewArticles(v)
	v2 := routes(articles)
	router := goncini.NewRouter(v2)
	v3 := problems()
	log := logConfig(cfg)
	logger := goncini.NewLogger(log)
	kernel, err := goncini.NewKernel(http, router, v3, logger)
	if err != nil {
		return nil, fmt.Errorf("goncini.NewKernel: %w", err)
	}
	server := goncini.NewServer(http, kernel, logger)
	v4 := commands()
	app := goncini.NewApp(kernel, server, router, v4, logger)
	return app, nil
}

// BuildTest builds the app with a test's clock.
func BuildTest(ctx context.Context, s *scope.Scope, cfg config.Config, now func() time.Time) (*goncini.App, error) {
	http := httpConfig(cfg)
	articles := articles.NewArticles(now)
	v := routes(articles)
	router := goncini.NewRouter(v)
	v2 := problems()
	log := logConfig(cfg)
	logger := goncini.NewLogger(log)
	kernel, err := goncini.NewKernel(http, router, v2, logger)
	if err != nil {
		return nil, fmt.Errorf("goncini.NewKernel: %w", err)
	}
	server := goncini.NewServer(http, kernel, logger)
	v3 := commands()
	app := goncini.NewApp(kernel, server, router, v3, logger)
	return app, nil
}
