// Code generated by ego generate. DO NOT EDIT.

//go:build !egolayers

package app

import (
	"context"
	"fmt"
	"time"

	"github.com/effect-go/effect-go/scope"
	"github.com/goncini/goncini"
	"github.com/goncini/goncini/db"
	"github.com/goncini/goncini/examples/articles/articles"
	"github.com/goncini/goncini/examples/articles/config"
)

// Build builds the app for cfg.
func Build(ctx context.Context, s *scope.Scope, cfg config.Config) (*goncini.App, error) {
	http := autoConfigHTTP(cfg)
	config2 := autoConfigDB(cfg)
	db2, cleanup, err := db.Open(config2)
	if err != nil {
		return nil, fmt.Errorf("db.Open: %w", err)
	}
	s.Defer(func(context.Context) error { return cleanup() })
	sql2 := db.NewSQL(db2)
	store := articles.NewStore(sql2)
	v := clock()
	articles2 := articles.NewArticles(store, v)
	v2 := autoRoutes(articles2)
	router := goncini.NewRouter(v2)
	v3 := goncini.NewMiddleware()
	v4 := autoProblems()
	renderer := goncini.NewRenderer()
	validator := goncini.NewValidator()
	log := autoConfigLog(cfg)
	handler := goncini.NewLogHandler(log)
	logger := goncini.NewLogger(handler)
	kernel, err := goncini.NewKernel(http, router, v3, v4, renderer, validator, logger)
	if err != nil {
		return nil, fmt.Errorf("NewKernel: %w", err)
	}
	server := goncini.NewServer(http, kernel, logger)
	slugCommand := articles.NewSlugCommand(articles2)
	migrator2, err := migrator(db2)
	if err != nil {
		return nil, fmt.Errorf("migrator: %w", err)
	}
	v5 := autoCommands(slugCommand, migrator2)
	v6 := autoChecks(db2)
	v7 := autoServices()
	config3 := autoDefaultOpenapiConfig()
	annotations := autoOpenAPI()
	document, err := goncini.NewOpenAPI(config3, router, kernel, annotations)
	if err != nil {
		return nil, fmt.Errorf("NewOpenAPI: %w", err)
	}
	app := goncini.NewApp(kernel, server, router, v5, v6, v7, logger, document)
	return app, nil
}

// BuildTest builds the app with a test's clock.
func BuildTest(ctx context.Context, s *scope.Scope, cfg config.Config, now func() time.Time) (*goncini.App, error) {
	http := autoConfigHTTP(cfg)
	config2 := autoConfigDB(cfg)
	db2, cleanup, err := db.Open(config2)
	if err != nil {
		return nil, fmt.Errorf("db.Open: %w", err)
	}
	s.Defer(func(context.Context) error { return cleanup() })
	sql2 := db.NewSQL(db2)
	store := articles.NewStore(sql2)
	articles2 := articles.NewArticles(store, now)
	v := autoRoutes(articles2)
	router := goncini.NewRouter(v)
	v2 := goncini.NewMiddleware()
	v3 := autoProblems()
	renderer := goncini.NewRenderer()
	validator := goncini.NewValidator()
	log := autoConfigLog(cfg)
	handler := goncini.NewLogHandler(log)
	logger := goncini.NewLogger(handler)
	kernel, err := goncini.NewKernel(http, router, v2, v3, renderer, validator, logger)
	if err != nil {
		return nil, fmt.Errorf("NewKernel: %w", err)
	}
	server := goncini.NewServer(http, kernel, logger)
	slugCommand := articles.NewSlugCommand(articles2)
	migrator2, err := migrator(db2)
	if err != nil {
		return nil, fmt.Errorf("migrator: %w", err)
	}
	v4 := autoCommands(slugCommand, migrator2)
	v5 := autoChecks(db2)
	v6 := autoServices()
	config3 := autoDefaultOpenapiConfig()
	annotations := autoOpenAPI()
	document, err := goncini.NewOpenAPI(config3, router, kernel, annotations)
	if err != nil {
		return nil, fmt.Errorf("NewOpenAPI: %w", err)
	}
	app := goncini.NewApp(kernel, server, router, v4, v5, v6, logger, document)
	return app, nil
}
