// Code generated by ego generate from notices_test.ego. DO NOT EDIT.

package moderation_test

import (
	"bytes"
	"encoding/json/v2"
	stdmime "mime"
	"net/http"
	"net/http/httptest"
	"net/mail"
	"sync"
	"testing"

	"github.com/goncini/goncini/mailer/mailertest"
	"github.com/goncini/goncini/webtest"

	"github.com/goncini/goncini/examples/realworld/app"
	"github.com/goncini/goncini/examples/realworld/config"
)

// TestRemovalNotices is M4's fourth gate: when a moderator removes an
// article, its author is told by email, and the moderators' chat hears of
// it, each a delivery of its own, sent by a worker.
//
//line notices_test.ego:23
func TestRemovalNotices(t *testing.T) {
	var mu sync.Mutex
	var chat []string
	hook := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		var msg struct {
			Text string `json:"text"`
		}
		json.UnmarshalRead(r.Body, &msg)
		mu.Lock()
		chat = append(chat, msg.Text)
		mu.Unlock()
	}))
	defer hook.Close()
	smtp := mailertest.NewServer(t)
	t.Setenv("MODERATORS_CHAT_URL", hook.URL)
	t.Setenv("MAILER_DSN", smtp.DSN())

	a := webtest.Boot(t, config.Load, app.Build)
	webtest.Run(t, a, "db:migrate")
	c := webtest.NewClient(t, a)
	var bob struct {
		User struct {
			Token string `json:"token"`
		} `json:"user"`
	}
	c.Post("/api/users", `{"user":{"username":"bob","email":"bob@example.com","password":"a password"}}`).Status(201).JSON(&bob)
	author := c.WithHeader("Authorization", "Token "+bob.User.Token)
	author.Post("/api/articles", `{"article":{"title":"Spam","description":"d","body":"b"}}`).Status(201)
	author.Post("/api/articles", `{"article":{"title":"Draft","description":"d","body":"b"}}`).Status(201)
	webtest.Run(t, a, "messenger:consume", "-drain") // the welcome email
	author.Delete("/api/articles/draft").Status(204) // its author's: no notice
	c.WithHeader("Authorization", "Bearer "+moderatorKey).Delete("/api/admin/articles/spam").Status(204)
	if len(chat) != 0 {
		t.Fatal("delivered in the request")
	}
	webtest.Run(t, a, "messenger:consume", "-drain")

	if len(chat) != 1 || chat[0] != "*Your article “Spam” was removed*\nmoderator, a moderator, removed bob’s article “Spam”, which breaks the rules." {
		t.Errorf("chat %q", chat)
	}
	got := smtp.Messages()
	if len(got) != 2 || got[1].To[0] != "bob@example.com" {
		t.Fatalf("emails %+v", got)
	}
	msg, err := mail.ReadMessage(bytes.NewReader(got[1].Data))
	if err != nil {
		panic(err)
	}
//line notices_test.ego:68
	subject, err := new(stdmime.WordDecoder).DecodeHeader(msg.Header.Get("Subject"))
	if err != nil {
		panic(err)
	}
//line notices_test.ego:69
	if subject != "Your article “Spam” was removed" {
		t.Errorf("subject %q", subject)
	}
}
