// Code generated by ego generate from commands.ego. DO NOT EDIT.

package articles

import (
	"context"
	"flag"
	"fmt"
	"io"

	"github.com/goncini/goncini/console"
	"github.com/goncini/goncini/routing"
)

// SlugCommand prints the slug that each title gets, or the URL of its
// article.
//
//line commands.ego:15
type SlugCommand struct {
	articles *Articles
	url      bool
}

func NewSlugCommand(a *Articles) *SlugCommand {
	return &SlugCommand{articles: a}
}

func (*SlugCommand) Name() string    { return "articles:slug" }
func (*SlugCommand) Summary() string { return "Prints the slug of each title given" }

func (c *SlugCommand) Flags(fs *flag.FlagSet) {
	fs.BoolVar(&c.url, "url", false, "print the URL of the article instead")
}

func (c *SlugCommand) Run(ctx context.Context, out io.Writer, titles []string) error {
	if len(titles) == 0 {
		return console.Usage{Command: c.Name(), Reason: "no title given"}
	}
	for _, title := range titles {
		slug := slugify(title)
		if slug == "" {
			return console.Usage{Command: c.Name(), Reason: fmt.Sprintf("%q needs a letter or a digit", title)}
		}
		if c.url {
			v, err := c.articles.show.URL(routing.Params{"slug": slug})
			if err != nil {
				panic(err)
			}
			slug = v
		}
//line commands.ego:43
		if _, err := fmt.Fprintln(out, slug); err != nil {
			return err
		}
	}
	return nil
}
