// Code generated by ego generate from commands_test.ego. DO NOT EDIT.

package articles_test

import (
	"bytes"
	"context"
	"strings"
	"testing"

	"github.com/goncini/goncini/console"
)

//line commands_test.ego:12
func TestSlugCommand(t *testing.T) {
	a := boot(t)
	run := func(args string) (string, error) {
		var out bytes.Buffer
		err := console.Run(context.Background(), &out, a.Commands, "", strings.Fields(args))
		return out.String(), err
	}
	for args, want := range map[string]string{
		"articles:slug Hello, World!": "hello\nworld\n",
		"articles:slug -url Café":     "/articles/caf%C3%A9\n",
	} {
		if out, err := run(args); err != nil || out != want {
			t.Errorf("%s: %q %v, want %q", args, out, err, want)
		}
	}
	for _, args := range []string{"articles:slug", "articles:slug !?", "articles:slug -x y"} {
		if _, err := run(args); !console.IsUsage(err) {
			t.Errorf("%s: %v, want a usage error", args, err)
		}
	}
}
