// Code generated by ego generate from controller.ego. DO NOT EDIT.

package articles

import (
	"context"
	"strings"

	"github.com/goncini/goncini/httpkernel"
	"github.com/goncini/goncini/routing"

	"github.com/effect-go/effect-go/trace"
)

// Routes registers the endpoints, and keeps the route of an article to build
// its URL. Each effect method compiles to a func(ctx, In) (Out, error),
// which httpkernel.Endpoint serves.
//
//line controller.ego:13
func (a *Articles) Routes(r *routing.Router) {
	r.Get("/articles", httpkernel.Endpoint(a.List)).Name("article_list")
	a.show = r.Get("/articles/{slug}", httpkernel.Endpoint(a.Show)).Name("article_show")
	r.Post("/articles", httpkernel.Endpoint(a.Create)).Name("article_create")
}

type ListInput struct {
	Tag   string `query:"tag"`
	Limit int    `query:"limit" default:"20" validate:"min=1,max=100"`
}

type ListOutput struct {
	Articles []Article `json:"articles"`
	Count    int       `json:"count"`
}

// List returns the newest articles first, with the tag if one is given.
func (a *Articles) List(ctx context.Context, in ListInput) (_ ListOutput, err error) {
	ctx, span := trace.Start(ctx, "articles.Articles.List")
	defer trace.End(span, &err)
//line controller.ego:31
	list, count, err := a.store.List(ctx, in.Tag, in.Limit)
	if err != nil {
		return ListOutput{}, Unavailable{Cause: err}
	}
//line controller.ego:32
	return ListOutput{Articles: list, Count: count}, nil
}

type ShowInput struct {
	Slug string `path:"slug"`
}

func (a *Articles) Show(ctx context.Context, in ShowInput) (_ Article, err error) {
	ctx, span := trace.Start(ctx, "articles.Articles.Show")
	defer trace.End(span, &err)
//line controller.ego:40
	art, ok, err := a.store.Get(ctx, in.Slug)
	if err != nil {
		return Article{}, Unavailable{Cause: err}
	}
//line controller.ego:41
	if !ok {
		return Article{}, NotFound{Slug: in.Slug}
	}
	return art, nil
}

type CreateInput struct {
	Body struct {
		Title string   `json:"title"`
		Body  string   `json:"body"`
		Tags  []string `json:"tags" validate:"max=5,dive,required"`
	}
}

// Validate checks what the validate tags can't express.
func (in *CreateInput) Validate() error {
	var vs []httpkernel.Violation
	if strings.TrimSpace(in.Body.Title) == "" {
		vs = append(vs, httpkernel.Violation{Pointer: "#/title", Detail: "can't be blank"})
	} else if slugify(in.Body.Title) == "" {
		vs = append(vs, httpkernel.Violation{Pointer: "#/title", Detail: "needs a letter or a digit"})
	}
	if strings.TrimSpace(in.Body.Body) == "" {
		vs = append(vs, httpkernel.Violation{Pointer: "#/body", Detail: "can't be blank"})
	}
	if len(vs) > 0 {
		return httpkernel.Invalid(vs...)
	}
	return nil
}

func (a *Articles) Create(ctx context.Context, in CreateInput) (_ httpkernel.Created[Article], err error) {
	ctx, span := trace.Start(ctx, "articles.Articles.Create")
	defer trace.End(span, &err)
//line controller.ego:73
	art := Article{Slug: slugify(in.Body.Title), Title: in.Body.Title, Body: in.Body.Body, Tags: in.Body.Tags, CreatedAt: a.now()}
	added, err := a.store.Add(ctx, art)
	if err != nil {
		return httpkernel.Created[Article]{}, Unavailable{Cause: err}
	}
//line controller.ego:75
	if !added {
		return httpkernel.Created[Article]{}, Duplicate{Slug: art.Slug}
	}
	// A URL that can't be built is a bug in this code, not in the request.
	loc, err := a.show.URL(routing.Params{"slug": art.Slug})
	if err != nil {
		panic(err)
	}
//line controller.ego:80
	return httpkernel.Created[Article]{Location: loc, Body: art}, nil
}
