// Code generated by ego generate from controller.ego. DO NOT EDIT.

package articles

import (
	"context"
	"errors"
	"strings"
	"time"

	"github.com/goncini/goncini/httpkernel"
	"github.com/goncini/goncini/listing"
	"github.com/goncini/goncini/routing"
	"github.com/goncini/goncini/uid"

	"github.com/effect-go/effect-go/trace"
)

// Routes registers the endpoints, and keeps the route of an article to build
// its URL. Each effect method compiles to a func(ctx, In) (Out, error),
// which httpkernel.Endpoint serves.
//
//line controller.ego:16
func (a *Articles) Routes(r *routing.Router) {
	r.Get("/articles", httpkernel.Endpoint(a.List)).Name("article_list")
	r.Get("/articles/{id}", httpkernel.Endpoint(a.ShowByID)).Name("article_show_by_id").Require("id", routing.UUID)
	a.show = r.Get("/articles/{slug}", httpkernel.Endpoint(a.Show)).Name("article_show")
	r.Post("/articles", httpkernel.Endpoint(a.Create)).Name("article_create")
}

type ListInput struct {
	listing.Window
	Sort listing.Sort[Order] `query:"sort" default:"-createdAt"`
	Tag  string              `query:"tag"` // only the articles with this tag
}

// Order is what lists of articles can be sorted by.
type Order struct{}

func (Order) Fields() map[string]string {
	return map[string]string{"createdAt": "created_at", "title": "title"}
}

// List returns a page of the articles, the newest first unless the sort
// says otherwise, with the tag if one is given.
func (a *Articles) List(ctx context.Context, in ListInput) (_ listing.Page[Article], err error) {
	ctx, span := trace.Start(ctx, "articles.Articles.List")
	defer trace.End(span, &err)
//line controller.ego:39
	list, count, err := a.store.List(ctx, in.Tag, in.Sort.SQL(), in.Limit, in.Offset)
	if err != nil {
		if _, ok := errors.AsType[ArticleError](err); ok {
			return listing.Page[Article]{}, err
		}
		return listing.Page[Article]{}, Unavailable{Cause: err}
	}
//line controller.ego:40
	return listing.Page[Article]{Items: list, Total: count, Window: in.Window}, nil
}

type IDInput struct {
	ID uid.UUID `path:"id"`
}

// ShowByID returns the article with the ID.
func (a *Articles) ShowByID(ctx context.Context, in IDInput) (_ Article, err error) {
	ctx, span := trace.Start(ctx, "articles.Articles.ShowByID")
	defer trace.End(span, &err)
//line controller.ego:49
	art, ok, err := a.store.ByID(ctx, in.ID)
	if err != nil {
		if _, ok := errors.AsType[ArticleError](err); ok {
			return Article{}, err
		}
		return Article{}, Unavailable{Cause: err}
	}
//line controller.ego:50
	if !ok {
		return Article{}, NotFound{Slug: in.ID.String()}
	}
	return art, nil
}

type ShowInput struct {
	Slug string `path:"slug"`
}

func (a *Articles) Show(ctx context.Context, in ShowInput) (_ Article, err error) {
	ctx, span := trace.Start(ctx, "articles.Articles.Show")
	defer trace.End(span, &err)
//line controller.ego:61
	art, ok, err := a.store.Get(ctx, in.Slug)
	if err != nil {
		if _, ok := errors.AsType[ArticleError](err); ok {
			return Article{}, err
		}
		return Article{}, Unavailable{Cause: err}
	}
//line controller.ego:62
	if !ok {
		return Article{}, NotFound{Slug: in.Slug}
	}
	return art, nil
}

type CreateInput struct {
	Body struct {
		Title string   `json:"title"`
		Body  string   `json:"body"`
		Tags  []string `json:"tags" validate:"max=5,dive,required"`
	}
}

// Validate checks what the validate tags can't express.
func (in *CreateInput) Validate() error {
	var vs []httpkernel.Violation
	if strings.TrimSpace(in.Body.Title) == "" {
		vs = append(vs, httpkernel.Violation{Pointer: "#/title", Detail: "can't be blank"})
	} else if slugify(in.Body.Title) == "" {
		vs = append(vs, httpkernel.Violation{Pointer: "#/title", Detail: "needs a letter or a digit"})
	}
	if strings.TrimSpace(in.Body.Body) == "" {
		vs = append(vs, httpkernel.Violation{Pointer: "#/body", Detail: "can't be blank"})
	}
	if len(vs) > 0 {
		return httpkernel.Invalid(vs...)
	}
	return nil
}

func (a *Articles) Create(ctx context.Context, in CreateInput) (_ httpkernel.Created[Article], err error) {
	ctx, span := trace.Start(ctx, "articles.Articles.Create")
	defer trace.End(span, &err)
	// The store keeps times to the microsecond: so does the response.
//line controller.ego:95
	created := a.now().Truncate(time.Microsecond)
	art := Article{ID: uid.NewV7(), Slug: slugify(in.Body.Title), Title: in.Body.Title, Body: in.Body.Body, Tags: in.Body.Tags, CreatedAt: created}
	added, err := a.store.Add(ctx, art)
	if err != nil {
		if _, ok := errors.AsType[ArticleError](err); ok {
			return httpkernel.Created[Article]{}, err
		}
		return httpkernel.Created[Article]{}, Unavailable{Cause: err}
	}
//line controller.ego:98
	if !added {
		return httpkernel.Created[Article]{}, Duplicate{Slug: art.Slug}
	}
	// A URL that can't be built is a bug in this code, not in the request.
	loc, err := a.show.URL(routing.Params{"slug": art.Slug})
	if err != nil {
		panic(err)
	}
//line controller.ego:103
	return httpkernel.Created[Article]{Location: loc, Body: art}, nil
}
