// Code generated by ego generate from store.ego. DO NOT EDIT.

package articles

import (
	"context"
	"database/sql"
	"encoding/json/v2"
	"errors"
	"fmt"
	"time"

	"github.com/goncini/goncini/db"

	"github.com/effect-go/effect-go/trace"
)

// Store keeps the articles in the database.
//
//line store.ego:14
type Store struct {
	sql *db.SQL
}

func NewStore(s *db.SQL) *Store {
	return &Store{sql: s}
}

// List returns the newest articles first, at most limit of them, with the
// tag if it isn't empty, and how many there are in all.
func (s *Store) List(ctx context.Context, tag string, limit int) (_ []Article, _ int, err error) {
	ctx, span := trace.Start(ctx, "articles.Store.List")
	defer trace.End(span, &err)
//line store.ego:25
	where, args := "", []any{}
	if tag != "" {
		where, args = " WHERE EXISTS (SELECT 1 FROM json_each(tags) WHERE value = ?)", []any{tag}
	}
	var count int
	if err := s.sql.Conn(ctx).QueryRowContext(ctx, "SELECT count(*) FROM articles"+where, args...).Scan(&count); err != nil {
		return nil, 0, fmt.Errorf("QueryRowContext.Scan: %w", err)
	}
//line store.ego:31
	rows, err := s.sql.Conn(ctx).QueryContext(ctx, "SELECT slug, title, body, tags, created_at FROM articles"+where+" ORDER BY created_at DESC LIMIT ?", append(args, limit)...)
	if err != nil {
		return nil, 0, fmt.Errorf("Conn.QueryContext: %w", err)
	}
//line store.ego:32
	defer rows.Close()
	var list []Article
	for rows.Next() {
		art, err := scan(rows)
		if err != nil {
			return nil, 0, err
		}
//line store.ego:36
		list = append(list, art)
	}
	if err := rows.Err(); err != nil {
		return nil, 0, fmt.Errorf("rows.Err: %w", err)
	}
//line store.ego:39
	return list, count, nil
}

// Get returns the article with the slug, and reports whether there is one.
func (s *Store) Get(ctx context.Context, slug string) (_ Article, _ bool, err error) {
	ctx, span := trace.Start(ctx, "articles.Store.Get")
	defer trace.End(span, &err)
//line store.ego:44
	row := s.sql.Conn(ctx).QueryRowContext(ctx, "SELECT slug, title, body, tags, created_at FROM articles WHERE slug = ?", slug)
	art, err := scan(row)
	if errors.Is(err, sql.ErrNoRows) {
		return Article{}, false, nil
	}
	if err != nil {
		return Article{}, false, err
	}
//line store.ego:50
	return art, true, nil
}

// Add adds an article, unless its slug is taken, and reports whether it
// did. Checking the slug and adding the article is one transaction, which
// Get takes part in.
func (s *Store) Add(ctx context.Context, art Article) (_ bool, err error) {
	ctx, span := trace.Start(ctx, "articles.Store.Add")
	defer trace.End(span, &err)
//line store.ego:57
	added := false
	if err := s.sql.InTx(ctx, func(ctx context.Context) error {
		_, taken, err := s.Get(ctx, art.Slug)
		if err != nil {
			return fmt.Errorf("s.Get: %w", err)
		}
//line store.ego:60
		if taken {
			return nil
		}
		tags, err := json.Marshal(art.Tags)
		if err != nil {
			return err
		}
//line store.ego:64
		if _, err := s.sql.Conn(ctx).ExecContext(ctx, "INSERT INTO articles (slug, title, body, tags, created_at) VALUES (?, ?, ?, ?, ?)",
			art.Slug, art.Title, art.Body, string(tags), art.CreatedAt.UnixMicro()); err != nil {
			return fmt.Errorf("Conn.ExecContext: %w", err)
		}
//line store.ego:66
		added = true
		return nil
	}); err != nil {
		return false, err
	}
//line store.ego:69
	return added, nil
}

// scan reads an article from a row.
func scan(row interface{ Scan(dest ...any) error }) (Article, error) {
	var art Article
	var tags string
	var created int64
	if err := row.Scan(&art.Slug, &art.Title, &art.Body, &tags, &created); err != nil {
		return Article{}, err
	}
//line store.ego:78
	if err := json.Unmarshal([]byte(tags), &art.Tags); err != nil {
		return Article{}, err
	}
//line store.ego:79
	art.CreatedAt = time.UnixMicro(created).UTC()
	return art, nil
}
