// Code generated by ego generate from doc.ego. DO NOT EDIT.

// Package client is a client of the RealWorld API, generated by
// oapi-codegen from the OpenAPI document that goncini generates for the
// app, testdata/openapi/conduit.json. TestClient drives the app through
// it: a client in another language would see the API the same way.
package client

//go:generate go tool oapi-codegen -generate types,client -package client -o client.gen.go ../testdata/openapi/conduit.json
