// Code generated by ego generate from sql.ego. DO NOT EDIT.

package lock

import (
	"context"
	"database/sql"
	"fmt"
	"sync"
	"sync/atomic"
	"time"

	"github.com/goncini/goncini/db"
)

// SQLStore keeps locks in a table of a SQLite or PostgreSQL database: the
// locks of the processes that share it. It creates its table the first
// time it needs it, unless told not to.
//
//line sql.ego:17
type SQLStore struct {
	pool    *sql.DB
	dialect db.Dialect
	// Table is the table's name; empty means goncini_locks.
	Table string
	// NoSetup leaves creating the table to the app's migrations, with
	// Schema.
	NoSetup bool

	mu       sync.Mutex
	setUp    bool
	acquired atomic.Int64 // acquisitions, to prune expired locks now and then
}

// NewSQLStore returns the store of the pool, a SQLite or PostgreSQL
// database.
func NewSQLStore(pool *sql.DB) (*SQLStore, error) {
	d := db.DialectOf(pool)
	if d == db.Unknown {
		return nil, fmt.Errorf("lock: the SQL store works with SQLite and PostgreSQL, not the %T driver", pool.Driver())
	}
	return &SQLStore{pool: pool, dialect: d}, nil
}

// Schema returns the statement that creates the store's table, for an
// app's migrations.
func (s *SQLStore) Schema() string {
	return fmt.Sprintf("CREATE TABLE IF NOT EXISTS %s (name VARCHAR(255) PRIMARY KEY, owner VARCHAR(64) NOT NULL, expires_at BIGINT NOT NULL)", s.table())
}

func (s *SQLStore) table() string {
	var v string
	if s.Table != "" {
		v = s.Table
	} else {
		v = "goncini_locks"
	}
	return v
}

// ready creates the table once, unless NoSetup says not to: until it
// succeeded, each call tries again.
//
//line sql.ego:53
func (s *SQLStore) ready(ctx context.Context) error {
	if s.NoSetup {
		return nil
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.setUp {
		return nil
	}
	if _, err := s.pool.ExecContext(ctx, s.Schema()); err != nil {
		return err
	}
//line sql.ego:63
	s.setUp = true
	return nil
}

func (s *SQLStore) Acquire(ctx context.Context, key, owner string, ttl time.Duration) (bool, error) {
	if err := s.ready(ctx); err != nil {
		return false, err
	}
//line sql.ego:69
	now := time.Now()
	t := s.table()
	// Insert the lock, or take it over if its owner is this one or its
	// hold has expired: one statement, which no other can interleave with.
	query := s.dialect.Rebind(fmt.Sprintf("INSERT INTO %s (name, owner, expires_at) VALUES (?, ?, ?) ON CONFLICT (name) DO UPDATE SET owner = excluded.owner, expires_at = excluded.expires_at WHERE %s.owner = excluded.owner OR %s.expires_at <= ?", t, t, t))
	res, err := s.pool.ExecContext(ctx, query, key, owner, now.Add(ttl).UnixMilli(), now.UnixMilli())
	if err != nil {
		return false, fmt.Errorf("pool.ExecContext: %w", err)
	}
//line sql.ego:75
	n, err := res.RowsAffected()
	if err != nil {
		return false, fmt.Errorf("res.RowsAffected: %w", err)
	}
//line sql.ego:76
	if s.acquired.Add(1)%256 == 0 {
		// Locks of keys used once, such as a scheduler's ticks, would stay.
		// A failure is no matter: the next prune does it.
		s.pool.ExecContext(ctx, s.dialect.Rebind(fmt.Sprintf("DELETE FROM %s WHERE expires_at <= ?", t)), now.UnixMilli())
	}
	return n == 1, nil
}

func (s *SQLStore) Release(ctx context.Context, key, owner string) error {
	if err := s.ready(ctx); err != nil {
		return err
	}
//line sql.ego:86
	if _, err := s.pool.ExecContext(ctx, s.dialect.Rebind(fmt.Sprintf("DELETE FROM %s WHERE name = ? AND owner = ?", s.table())), key, owner); err != nil {
		return fmt.Errorf("pool.ExecContext: %w", err)
	}
//line sql.ego:87
	return nil
}
